local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Alchemy
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 131 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(171, {
		[2329] = {
			["name"] = "Elixir of Lion's Strength",
		},
		[2330] = {
			["name"] = "Minor Healing Potion",
		},
		[2331] = {
			["name"] = "Minor Mana Potion",
		},
		[2332] = {
			["name"] = "Minor Rejuvenation Potion",
		},
		[2333] = {
			["name"] = "Elixir of Lesser Agility",
		},
		[2334] = {
			["name"] = "Elixir of Minor Fortitude",
		},
		[2335] = {
			["name"] = "Swiftness Potion",
		},
		[2336] = {
			["name"] = "Elixir of Tongues",
		},
		[2337] = {
			["name"] = "Lesser Healing Potion",
		},
		[3170] = {
			["name"] = "Weak Troll's Blood Potion",
		},
		[3171] = {
			["name"] = "Elixir of Wisdom",
		},
		[3172] = {
			["name"] = "Minor Magic Resistance Potion",
		},
		[3173] = {
			["name"] = "Lesser Mana Potion",
		},
		[3174] = {
			["name"] = "Elixir of Poison Resistance",
		},
		[3175] = {
			["name"] = "Limited Invulnerability Potion",
		},
		[3176] = {
			["name"] = "Strong Troll's Blood Potion",
		},
		[3177] = {
			["name"] = "Elixir of Defense",
		},
		[3188] = {
			["name"] = "Elixir of Ogre's Strength",
		},
		[3230] = {
			["name"] = "Elixir of Minor Agility",
		},
		[3447] = {
			["name"] = "Healing Potion",
		},
		[3448] = {
			["name"] = "Lesser Invisibility Potion",
		},
		[3449] = {
			["name"] = "Shadow Oil",
		},
		[3450] = {
			["name"] = "Elixir of Fortitude",
		},
		[3451] = {
			["name"] = "Mighty Troll's Blood Potion",
		},
		[3452] = {
			["name"] = "Mana Potion",
		},
		[3453] = {
			["name"] = "Elixir of Detect Lesser Invisibility",
		},
		[3454] = {
			["name"] = "Frost Oil",
		},
		[4508] = {
			["name"] = "Discolored Healing Potion",
		},
		[4942] = {
			["name"] = "Lesser Stoneshield Potion",
		},
		[6617] = {
			["name"] = "Rage Potion",
		},
		[6618] = {
			["name"] = "Great Rage Potion",
		},
		[6619] = {
			["name"] = "Cowardly Flight Potion",
		},
		[6624] = {
			["name"] = "Free Action Potion",
		},
		[7179] = {
			["name"] = "Elixir of Water Breathing",
		},
		[7181] = {
			["name"] = "Greater Healing Potion",
		},
		[7183] = {
			["name"] = "Elixir of Minor Defense",
		},
		[7255] = {
			["name"] = "Holy Protection Potion",
		},
		[7256] = {
			["name"] = "Shadow Protection Potion",
		},
		[7257] = {
			["name"] = "Fire Protection Potion",
		},
		[7258] = {
			["name"] = "Frost Protection Potion",
		},
		[7259] = {
			["name"] = "Nature Protection Potion",
		},
		[7836] = {
			["name"] = "Blackmouth Oil",
		},
		[7837] = {
			["name"] = "Fire Oil",
		},
		[7841] = {
			["name"] = "Swim Speed Potion",
		},
		[7845] = {
			["name"] = "Elixir of Firepower",
		},
		[8240] = {
			["name"] = "Elixir of Giant Growth",
		},
		[11448] = {
			["name"] = "Greater Mana Potion",
		},
		[11449] = {
			["name"] = "Elixir of Agility",
		},
		[11450] = {
			["name"] = "Elixir of Greater Defense",
		},
		[11451] = {
			["name"] = "Oil of Immolation",
		},
		[11452] = {
			["name"] = "Restorative Potion",
		},
		[11453] = {
			["name"] = "Magic Resistance Potion",
		},
		[11456] = {
			["name"] = "Goblin Rocket Fuel",
		},
		[11457] = {
			["name"] = "Superior Healing Potion",
		},
		[11458] = {
			["name"] = "Wildvine Potion",
		},
		[11459] = {
			["name"] = "Philosophers' Stone",
		},
		[11460] = {
			["name"] = "Elixir of Detect Undead",
		},
		[11461] = {
			["name"] = "Arcane Elixir",
		},
		[11464] = {
			["name"] = "Invisibility Potion",
		},
		[11465] = {
			["name"] = "Elixir of Greater Intellect",
		},
		[11466] = {
			["name"] = "Gift of Arthas",
		},
		[11467] = {
			["name"] = "Elixir of Greater Agility",
		},
		[11468] = {
			["name"] = "Elixir of Dream Vision",
		},
		[11472] = {
			["name"] = "Elixir of Giants",
		},
		[11473] = {
			["name"] = "Ghost Dye",
		},
		[11476] = {
			["name"] = "Elixir of Shadow Power",
		},
		[11477] = {
			["name"] = "Elixir of Demonslaying",
		},
		[11478] = {
			["name"] = "Elixir of Detect Demon",
		},
		[11479] = {
			["name"] = "Transmute: Iron to Gold",
		},
		[11480] = {
			["name"] = "Transmute: Mithril to Truesilver",
		},
		[12609] = {
			["name"] = "Catseye Elixir",
		},
		[15833] = {
			["name"] = "Dreamless Sleep Potion",
		},
		[17187] = {
			["name"] = "Transmute: Arcanite",
		},
		[17551] = {
			["name"] = "Stonescale Oil",
		},
		[17552] = {
			["name"] = "Mighty Rage Potion",
		},
		[17553] = {
			["name"] = "Superior Mana Potion",
		},
		[17554] = {
			["name"] = "Elixir of Superior Defense",
		},
		[17555] = {
			["name"] = "Elixir of the Sages",
		},
		[17556] = {
			["name"] = "Major Healing Potion",
		},
		[17557] = {
			["name"] = "Elixir of Brute Force",
		},
		[17559] = {
			["name"] = "Transmute: Air to Fire",
		},
		[17560] = {
			["name"] = "Transmute: Fire to Earth",
		},
		[17561] = {
			["name"] = "Transmute: Earth to Water",
		},
		[17562] = {
			["name"] = "Transmute: Water to Air",
		},
		[17563] = {
			["name"] = "Transmute: Undeath to Water",
		},
		[17564] = {
			["name"] = "Transmute: Water to Undeath",
		},
		[17565] = {
			["name"] = "Transmute: Life to Earth",
		},
		[17566] = {
			["name"] = "Transmute: Earth to Life",
		},
		[17570] = {
			["name"] = "Greater Stoneshield Potion",
		},
		[17571] = {
			["name"] = "Elixir of the Mongoose",
		},
		[17572] = {
			["name"] = "Purification Potion",
		},
		[17573] = {
			["name"] = "Greater Arcane Elixir",
		},
		[17574] = {
			["name"] = "Greater Fire Protection Potion",
		},
		[17575] = {
			["name"] = "Greater Frost Protection Potion",
		},
		[17576] = {
			["name"] = "Greater Nature Protection Potion",
		},
		[17577] = {
			["name"] = "Greater Arcane Protection Potion",
		},
		[17578] = {
			["name"] = "Greater Shadow Protection Potion",
		},
		[17579] = {
			["name"] = "Greater Holy Protection Potion",
		},
		[17580] = {
			["name"] = "Major Mana Potion",
		},
		[17632] = {
			["name"] = "Alchemist's Stone",
		},
		[17634] = {
			["name"] = "Flask of Petrification",
		},
		[17635] = {
			["name"] = "Flask of the Titans",
		},
		[17636] = {
			["name"] = "Flask of Distilled Wisdom",
		},
		[17637] = {
			["name"] = "Flask of Supreme Power",
		},
		[17638] = {
			["name"] = "Flask of Chromatic Resistance",
		},
		[21923] = {
			["name"] = "Elixir of Frost Power",
		},
		[22732] = {
			["name"] = "Major Rejuvenation Potion",
		},
		[22808] = {
			["name"] = "Elixir of Greater Water Breathing",
		},
		[24266] = {
			["name"] = "Gurubashi Mojo Madness",
		},
		[24365] = {
			["name"] = "Mageblood Potion",
		},
		[24366] = {
			["name"] = "Greater Dreamless Sleep Potion",
		},
		[24367] = {
			["name"] = "Living Action Potion",
		},
		[24368] = {
			["name"] = "Major Troll's Blood Potion",
		},
		[25146] = {
			["name"] = "Transmute: Elemental Fire",
		},
		[26277] = {
			["name"] = "Elixir of Greater Firepower",
		},
		[426607] = {
			["name"] = "Elixir of Coalesced Regret",
		},
		[435969] = {
			["name"] = "Insulating Gniodine",
		},
		[435971] = {
			["name"] = "Mildly Irradiated Rejuvenation Potion",
		},
		[439960] = {
			["name"] = "Lesser Arcane Elixir",
		},
		[446226] = {
			["name"] = "Flask of Everlasting Nightmares",
		},
		[446851] = {
			["name"] = "Flask of Nightmarish Mojo",
		},
		[448085] = {
			["name"] = "Flask of Restless Dreams",
		},
		[1213544] = {
			["name"] = "Flask of Unyielding Sorrow",
		},
		[1213546] = {
			["name"] = "Flask of Ancient Knowledge",
		},
		[1213548] = {
			["name"] = "Flask of the Old Gods",
		},
		[1213552] = {
			["name"] = "Flask of Madness",
		},
		[1213559] = {
			["name"] = "Elixir of the Honey Badger",
		},
		[1213563] = {
			["name"] = "Elixir of the Mage-Lord",
		},
		[1213565] = {
			["name"] = "Elixir of the Ironside",
		},
		[1213571] = {
			["name"] = "Elixir of Alacrity",
		},
		[1231583] = {
			["name"] = "Major Discolored Healing Potion",
		},
	})

end
