local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Blacksmithing
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 315 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(164, {
		[2660] = {
			["name"] = "Rough Sharpening Stone",
		},
		[2661] = {
			["name"] = "Copper Chain Belt",
		},
		[2662] = {
			["name"] = "Copper Chain Pants",
		},
		[2663] = {
			["name"] = "Copper Bracers",
		},
		[2664] = {
			["name"] = "Runed Copper Bracers",
		},
		[2665] = {
			["name"] = "Coarse Sharpening Stone",
		},
		[2666] = {
			["name"] = "Runed Copper Belt",
		},
		[2667] = {
			["name"] = "Runed Copper Breastplate",
		},
		[2668] = {
			["name"] = "Rough Bronze Leggings",
		},
		[2670] = {
			["name"] = "Rough Bronze Cuirass",
		},
		[2671] = {
			["name"] = "Rough Bronze Bracers",
		},
		[2672] = {
			["name"] = "Patterned Bronze Bracers",
		},
		[2673] = {
			["name"] = "Silvered Bronze Breastplate",
		},
		[2674] = {
			["name"] = "Heavy Sharpening Stone",
		},
		[2675] = {
			["name"] = "Shining Silver Breastplate",
		},
		[2737] = {
			["name"] = "Copper Mace",
		},
		[2738] = {
			["name"] = "Copper Axe",
		},
		[2739] = {
			["name"] = "Copper Shortsword",
		},
		[2740] = {
			["name"] = "Bronze Mace",
		},
		[2741] = {
			["name"] = "Bronze Axe",
		},
		[2742] = {
			["name"] = "Bronze Shortsword",
		},
		[3115] = {
			["name"] = "Rough Weightstone",
		},
		[3116] = {
			["name"] = "Coarse Weightstone",
		},
		[3117] = {
			["name"] = "Heavy Weightstone",
		},
		[3292] = {
			["name"] = "Heavy Copper Broadsword",
		},
		[3293] = {
			["name"] = "Copper Battle Axe",
		},
		[3294] = {
			["name"] = "Thick War Axe",
		},
		[3295] = {
			["name"] = "Deadly Bronze Poniard",
		},
		[3296] = {
			["name"] = "Heavy Bronze Mace",
		},
		[3297] = {
			["name"] = "Mighty Iron Hammer",
		},
		[3319] = {
			["name"] = "Copper Chain Boots",
		},
		[3320] = {
			["name"] = "Rough Grinding Stone",
		},
		[3321] = {
			["name"] = "Copper Chain Vest",
		},
		[3323] = {
			["name"] = "Runed Copper Gauntlets",
		},
		[3324] = {
			["name"] = "Runed Copper Pants",
		},
		[3325] = {
			["name"] = "Gemmed Copper Gauntlets",
		},
		[3326] = {
			["name"] = "Coarse Grinding Stone",
		},
		[3328] = {
			["name"] = "Rough Bronze Shoulders",
		},
		[3330] = {
			["name"] = "Silvered Bronze Shoulders",
		},
		[3331] = {
			["name"] = "Silvered Bronze Boots",
		},
		[3333] = {
			["name"] = "Silvered Bronze Gauntlets",
		},
		[3334] = {
			["name"] = "Green Iron Boots",
		},
		[3336] = {
			["name"] = "Green Iron Gauntlets",
		},
		[3337] = {
			["name"] = "Heavy Grinding Stone",
		},
		[3491] = {
			["name"] = "Big Bronze Knife",
		},
		[3492] = {
			["name"] = "Hardened Iron Shortsword",
		},
		[3493] = {
			["name"] = "Jade Serpentblade",
		},
		[3494] = {
			["name"] = "Solid Iron Maul",
		},
		[3495] = {
			["name"] = "Golden Iron Destroyer",
		},
		[3496] = {
			["name"] = "Moonsteel Broadsword",
		},
		[3497] = {
			["name"] = "Frost Tiger Blade",
		},
		[3498] = {
			["name"] = "Massive Iron Axe",
		},
		[3500] = {
			["name"] = "Shadow Crescent Axe",
		},
		[3501] = {
			["name"] = "Green Iron Bracers",
		},
		[3502] = {
			["name"] = "Green Iron Helm",
		},
		[3503] = {
			["name"] = "Golden Scale Coif",
		},
		[3504] = {
			["name"] = "Green Iron Shoulders",
		},
		[3505] = {
			["name"] = "Golden Scale Shoulders",
		},
		[3506] = {
			["name"] = "Green Iron Leggings",
		},
		[3507] = {
			["name"] = "Golden Scale Leggings",
		},
		[3508] = {
			["name"] = "Green Iron Hauberk",
		},
		[3511] = {
			["name"] = "Golden Scale Cuirass",
		},
		[3513] = {
			["name"] = "Polished Steel Boots",
		},
		[3515] = {
			["name"] = "Golden Scale Boots",
		},
		[6517] = {
			["name"] = "Pearl-handled Dagger",
		},
		[6518] = {
			["name"] = "Iridescent Hammer",
		},
		[7221] = {
			["name"] = "Iron Shield Spike",
		},
		[7222] = {
			["name"] = "Iron Counterweight",
		},
		[7223] = {
			["name"] = "Golden Scale Bracers",
		},
		[7224] = {
			["name"] = "Steel Weapon Chain",
		},
		[7408] = {
			["name"] = "Heavy Copper Maul",
		},
		[7817] = {
			["name"] = "Rough Bronze Boots",
		},
		[7818] = {
			["name"] = "Silver Rod",
		},
		[8366] = {
			["name"] = "Ironforge Chain",
		},
		[8367] = {
			["name"] = "Ironforge Breastplate",
		},
		[8368] = {
			["name"] = "Ironforge Gauntlets",
		},
		[8768] = {
			["name"] = "Iron Buckle",
		},
		[8880] = {
			["name"] = "Copper Dagger",
		},
		[9811] = {
			["name"] = "Barbaric Iron Shoulders",
		},
		[9813] = {
			["name"] = "Barbaric Iron Breastplate",
		},
		[9814] = {
			["name"] = "Barbaric Iron Helm",
		},
		[9818] = {
			["name"] = "Barbaric Iron Boots",
		},
		[9820] = {
			["name"] = "Barbaric Iron Gloves",
		},
		[9916] = {
			["name"] = "Steel Breastplate",
		},
		[9918] = {
			["name"] = "Solid Sharpening Stone",
		},
		[9920] = {
			["name"] = "Solid Grinding Stone",
		},
		[9921] = {
			["name"] = "Solid Weightstone",
		},
		[9926] = {
			["name"] = "Heavy Mithril Shoulder",
		},
		[9928] = {
			["name"] = "Heavy Mithril Gauntlet",
		},
		[9931] = {
			["name"] = "Mithril Scale Pants",
		},
		[9933] = {
			["name"] = "Heavy Mithril Pants",
		},
		[9935] = {
			["name"] = "Steel Plate Helm",
		},
		[9937] = {
			["name"] = "Mithril Scale Bracers",
		},
		[9939] = {
			["name"] = "Mithril Shield Spike",
		},
		[9942] = {
			["name"] = "Mithril Scale Gloves",
		},
		[9945] = {
			["name"] = "Ornate Mithril Pants",
		},
		[9950] = {
			["name"] = "Ornate Mithril Gloves",
		},
		[9952] = {
			["name"] = "Ornate Mithril Shoulders",
		},
		[9954] = {
			["name"] = "Truesilver Gauntlets",
		},
		[9957] = {
			["name"] = "Orcish War Leggings",
		},
		[9959] = {
			["name"] = "Heavy Mithril Breastplate",
		},
		[9961] = {
			["name"] = "Mithril Coif",
		},
		[9964] = {
			["name"] = "Mithril Spurs",
		},
		[9966] = {
			["name"] = "Mithril Scale Shoulders",
		},
		[9968] = {
			["name"] = "Heavy Mithril Boots",
		},
		[9970] = {
			["name"] = "Heavy Mithril Helm",
		},
		[9972] = {
			["name"] = "Ornate Mithril Breastplate",
		},
		[9974] = {
			["name"] = "Truesilver Breastplate",
		},
		[9979] = {
			["name"] = "Ornate Mithril Boots",
		},
		[9980] = {
			["name"] = "Ornate Mithril Helm",
		},
		[9983] = {
			["name"] = "Copper Claymore",
		},
		[9985] = {
			["name"] = "Bronze Warhammer",
		},
		[9986] = {
			["name"] = "Bronze Greatsword",
		},
		[9987] = {
			["name"] = "Bronze Battle Axe",
		},
		[9993] = {
			["name"] = "Heavy Mithril Axe",
		},
		[9995] = {
			["name"] = "Blue Glittering Axe",
		},
		[9997] = {
			["name"] = "Wicked Mithril Blade",
		},
		[10001] = {
			["name"] = "Big Black Mace",
		},
		[10003] = {
			["name"] = "The Shatterer",
		},
		[10005] = {
			["name"] = "Dazzling Mithril Rapier",
		},
		[10007] = {
			["name"] = "Phantom Blade",
		},
		[10009] = {
			["name"] = "Runed Mithril Hammer",
		},
		[10011] = {
			["name"] = "Blight",
		},
		[10013] = {
			["name"] = "Ebon Shiv",
		},
		[10015] = {
			["name"] = "Truesilver Champion",
		},
		[11454] = {
			["name"] = "Inlaid Mithril Cylinder",
		},
		[11643] = {
			["name"] = "Golden Scale Gauntlets",
		},
		[12259] = {
			["name"] = "Silvered Bronze Leggings",
		},
		[12260] = {
			["name"] = "Rough Copper Vest",
		},
		[14379] = {
			["name"] = "Golden Rod",
		},
		[14380] = {
			["name"] = "Truesilver Rod",
		},
		[15292] = {
			["name"] = "Dark Iron Pulverizer",
		},
		[15293] = {
			["name"] = "Dark Iron Mail",
		},
		[15294] = {
			["name"] = "Dark Iron Sunderer",
		},
		[15295] = {
			["name"] = "Dark Iron Shoulders",
		},
		[15296] = {
			["name"] = "Dark Iron Plate",
		},
		[15972] = {
			["name"] = "Glinting Steel Dagger",
		},
		[15973] = {
			["name"] = "Searing Golden Blade",
		},
		[16639] = {
			["name"] = "Dense Grinding Stone",
		},
		[16640] = {
			["name"] = "Dense Weightstone",
		},
		[16641] = {
			["name"] = "Dense Sharpening Stone",
		},
		[16642] = {
			["name"] = "Thorium Armor",
		},
		[16643] = {
			["name"] = "Thorium Belt",
		},
		[16644] = {
			["name"] = "Thorium Bracers",
		},
		[16645] = {
			["name"] = "Radiant Belt",
		},
		[16646] = {
			["name"] = "Imperial Plate Shoulders",
		},
		[16647] = {
			["name"] = "Imperial Plate Belt",
		},
		[16648] = {
			["name"] = "Radiant Breastplate",
		},
		[16649] = {
			["name"] = "Imperial Plate Bracers",
		},
		[16650] = {
			["name"] = "Wildthorn Mail",
		},
		[16651] = {
			["name"] = "Thorium Shield Spike",
		},
		[16652] = {
			["name"] = "Thorium Boots",
		},
		[16653] = {
			["name"] = "Thorium Helm",
		},
		[16654] = {
			["name"] = "Radiant Gloves",
		},
		[16655] = {
			["name"] = "Fiery Plate Gauntlets",
		},
		[16656] = {
			["name"] = "Radiant Boots",
		},
		[16657] = {
			["name"] = "Imperial Plate Boots",
		},
		[16658] = {
			["name"] = "Imperial Plate Helm",
		},
		[16659] = {
			["name"] = "Radiant Circlet",
		},
		[16660] = {
			["name"] = "Dawnbringer Shoulders",
		},
		[16661] = {
			["name"] = "Storm Gauntlets",
		},
		[16662] = {
			["name"] = "Thorium Leggings",
		},
		[16663] = {
			["name"] = "Imperial Plate Chest",
		},
		[16664] = {
			["name"] = "Runic Plate Shoulders",
		},
		[16665] = {
			["name"] = "Runic Plate Boots",
		},
		[16667] = {
			["name"] = "Demon Forged Breastplate",
		},
		[16724] = {
			["name"] = "Whitesoul Helm",
		},
		[16725] = {
			["name"] = "Radiant Leggings",
		},
		[16726] = {
			["name"] = "Runic Plate Helm",
		},
		[16728] = {
			["name"] = "Helm of the Great Chief",
		},
		[16729] = {
			["name"] = "Lionheart Helm",
		},
		[16730] = {
			["name"] = "Imperial Plate Leggings",
		},
		[16731] = {
			["name"] = "Runic Breastplate",
		},
		[16732] = {
			["name"] = "Runic Plate Leggings",
		},
		[16741] = {
			["name"] = "Stronghold Gauntlets",
		},
		[16742] = {
			["name"] = "Enchanted Thorium Helm",
		},
		[16744] = {
			["name"] = "Enchanted Thorium Leggings",
		},
		[16745] = {
			["name"] = "Enchanted Thorium Breastplate",
		},
		[16746] = {
			["name"] = "Invulnerable Mail",
		},
		[16960] = {
			["name"] = "Thorium Greatsword",
		},
		[16965] = {
			["name"] = "Bleakwood Hew",
		},
		[16967] = {
			["name"] = "Inlaid Thorium Hammer",
		},
		[16969] = {
			["name"] = "Ornate Thorium Handaxe",
		},
		[16970] = {
			["name"] = "Dawn's Edge",
		},
		[16971] = {
			["name"] = "Huge Thorium Battleaxe",
		},
		[16973] = {
			["name"] = "Enchanted Battlehammer",
		},
		[16978] = {
			["name"] = "Blazing Rapier",
		},
		[16980] = {
			["name"] = "Rune Edge",
		},
		[16983] = {
			["name"] = "Serenity",
		},
		[16984] = {
			["name"] = "Volcanic Hammer",
		},
		[16985] = {
			["name"] = "Corruption",
		},
		[16986] = {
			["name"] = "Blood Talon",
		},
		[16987] = {
			["name"] = "Darkspear",
		},
		[16988] = {
			["name"] = "Hammer of the Titans",
		},
		[16990] = {
			["name"] = "Arcanite Champion",
		},
		[16991] = {
			["name"] = "Annihilator",
		},
		[16992] = {
			["name"] = "Frostguard",
		},
		[16993] = {
			["name"] = "Masterwork Stormhammer",
		},
		[16994] = {
			["name"] = "Arcanite Reaper",
		},
		[16995] = {
			["name"] = "Heartseeker",
		},
		[19666] = {
			["name"] = "Silver Skeleton Key",
		},
		[19667] = {
			["name"] = "Golden Skeleton Key",
		},
		[19668] = {
			["name"] = "Truesilver Skeleton Key",
		},
		[19669] = {
			["name"] = "Arcanite Skeleton Key",
		},
		[20201] = {
			["name"] = "Arcanite Rod",
		},
		[20872] = {
			["name"] = "Fiery Chain Girdle",
		},
		[20873] = {
			["name"] = "Fiery Chain Shoulders",
		},
		[20874] = {
			["name"] = "Dark Iron Bracers",
		},
		[20876] = {
			["name"] = "Dark Iron Leggings",
		},
		[20890] = {
			["name"] = "Dark Iron Reaver",
		},
		[20897] = {
			["name"] = "Dark Iron Destroyer",
		},
		[21161] = {
			["name"] = "Sulfuron Hammer",
		},
		[21913] = {
			["name"] = "Edge of Winter",
		},
		[22757] = {
			["name"] = "Elemental Sharpening Stone",
		},
		[23628] = {
			["name"] = "Heavy Timbermaw Belt",
		},
		[23629] = {
			["name"] = "Heavy Timbermaw Boots",
		},
		[23632] = {
			["name"] = "Girdle of the Dawn",
		},
		[23633] = {
			["name"] = "Gloves of the Dawn",
		},
		[23636] = {
			["name"] = "Dark Iron Helm",
		},
		[23637] = {
			["name"] = "Dark Iron Gauntlets",
		},
		[23638] = {
			["name"] = "Black Amnesty",
		},
		[23639] = {
			["name"] = "Blackfury",
		},
		[23650] = {
			["name"] = "Ebon Hand",
		},
		[23652] = {
			["name"] = "Blackguard",
		},
		[23653] = {
			["name"] = "Nightfall",
		},
		[24136] = {
			["name"] = "Bloodsoul Breastplate",
		},
		[24137] = {
			["name"] = "Bloodsoul Shoulders",
		},
		[24138] = {
			["name"] = "Bloodsoul Gauntlets",
		},
		[24139] = {
			["name"] = "Darksoul Breastplate",
		},
		[24140] = {
			["name"] = "Darksoul Leggings",
		},
		[24141] = {
			["name"] = "Darksoul Shoulders",
		},
		[24399] = {
			["name"] = "Dark Iron Boots",
		},
		[24912] = {
			["name"] = "Darkrune Gauntlets",
		},
		[24913] = {
			["name"] = "Darkrune Helm",
		},
		[24914] = {
			["name"] = "Darkrune Breastplate",
		},
		[27585] = {
			["name"] = "Heavy Obsidian Belt",
		},
		[27586] = {
			["name"] = "Jagged Obsidian Shield",
		},
		[27587] = {
			["name"] = "Thick Obsidian Breastplate",
		},
		[27588] = {
			["name"] = "Light Obsidian Belt",
		},
		[27589] = {
			["name"] = "Black Grasp of the Destroyer",
		},
		[27590] = {
			["name"] = "Obsidian Mail Tunic",
		},
		[27829] = {
			["name"] = "Titanic Leggings",
		},
		[27830] = {
			["name"] = "Persuader",
		},
		[27832] = {
			["name"] = "Sageblade",
		},
		[28242] = {
			["name"] = "Icebane Breastplate",
		},
		[28243] = {
			["name"] = "Icebane Gauntlets",
		},
		[28244] = {
			["name"] = "Icebane Bracers",
		},
		[28461] = {
			["name"] = "Ironvine Breastplate",
		},
		[28462] = {
			["name"] = "Ironvine Gloves",
		},
		[28463] = {
			["name"] = "Ironvine Belt",
		},
		[427061] = {
			["name"] = "Mantle of the Second War",
		},
		[429348] = {
			["name"] = "Shifting Silver Breastplate",
		},
		[430397] = {
			["name"] = "Blackfathom Sharpening Stone",
		},
		[435906] = {
			["name"] = "Reflective Truesilver Braincage",
		},
		[435908] = {
			["name"] = "Tempered Interference-Negating Helmet",
		},
		[435910] = {
			["name"] = "Low-Background Truesilver Plates",
		},
		[439120] = {
			["name"] = "Golden Scale Gauntlets",
		},
		[439122] = {
			["name"] = "Golden Scale Boots",
		},
		[439124] = {
			["name"] = "Golden Scale Cuirass",
		},
		[439126] = {
			["name"] = "Golden Scale Coif",
		},
		[439128] = {
			["name"] = "Moonsteel Broadsword",
		},
		[439130] = {
			["name"] = "Golden Scale Shoulders",
		},
		[439132] = {
			["name"] = "Golden Scale Leggings",
		},
		[446179] = {
			["name"] = "Shoulderplates of Dread",
		},
		[446188] = {
			["name"] = "Fearmonger's Shoulderguards",
		},
		[446191] = {
			["name"] = "Baleful Pauldrons",
		},
		[460460] = {
			["name"] = "Sulfuron Hammer",
		},
		[461647] = {
			["name"] = "Skyrider's Masterwork Stormhammer",
		},
		[461651] = {
			["name"] = "Fiery Plate Gauntlets of the Hidden Technique",
		},
		[461667] = {
			["name"] = "Tempered Dark Iron Plate",
		},
		[461669] = {
			["name"] = "Refined Arcanite Champion",
		},
		[461671] = {
			["name"] = "Stronger-hold Gauntlets",
		},
		[461675] = {
			["name"] = "Refined Arcanite Reaper",
		},
		[461712] = {
			["name"] = "Refined Hammer of the Titans",
		},
		[461714] = {
			["name"] = "Desecration",
		},
		[461716] = {
			["name"] = "Deadly Heartseeker",
		},
		[461718] = {
			["name"] = "Tranquility",
		},
		[461730] = {
			["name"] = "Hardened Frostguard",
		},
		[461733] = {
			["name"] = "Finely-Enchanted Battlehammer",
		},
		[461735] = {
			["name"] = "Invincible Mail",
		},
		[461737] = {
			["name"] = "Tempest Gauntlets",
		},
		[461739] = {
			["name"] = "Warcrest of the Great Chief",
		},
		[461743] = {
			["name"] = "Sageblade of the Archmagus",
		},
		[1213481] = {
			["name"] = "Razorspike Headcage",
		},
		[1213484] = {
			["name"] = "Razorspike Shoulderplate",
		},
		[1213490] = {
			["name"] = "Razorspike Battleplate",
		},
		[1213492] = {
			["name"] = "Obsidian Reaver",
		},
		[1213498] = {
			["name"] = "Obsidian Champion",
		},
		[1213500] = {
			["name"] = "Obsidian Destroyer",
		},
		[1213502] = {
			["name"] = "Obsidian Stormhammer",
		},
		[1213504] = {
			["name"] = "Obsidian Sageblade",
		},
		[1213506] = {
			["name"] = "Obsidian Defender",
		},
		[1213643] = {
			["name"] = "Obsidian Grinding Stone",
		},
		[1213709] = {
			["name"] = "Ironvine Belt",
		},
		[1213711] = {
			["name"] = "Ironvine Gloves",
		},
		[1213715] = {
			["name"] = "Ironvine Breastplate",
		},
		[1213746] = {
			["name"] = "Heavy Obsidian Belt",
		},
		[1213748] = {
			["name"] = "Light Obsidian Belt",
		},
		[1214137] = {
			["name"] = "Obsidian Heartseeker",
		},
		[1214257] = {
			["name"] = "Black Grasp of the Destroyer",
		},
		[1214270] = {
			["name"] = "Jagged Obsidian Shield",
		},
		[1214274] = {
			["name"] = "Obsidian Mail Tunic",
		},
		[1214309] = {
			["name"] = "Dreamscale Visor",
		},
		[1215507] = {
			["name"] = "Thick Obsidian Breastplate",
		},
		[1223787] = {
			["name"] = "Icebane Breastplate",
		},
		[1223789] = {
			["name"] = "Icebane Gauntlets",
		},
		[1223791] = {
			["name"] = "Icebane Bracers",
		},
		[1224631] = {
			["name"] = "Scarlet Soldier's Helmet",
		},
		[1224632] = {
			["name"] = "Scarlet Soldier's Spaulders",
		},
		[1224633] = {
			["name"] = "Scarlet Soldier's Chestplate",
		},
		[1224635] = {
			["name"] = "Scarlet Soldier's Protectors",
		},
		[1224636] = {
			["name"] = "Scarlet Soldier's Grips",
		},
		[1224637] = {
			["name"] = "Scarlet Soldier's Waistguard",
		},
		[1224638] = {
			["name"] = "Scarlet Soldier's Legplates",
		},
		[1224639] = {
			["name"] = "Scarlet Soldier's Stompers",
		},
	})

end
