local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Cooking
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 91 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(185, {
		[2538] = {
			["name"] = "Charred Wolf Meat",
		},
		[2539] = {
			["name"] = "Spiced Wolf Meat",
		},
		[2540] = {
			["name"] = "Roasted Boar Meat",
		},
		[2541] = {
			["name"] = "Coyote Steak",
		},
		[2542] = {
			["name"] = "Goretusk Liver Pie",
		},
		[2543] = {
			["name"] = "Westfall Stew",
		},
		[2544] = {
			["name"] = "Crab Cake",
		},
		[2545] = {
			["name"] = "Cooked Crab Claw",
		},
		[2546] = {
			["name"] = "Dry Pork Ribs",
		},
		[2547] = {
			["name"] = "Redridge Goulash",
		},
		[2548] = {
			["name"] = "Succulent Pork Ribs",
		},
		[2549] = {
			["name"] = "Seasoned Wolf Kabob",
		},
		[2795] = {
			["name"] = "Beer Basted Boar Ribs",
		},
		[3370] = {
			["name"] = "Crocolisk Steak",
		},
		[3371] = {
			["name"] = "Blood Sausage",
		},
		[3372] = {
			["name"] = "Murloc Fin Soup",
		},
		[3373] = {
			["name"] = "Crocolisk Gumbo",
		},
		[3376] = {
			["name"] = "Curiously Tasty Omelet",
		},
		[3377] = {
			["name"] = "Gooey Spider Cake",
		},
		[3397] = {
			["name"] = "Big Bear Steak",
		},
		[3398] = {
			["name"] = "Hot Lion Chops",
		},
		[3399] = {
			["name"] = "Tasty Lion Steak",
		},
		[3400] = {
			["name"] = "Soothing Turtle Bisque",
		},
		[3413] = {
			["name"] = "Cooking",
		},
		[4094] = {
			["name"] = "Barbecued Buzzard Wing",
		},
		[6412] = {
			["name"] = "Kaldorei Spider Kabob",
		},
		[6413] = {
			["name"] = "Scorpid Surprise",
		},
		[6414] = {
			["name"] = "Roasted Kodo Meat",
		},
		[6415] = {
			["name"] = "Fillet of Frenzy",
		},
		[6416] = {
			["name"] = "Strider Stew",
		},
		[6417] = {
			["name"] = "Dig Rat Stew",
		},
		[6418] = {
			["name"] = "Crispy Lizard Tail",
		},
		[6419] = {
			["name"] = "Lean Venison",
		},
		[6499] = {
			["name"] = "Boiled Clams",
		},
		[6500] = {
			["name"] = "Goblin Deviled Clams",
		},
		[6501] = {
			["name"] = "Clam Chowder",
		},
		[7213] = {
			["name"] = "Giant Clam Scorcho",
		},
		[7751] = {
			["name"] = "Brilliant Smallfish",
		},
		[7752] = {
			["name"] = "Slitherskin Mackerel",
		},
		[7753] = {
			["name"] = "Longjaw Mud Snapper",
		},
		[7754] = {
			["name"] = "Loch Frenzy Delight",
		},
		[7755] = {
			["name"] = "Bristle Whisker Catfish",
		},
		[7827] = {
			["name"] = "Rainbow Fin Albacore",
		},
		[7828] = {
			["name"] = "Rockscale Cod",
		},
		[8238] = {
			["name"] = "Savory Deviate Delight",
		},
		[8604] = {
			["name"] = "Herb Baked Egg",
		},
		[8607] = {
			["name"] = "Smoked Bear Meat",
		},
		[9513] = {
			["name"] = "Thistle Tea",
		},
		[13028] = {
			["name"] = "Goldthorn Tea",
		},
		[15853] = {
			["name"] = "Lean Wolf Steak",
		},
		[15855] = {
			["name"] = "Roast Raptor",
		},
		[15856] = {
			["name"] = "Hot Wolf Ribs",
		},
		[15861] = {
			["name"] = "Jungle Stew",
		},
		[15863] = {
			["name"] = "Carrion Surprise",
		},
		[15865] = {
			["name"] = "Mystery Stew",
		},
		[15906] = {
			["name"] = "Dragonbreath Chili",
		},
		[15910] = {
			["name"] = "Heavy Kodo Stew",
		},
		[15915] = {
			["name"] = "Spiced Chili Crab",
		},
		[15933] = {
			["name"] = "Monster Omelet",
		},
		[15935] = {
			["name"] = "Crispy Bat Wing",
		},
		[18238] = {
			["name"] = "Spotted Yellowtail",
		},
		[18239] = {
			["name"] = "Cooked Glossy Mightfish",
		},
		[18240] = {
			["name"] = "Grilled Squid",
		},
		[18241] = {
			["name"] = "Filet of Redgill",
		},
		[18242] = {
			["name"] = "Hot Smoked Bass",
		},
		[18243] = {
			["name"] = "Nightfin Soup",
		},
		[18244] = {
			["name"] = "Poached Sunscale Salmon",
		},
		[18245] = {
			["name"] = "Lobster Stew",
		},
		[18246] = {
			["name"] = "Mightfish Steak",
		},
		[18247] = {
			["name"] = "Baked Salmon",
		},
		[18260] = {
			["name"] = "Cooking",
		},
		[20626] = {
			["name"] = "Undermine Clam Chowder",
		},
		[20916] = {
			["name"] = "Mithril Headed Trout",
		},
		[21143] = {
			["name"] = "Gingerbread Cookie",
		},
		[21144] = {
			["name"] = "Egg Nog",
		},
		[21175] = {
			["name"] = "Spider Sausage",
		},
		[22480] = {
			["name"] = "Tender Wolf Steak",
		},
		[22761] = {
			["name"] = "Runn Tum Tuber Surprise",
		},
		[24418] = {
			["name"] = "Heavy Crocolisk Stew",
		},
		[24801] = {
			["name"] = "Smoked Desert Dumplings",
		},
		[25659] = {
			["name"] = "Dirge's Kickin' Chimaerok Chops",
		},
		[25704] = {
			["name"] = "Smoked Sagefish",
		},
		[25954] = {
			["name"] = "Sagefish Delight",
		},
		[30047] = {
			["name"] = "Crystal Throat Lozenge",
		},
		[470359] = {
			["name"] = "Darkclaw Bisque",
		},
		[470370] = {
			["name"] = "Smoked Redgill",
		},
		[1225758] = {
			["name"] = "Prowler Steak",
		},
		[1225759] = {
			["name"] = "Filet o' Flank",
		},
		[1225760] = {
			["name"] = "Sunrise Omelette",
		},
		[1225762] = {
			["name"] = "Specklefin Feast",
		},
		[1225763] = {
			["name"] = "Grand Lobster Banquet",
		},
	})

end
