local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Enchanting
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 199 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(333, {
		[7418] = {
			["effect"] = "Health +5",
			["name"] = "Enchant Bracer - Minor Health",
		},
		[7420] = {
			["effect"] = "Health +5",
			["name"] = "Enchant Chest - Minor Health",
		},
		[7421] = {
			["name"] = "Runed Copper Rod",
		},
		[7426] = {
			["effect"] = "Absorption (10)",
			["name"] = "Enchant Chest - Minor Absorption",
		},
		[7428] = {
			["effect"] = "Defense +1",
			["name"] = "Enchant Bracer - Minor Deflect",
		},
		[7443] = {
			["effect"] = "Mana +5",
			["name"] = "Enchant Chest - Minor Mana",
		},
		[7454] = {
			["effect"] = "+1 All Resistances",
			["name"] = "Enchant Cloak - Minor Resistance",
		},
		[7457] = {
			["effect"] = "Stamina +1",
			["name"] = "Enchant Bracer - Minor Stamina",
		},
		[7745] = {
			["effect"] = "Weapon Damage +2",
			["name"] = "Enchant 2H Weapon - Minor Impact",
		},
		[7748] = {
			["effect"] = "Health +15",
			["name"] = "Enchant Chest - Lesser Health",
		},
		[7766] = {
			["effect"] = "Spirit +1",
			["name"] = "Enchant Bracer - Minor Spirit",
		},
		[7771] = {
			["effect"] = "Armor +10",
			["name"] = "Enchant Cloak - Minor Protection",
		},
		[7776] = {
			["effect"] = "Mana +20",
			["name"] = "Enchant Chest - Lesser Mana",
		},
		[7779] = {
			["effect"] = "Agility +1",
			["name"] = "Enchant Bracer - Minor Agility",
		},
		[7782] = {
			["effect"] = "Strength +1",
			["name"] = "Enchant Bracer - Minor Strength",
		},
		[7786] = {
			["effect"] = "Beastslaying +2",
			["name"] = "Enchant Weapon - Minor Beastslayer",
		},
		[7788] = {
			["effect"] = "Weapon Damage +1",
			["name"] = "Enchant Weapon - Minor Striking",
		},
		[7793] = {
			["effect"] = "Intellect +3",
			["name"] = "Enchant 2H Weapon - Lesser Intellect",
		},
		[7795] = {
			["name"] = "Runed Silver Rod",
		},
		[7857] = {
			["effect"] = "Health +25",
			["name"] = "Enchant Chest - Health",
		},
		[7859] = {
			["effect"] = "Spirit +3",
			["name"] = "Enchant Bracer - Lesser Spirit",
		},
		[7861] = {
			["effect"] = "+5 Fire Resistance",
			["name"] = "Enchant Cloak - Lesser Fire Resistance",
		},
		[7863] = {
			["effect"] = "Stamina +1",
			["name"] = "Enchant Boots - Minor Stamina",
		},
		[7867] = {
			["effect"] = "Agility +1",
			["name"] = "Enchant Boots - Minor Agility",
		},
		[13378] = {
			["effect"] = "Stamina +1",
			["name"] = "Enchant Shield - Minor Stamina",
		},
		[13380] = {
			["effect"] = "Spirit +3",
			["name"] = "Enchant 2H Weapon - Lesser Spirit",
		},
		[13419] = {
			["effect"] = "Agility +1",
			["name"] = "Enchant Cloak - Minor Agility",
		},
		[13421] = {
			["effect"] = "Armor +20",
			["name"] = "Enchant Cloak - Lesser Protection",
		},
		[13464] = {
			["effect"] = "Armor +30",
			["name"] = "Enchant Shield - Lesser Protection",
		},
		[13485] = {
			["effect"] = "Spirit +3",
			["name"] = "Enchant Shield - Lesser Spirit",
		},
		[13501] = {
			["effect"] = "Stamina +3",
			["name"] = "Enchant Bracer - Lesser Stamina",
		},
		[13503] = {
			["effect"] = "Weapon Damage +2",
			["name"] = "Enchant Weapon - Lesser Striking",
		},
		[13522] = {
			["effect"] = "+10 Shadow Resistance",
			["name"] = "Enchant Cloak - Lesser Shadow Resistance",
		},
		[13529] = {
			["effect"] = "Weapon Damage +3",
			["name"] = "Enchant 2H Weapon - Lesser Impact",
		},
		[13536] = {
			["effect"] = "Strength +3",
			["name"] = "Enchant Bracer - Lesser Strength",
		},
		[13538] = {
			["effect"] = "Absorption (25)",
			["name"] = "Enchant Chest - Lesser Absorption",
		},
		[13607] = {
			["effect"] = "Mana +30",
			["name"] = "Enchant Chest - Mana",
		},
		[13612] = {
			["effect"] = "Mining +2",
			["name"] = "Enchant Gloves - Mining",
		},
		[13617] = {
			["effect"] = "Herbalism +2",
			["name"] = "Enchant Gloves - Herbalism",
		},
		[13620] = {
			["effect"] = "Fishing +2",
			["name"] = "Enchant Gloves - Fishing",
		},
		[13622] = {
			["effect"] = "Intellect +3",
			["name"] = "Enchant Bracer - Lesser Intellect",
		},
		[13626] = {
			["effect"] = "All Stats +1",
			["name"] = "Enchant Chest - Minor Stats",
		},
		[13628] = {
			["name"] = "Runed Golden Rod",
		},
		[13631] = {
			["effect"] = "Stamina +3",
			["name"] = "Enchant Shield - Lesser Stamina",
		},
		[13635] = {
			["effect"] = "Armor +30",
			["name"] = "Enchant Cloak - Defense",
		},
		[13637] = {
			["effect"] = "Agility +3",
			["name"] = "Enchant Boots - Lesser Agility",
		},
		[13640] = {
			["effect"] = "Health +35",
			["name"] = "Enchant Chest - Greater Health",
		},
		[13642] = {
			["effect"] = "Spirit +5",
			["name"] = "Enchant Bracer - Spirit",
		},
		[13644] = {
			["effect"] = "Stamina +3",
			["name"] = "Enchant Boots - Lesser Stamina",
		},
		[13646] = {
			["effect"] = "Defense +2",
			["name"] = "Enchant Bracer - Lesser Deflection",
		},
		[13648] = {
			["effect"] = "Stamina +5",
			["name"] = "Enchant Bracer - Stamina",
		},
		[13653] = {
			["effect"] = "Beastslaying +6",
			["name"] = "Enchant Weapon - Lesser Beastslayer",
		},
		[13655] = {
			["effect"] = "Elemental Slayer +6",
			["name"] = "Enchant Weapon - Lesser Elemental Slayer",
		},
		[13657] = {
			["effect"] = "+7 Fire Resistance",
			["name"] = "Enchant Cloak - Fire Resistance",
		},
		[13659] = {
			["effect"] = "Spirit +5",
			["name"] = "Enchant Shield - Spirit",
		},
		[13661] = {
			["effect"] = "Strength +5",
			["name"] = "Enchant Bracer - Strength",
		},
		[13663] = {
			["effect"] = "Mana +50",
			["name"] = "Enchant Chest - Greater Mana",
		},
		[13687] = {
			["effect"] = "Spirit +3",
			["name"] = "Enchant Boots - Lesser Spirit",
		},
		[13689] = {
			["effect"] = "Blocking +2%",
			["name"] = "Enchant Shield - Lesser Block",
		},
		[13693] = {
			["effect"] = "Weapon Damage +3",
			["name"] = "Enchant Weapon - Striking",
		},
		[13695] = {
			["effect"] = "Weapon Damage +5",
			["name"] = "Enchant 2H Weapon - Impact",
		},
		[13698] = {
			["effect"] = "Skinning +5",
			["name"] = "Enchant Gloves - Skinning",
		},
		[13700] = {
			["effect"] = "All Stats +2",
			["name"] = "Enchant Chest - Lesser Stats",
		},
		[13702] = {
			["name"] = "Runed Truesilver Rod",
		},
		[13746] = {
			["effect"] = "Armor +50",
			["name"] = "Enchant Cloak - Greater Defense",
		},
		[13794] = {
			["effect"] = "+3 All Resistances",
			["name"] = "Enchant Cloak - Resistance",
		},
		[13815] = {
			["effect"] = "Agility +5",
			["name"] = "Enchant Gloves - Agility",
		},
		[13817] = {
			["effect"] = "Stamina +5",
			["name"] = "Enchant Shield - Stamina",
		},
		[13822] = {
			["effect"] = "Intellect +5",
			["name"] = "Enchant Bracer - Intellect",
		},
		[13836] = {
			["effect"] = "Stamina +5",
			["name"] = "Enchant Boots - Stamina",
		},
		[13841] = {
			["effect"] = "Mining +5",
			["name"] = "Enchant Gloves - Advanced Mining",
		},
		[13846] = {
			["effect"] = "Spirit +7",
			["name"] = "Enchant Bracer - Greater Spirit",
		},
		[13858] = {
			["effect"] = "Health +50",
			["name"] = "Enchant Chest - Superior Health",
		},
		[13868] = {
			["effect"] = "Herbalism +5",
			["name"] = "Enchant Gloves - Advanced Herbalism",
		},
		[13882] = {
			["effect"] = "Agility +3",
			["name"] = "Enchant Cloak - Lesser Agility",
		},
		[13887] = {
			["effect"] = "Strength +5",
			["name"] = "Enchant Gloves - Strength",
		},
		[13890] = {
			["effect"] = "Minor Speed Increase",
			["name"] = "Enchant Boots - Minor Speed",
		},
		[13898] = {
			["effect"] = "Fiery Weapon",
			["name"] = "Enchant Weapon - Fiery Weapon",
		},
		[13905] = {
			["effect"] = "Spirit +7",
			["name"] = "Enchant Shield - Greater Spirit",
		},
		[13915] = {
			["effect"] = "Demonslaying",
			["name"] = "Enchant Weapon - Demonslaying",
		},
		[13917] = {
			["effect"] = "Mana +65",
			["name"] = "Enchant Chest - Superior Mana",
		},
		[13931] = {
			["effect"] = "Defense +3",
			["name"] = "Enchant Bracer - Deflection",
		},
		[13933] = {
			["effect"] = "+8 Frost Resistance",
			["name"] = "Enchant Shield - Frost Resistance",
		},
		[13935] = {
			["effect"] = "Agility +5",
			["name"] = "Enchant Boots - Agility",
		},
		[13937] = {
			["effect"] = "Weapon Damage +7",
			["name"] = "Enchant 2H Weapon - Greater Impact",
		},
		[13939] = {
			["effect"] = "Strength +7",
			["name"] = "Enchant Bracer - Greater Strength",
		},
		[13941] = {
			["effect"] = "All Stats +3",
			["name"] = "Enchant Chest - Stats",
		},
		[13943] = {
			["effect"] = "Weapon Damage +4",
			["name"] = "Enchant Weapon - Greater Striking",
		},
		[13945] = {
			["effect"] = "Stamina +7",
			["name"] = "Enchant Bracer - Greater Stamina",
		},
		[13947] = {
			["effect"] = "Minor Mount Speed Increase",
			["name"] = "Enchant Gloves - Riding Skill",
		},
		[13948] = {
			["effect"] = "Attack Speed +1%",
			["name"] = "Enchant Gloves - Minor Haste",
		},
		[14293] = {
			["name"] = "Lesser Magic Wand",
		},
		[14807] = {
			["name"] = "Greater Magic Wand",
		},
		[14809] = {
			["name"] = "Lesser Mystic Wand",
		},
		[14810] = {
			["name"] = "Greater Mystic Wand",
		},
		[15596] = {
			["name"] = "Smoking Heart of the Mountain",
		},
		[17180] = {
			["name"] = "Enchanted Thorium",
		},
		[17181] = {
			["name"] = "Enchanted Leather",
		},
		[20008] = {
			["effect"] = "Intellect +7",
			["name"] = "Enchant Bracer - Greater Intellect",
		},
		[20009] = {
			["effect"] = "Spirit +9",
			["name"] = "Enchant Bracer - Superior Spirit",
		},
		[20010] = {
			["effect"] = "Strength +9",
			["name"] = "Enchant Bracer - Superior Strength",
		},
		[20011] = {
			["effect"] = "Stamina +9",
			["name"] = "Enchant Bracer - Superior Stamina",
		},
		[20012] = {
			["effect"] = "Agility +7",
			["name"] = "Enchant Gloves - Greater Agility",
		},
		[20013] = {
			["effect"] = "Strength +7",
			["name"] = "Enchant Gloves - Greater Strength",
		},
		[20014] = {
			["effect"] = "+5 All Resistances",
			["name"] = "Enchant Cloak - Greater Resistance",
		},
		[20015] = {
			["effect"] = "Armor +70",
			["name"] = "Enchant Cloak - Superior Defense",
		},
		[20016] = {
			["effect"] = "Spirit +9",
			["name"] = "Enchant Shield - Superior Spirit",
		},
		[20017] = {
			["effect"] = "Stamina +7",
			["name"] = "Enchant Shield - Greater Stamina",
		},
		[20020] = {
			["effect"] = "Stamina +7",
			["name"] = "Enchant Boots - Greater Stamina",
		},
		[20023] = {
			["effect"] = "Agility +7",
			["name"] = "Enchant Boots - Greater Agility",
		},
		[20024] = {
			["effect"] = "Spirit +5",
			["name"] = "Enchant Boots - Spirit",
		},
		[20025] = {
			["effect"] = "All Stats +4",
			["name"] = "Enchant Chest - Greater Stats",
		},
		[20026] = {
			["effect"] = "Health +100",
			["name"] = "Enchant Chest - Major Health",
		},
		[20028] = {
			["effect"] = "Mana +100",
			["name"] = "Enchant Chest - Major Mana",
		},
		[20029] = {
			["effect"] = "Icy Weapon",
			["name"] = "Enchant Weapon - Icy Chill",
		},
		[20030] = {
			["effect"] = "Weapon Damage +9",
			["name"] = "Enchant 2H Weapon - Superior Impact",
		},
		[20031] = {
			["effect"] = "Weapon Damage +5",
			["name"] = "Enchant Weapon - Superior Striking",
		},
		[20032] = {
			["effect"] = "Lifestealing",
			["name"] = "Enchant Weapon - Lifestealing",
		},
		[20033] = {
			["effect"] = "Unholy Weapon",
			["name"] = "Enchant Weapon - Unholy Weapon",
		},
		[20034] = {
			["effect"] = "Crusader",
			["name"] = "Enchant Weapon - Crusader",
		},
		[20035] = {
			["effect"] = "Spirit +9",
			["name"] = "Enchant 2H Weapon - Major Spirit",
		},
		[20036] = {
			["effect"] = "Intellect +9",
			["name"] = "Enchant 2H Weapon - Major Intellect",
		},
		[20051] = {
			["name"] = "Runed Arcanite Rod",
		},
		[21931] = {
			["effect"] = "Frost Spell Damage +7",
			["name"] = "Enchant Weapon - Winter's Might",
		},
		[22749] = {
			["effect"] = "Spell Damage +30",
			["name"] = "Enchant  Weapon - Spell Power",
		},
		[22750] = {
			["effect"] = "Healing Spells +55",
			["name"] = "Enchant  Weapon - Healing Power",
		},
		[23799] = {
			["effect"] = "Strength +15",
			["name"] = "Enchant Weapon - Strength",
		},
		[23800] = {
			["effect"] = "Agility +15",
			["name"] = "Enchant Weapon - Agility",
		},
		[23801] = {
			["effect"] = "Mana Regen 4 per 5 sec.",
			["name"] = "Enchant Bracer - Mana Regeneration",
		},
		[23802] = {
			["effect"] = "Healing Spells +24",
			["name"] = "Enchant Bracer - Healing Power",
		},
		[23803] = {
			["effect"] = "Spirit +20",
			["name"] = "Enchant Weapon - Mighty Spirit",
		},
		[23804] = {
			["effect"] = "Intellect +22",
			["name"] = "Enchant Weapon - Mighty Intellect",
		},
		[25072] = {
			["effect"] = "Threat +2%",
			["name"] = "Enchant Gloves - Threat",
		},
		[25073] = {
			["effect"] = "Shadow Damage +20",
			["name"] = "Enchant Gloves - Shadow Power",
		},
		[25074] = {
			["effect"] = "Frost Damage +20",
			["name"] = "Enchant Gloves - Frost Power",
		},
		[25078] = {
			["effect"] = "Fire Damage +20",
			["name"] = "Enchant Gloves - Fire Power",
		},
		[25079] = {
			["effect"] = "Healing Spells +30",
			["name"] = "Enchant Gloves - Healing Power",
		},
		[25080] = {
			["effect"] = "Agility +15",
			["name"] = "Enchant Gloves - Superior Agility",
		},
		[25081] = {
			["effect"] = "+15 Fire Resistance",
			["name"] = "Enchant Cloak - Greater Fire Resistance",
		},
		[25082] = {
			["effect"] = "+15 Nature Resistance",
			["name"] = "Enchant Cloak - Greater Nature Resistance",
		},
		[25083] = {
			["effect"] = "Increased Stealth",
			["name"] = "Enchant Cloak - Stealth",
		},
		[25084] = {
			["effect"] = "Subtlety",
			["name"] = "Enchant Cloak - Subtlety",
		},
		[25086] = {
			["effect"] = "Dodge +1%",
			["name"] = "Enchant Cloak - Dodge",
		},
		[25124] = {
			["name"] = "Minor Wizard Oil",
		},
		[25125] = {
			["name"] = "Minor Mana Oil",
		},
		[25126] = {
			["name"] = "Lesser Wizard Oil",
		},
		[25127] = {
			["name"] = "Lesser Mana Oil",
		},
		[25128] = {
			["name"] = "Wizard Oil",
		},
		[25129] = {
			["name"] = "Brilliant Wizard Oil",
		},
		[25130] = {
			["name"] = "Brilliant Mana Oil",
		},
		[27837] = {
			["effect"] = "Agility +25",
			["name"] = "Enchant 2H Weapon - Agility",
		},
		[430409] = {
			["name"] = "Blackfathom Mana Oil",
		},
		[435481] = {
			["effect"] = "Dismantle",
			["name"] = "Enchant Weapon - Dismantle",
		},
		[435903] = {
			["effect"] = "Retricutioner",
			["name"] = "Enchant Chest - Retricutioner",
		},
		[439134] = {
			["name"] = "Greater Mystic Wand",
		},
		[439156] = {
			["name"] = "Sigil of Innovation",
		},
		[446243] = {
			["name"] = "Sigil of Living Dreams",
		},
		[448624] = {
			["name"] = "Scroll of Spatial Mending",
		},
		[463866] = {
			["name"] = "Sigil of Flowing Waters",
		},
		[463869] = {
			["name"] = "Conductive Shield Coating",
		},
		[463871] = {
			["effect"] = "Law of Nature",
			["name"] = "Enchant Shield - Law of Nature",
		},
		[471400] = {
			["name"] = "Magnificent Trollshine",
		},
		[1213593] = {
			["name"] = "Speedstone",
		},
		[1213595] = {
			["name"] = "Tear of the Dreamer",
		},
		[1213598] = {
			["name"] = "Lodestone of Retaliation",
		},
		[1213600] = {
			["name"] = "Enchanted Stopwatch",
		},
		[1213603] = {
			["name"] = "Ruby-Encrusted Broach",
		},
		[1213607] = {
			["name"] = "Scroll: Wrath of the Swarm",
		},
		[1213610] = {
			["name"] = "Enchanted Repellent",
		},
		[1213616] = {
			["effect"] = "Living Stats",
			["name"] = "Enchant Chest - Living Stats",
		},
		[1213622] = {
			["effect"] = "Holy Damage +20",
			["name"] = "Enchant Gloves - Holy Power",
		},
		[1213626] = {
			["effect"] = "Arcane Damage +20",
			["name"] = "Enchant Gloves - Arcane Power",
		},
		[1213628] = {
			["name"] = "Enchanted Prayer Tome",
		},
		[1213633] = {
			["name"] = "Enchanted Totem",
		},
		[1213635] = {
			["name"] = "Enchanted Mushroom",
		},
		[1216005] = {
			["name"] = "Libram of Righteousness",
		},
		[1216007] = {
			["name"] = "Libram of the Exorcist",
		},
		[1216010] = {
			["name"] = "Libram of Sanctity",
		},
		[1216014] = {
			["name"] = "Totem of Pyroclastic Thunder",
		},
		[1216016] = {
			["name"] = "Totem of Thunderous Strikes",
		},
		[1216018] = {
			["name"] = "Totem of Flowing Magma",
		},
		[1216020] = {
			["name"] = "Idol of Sidereal Wrath",
		},
		[1216022] = {
			["name"] = "Idol of Feline Ferocity",
		},
		[1216024] = {
			["name"] = "Idol of Ursin Power",
		},
		[1217189] = {
			["effect"] = "+12 Spell Damage",
			["name"] = "Enchant Bracer - Spell Power",
		},
		[1217203] = {
			["effect"] = "+9 Agility",
			["name"] = "Enchant Bracer - Agility",
		},
		[1219577] = {
			["effect"] = "+9 Intellect",
			["name"] = "Enchant Off-Hand - Superior Intellect",
		},
		[1219578] = {
			["effect"] = "+12 Spirit",
			["name"] = "Enchant Off-Hand - Excellent Spirit",
		},
		[1219579] = {
			["effect"] = "+6 Intellect and +5 Spirit",
			["name"] = "Enchant Off-Hand - Wisdom",
		},
		[1219580] = {
			["effect"] = "+65 Spell Power",
			["name"] = "Enchant 2H Weapon - Spellblasting",
		},
		[1219581] = {
			["effect"] = "+12 Stamina",
			["name"] = "Enchant Shield - Excellent Stamina",
		},
		[1219586] = {
			["effect"] = "+15 Strength",
			["name"] = "Enchant Gloves - Superior Strength",
		},
		[1219587] = {
			["effect"] = "+5 Agility",
			["name"] = "Enchant Cloak - Agility",
		},
		[1220623] = {
			["effect"] = "+% Critical Strike Chance",
			["name"] = "Enchant Shield - Critical Strike",
		},
		[1220624] = {
			["effect"] = "+16 Spell Power",
			["name"] = "Enchant Bracer - Greater Spellpower",
		},
		[1231128] = {
			["effect"] = "Grand Crusader",
			["name"] = "Enchant Weapon - Grand Crusader",
		},
		[1231139] = {
			["effect"] = "Grand Arcanist",
			["name"] = "Enchant 2H Weapon - Grand Arcanist",
		},
		[1231164] = {
			["effect"] = "Grand Sorcerer",
			["name"] = "Enchant Weapon - Grand Sorceror",
		},
		[1232172] = {
			["effect"] = "Grand Inquisitor",
			["name"] = "Enchant 2H Weapon - Grand Inquisitor",
		},
	})

lib:LoadEnchantsNames({
		[15] = {
			["name"] = "Reinforced Armor +8",
		},
		[16] = {
			["name"] = "Reinforced Armor +16",
		},
		[17] = {
			["name"] = "Reinforced Armor +24",
		},
		[18] = {
			["name"] = "Reinforced Armor +32",
		},
		[464] = {
			["name"] = "Mithril Spurs",
		},
		[1483] = {
			["name"] = "Mana +150",
		},
		[1503] = {
			["name"] = "HP +100",
		},
		[1504] = {
			["name"] = "Armor +125",
		},
		[1505] = {
			["name"] = "+20 Fire Resistance",
		},
		[1506] = {
			["name"] = "Strength +8",
		},
		[1507] = {
			["name"] = "Stamina +8",
		},
		[1508] = {
			["name"] = "Agility +8",
		},
		[1509] = {
			["name"] = "Intellect +8",
		},
		[1510] = {
			["name"] = "Spirit +8",
		},
		[1843] = {
			["name"] = "Reinforced Armor +40",
		},
		[2483] = {
			["name"] = "+5 Fire Resistance",
		},
		[2484] = {
			["name"] = "+5 Frost Resistance",
		},
		[2485] = {
			["name"] = "+5 Arcane Resistance",
		},
		[2486] = {
			["name"] = "+5 Nature Resistance",
		},
		[2487] = {
			["name"] = "+5 Shadow Resistance",
		},
		[2488] = {
			["name"] = "+5 All Resistances",
		},
		[2503] = {
			["name"] = "Defense +3",
		},
		[2543] = {
			["name"] = "Attack Speed +1%",
		},
		[2544] = {
			["name"] = "Healing and Spell Damage +8",
		},
		[2545] = {
			["name"] = "Dodge +1%",
		},
		[2583] = {
			["name"] = "Defense +7/Stamina +10/Block Value +15",
		},
		[2584] = {
			["name"] = "Defense +7/Stamina +10/Healing Spells +24",
		},
		[2585] = {
			["name"] = "Attack Power +28/Dodge +1%",
		},
		[2586] = {
			["name"] = "Ranged Attack Power +24/Stamina +10/Hit +1%",
		},
		[2587] = {
			["name"] = "Healing and Spell Damage +13/Intellect +15",
		},
		[2588] = {
			["name"] = "Healing and Spell Damage +18/Spell Hit +1%",
		},
		[2589] = {
			["name"] = "Healing and Spell Damage +18/Stamina +10",
		},
		[2590] = {
			["name"] = "Mana Regen +4/Stamina +10/Healing Spells +24",
		},
		[2591] = {
			["name"] = "Intellect +10/Stamina +10/Healing Spells +24",
		},
		[2604] = {
			["name"] = "+33 Healing Spells",
		},
		[2605] = {
			["name"] = "+18 Spell Damage and Healing",
		},
		[2606] = {
			["name"] = "+30 Attack Power",
		},
		[2681] = {
			["name"] = "+10 Nature Resistance",
		},
		[2682] = {
			["name"] = "+10 Frost Resistance",
		},
		[2683] = {
			["name"] = "+10 Shadow Resistance",
		},
		[2715] = {
			["name"] = "Healing +31 and 5 mana per 5 sec.",
		},
		[2716] = {
			["name"] = "Stamina +16 and Armor +100",
		},
		[2717] = {
			["name"] = "Attack Power +26 and +1% Critical Strike",
		},
		[2721] = {
			["name"] = "Spell Damage +15 and +1% Spell Critical Strike",
		},
		[7123] = {
			["name"] = "Automatic Crowd Pummeler",
		},
		[7124] = {
			["name"] = "Wolfshead Trophy",
		},
		[7325] = {
			["name"] = "+9 Spell Damage and Healing",
		},
		[7326] = {
			["name"] = "+18 Healing Spells",
		},
		[7328] = {
			["name"] = "+15 Attack Power",
		},
		[7563] = {
			["name"] = "+25 Fire Resistance",
		},
		[7564] = {
			["name"] = "+30 Fire Resistance",
		},
		[7613] = {
			["name"] = "Stamina +20/Intellect +10/Healing Spells +24",
		},
		[7614] = {
			["name"] = "Stamina +20/Hit +1%/Healing and Spell Damage +12",
		},
		[7615] = {
			["name"] = "Stamina +20/Strength +10/Agility +10",
		},
		[7616] = {
			["name"] = "Stamina +20/Strength +10/Defense +7",
		},
		[7617] = {
			["name"] = "Stamina +20/Agility +10/Hit +1%",
		},
		[7618] = {
			["name"] = "Stamina +20/Defense +7/Healing and Spell Damage +12",
		},
		[7619] = {
			["name"] = "Stamina +20/Strength +10/Healing and Spell Damage +12",
		},
		[7620] = {
			["name"] = "Stamina +20/Intellect +10/Healing Spells +22",
		},
		[7621] = {
			["name"] = "Stamina +20/Intellect +10/Healing and Spell Damage +12",
		},
		[7622] = {
			["name"] = "Stamina +20/Intellect +10/Healing Spells +22",
		},
		[7623] = {
			["name"] = "Stamina +20/Intellect +10/Healing and Spell Damage +12",
		},
		[7624] = {
			["name"] = "Stamina +20/Agility +10/Defense +7",
		},
		[7625] = {
			["name"] = "Stamina +20/Agility +10/Hit +1%",
		},
		[7626] = {
			["name"] = "Stamina +20/Strength +10/Healing and Spell Damage +12",
		},
		[7627] = {
			["name"] = "Stamina +20/Hit +1%/Healing and Spell Damage +12",
		},
		[7628] = {
			["name"] = "Stamina +20/Intellect +10/Healing Spells +22",
		},
		[7629] = {
			["name"] = "Stamina +20/Defense +7/Block Chance +2%",
		},
		[7630] = {
			["name"] = "Stamina +20/Hit +1%/Healing and Spell Damage +12",
		},
		[7631] = {
			["name"] = "Stamina +20/Hit +1%/Defense +7",
		},
		[7632] = {
			["name"] = "Stamina +20/Strength +10/Agility +10",
		},
		[7633] = {
			["name"] = "Stamina +20/Defense +7/Block Value +15",
		},
		[7634] = {
			["name"] = "Stamina +20/Intellect +10/Healing and Spell Damage +12",
		},
		[7635] = {
			["name"] = "Stamina +20/Agility +10/Strength +10",
		},
		[7648] = {
			["name"] = "Spell Damage and Healing +10",
		},
		[7649] = {
			["name"] = "Thorns +20",
		},
		[7882] = {
			["name"] = "Healing +31 and +5 mana per 5 sec.",
		},
		[7883] = {
			["name"] = "Spell Damage +14 and +% Critical Strike",
		},
		[7884] = {
			["name"] = "Attack Power +25 and +% Critical Strike",
		},
		[7885] = {
			["name"] = "Stamina +15 and Defense +7",
		},
	})

end
