local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Engineering
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 193 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(202, {
		[3918] = {
			["name"] = "Rough Blasting Powder",
		},
		[3919] = {
			["name"] = "Rough Dynamite",
		},
		[3920] = {
			["name"] = "Crafted Light Shot",
		},
		[3922] = {
			["name"] = "Handful of Copper Bolts",
		},
		[3923] = {
			["name"] = "Rough Copper Bomb",
		},
		[3924] = {
			["name"] = "Copper Tube",
		},
		[3925] = {
			["name"] = "Rough Boomstick",
		},
		[3926] = {
			["name"] = "Copper Modulator",
		},
		[3928] = {
			["name"] = "Mechanical Squirrel",
		},
		[3929] = {
			["name"] = "Coarse Blasting Powder",
		},
		[3930] = {
			["name"] = "Crafted Heavy Shot",
		},
		[3931] = {
			["name"] = "Coarse Dynamite",
		},
		[3932] = {
			["name"] = "Target Dummy",
		},
		[3933] = {
			["name"] = "Small Seaforium Charge",
		},
		[3934] = {
			["name"] = "Flying Tiger Goggles",
		},
		[3936] = {
			["name"] = "Deadly Blunderbuss",
		},
		[3937] = {
			["name"] = "Large Copper Bomb",
		},
		[3938] = {
			["name"] = "Bronze Tube",
		},
		[3939] = {
			["name"] = "Lovingly Crafted Boomstick",
		},
		[3940] = {
			["name"] = "Shadow Goggles",
		},
		[3941] = {
			["name"] = "Small Bronze Bomb",
		},
		[3942] = {
			["name"] = "Whirring Bronze Gizmo",
		},
		[3944] = {
			["name"] = "Flame Deflector",
		},
		[3945] = {
			["name"] = "Heavy Blasting Powder",
		},
		[3946] = {
			["name"] = "Heavy Dynamite",
		},
		[3947] = {
			["name"] = "Crafted Solid Shot",
		},
		[3949] = {
			["name"] = "Silver-plated Shotgun",
		},
		[3950] = {
			["name"] = "Big Bronze Bomb",
		},
		[3952] = {
			["name"] = "Minor Recombobulator",
		},
		[3953] = {
			["name"] = "Bronze Framework",
		},
		[3954] = {
			["name"] = "Moonsight Rifle",
		},
		[3955] = {
			["name"] = "Explosive Sheep",
		},
		[3956] = {
			["name"] = "Green Tinted Goggles",
		},
		[3957] = {
			["name"] = "Ice Deflector",
		},
		[3958] = {
			["name"] = "Iron Strut",
		},
		[3959] = {
			["name"] = "Discombobulator Ray",
		},
		[3960] = {
			["name"] = "Portable Bronze Mortar",
		},
		[3961] = {
			["name"] = "Gyrochronatom",
		},
		[3962] = {
			["name"] = "Iron Grenade",
		},
		[3963] = {
			["name"] = "Compact Harvest Reaper Kit",
		},
		[3965] = {
			["name"] = "Advanced Target Dummy",
		},
		[3966] = {
			["name"] = "Craftsman's Monocle",
		},
		[3967] = {
			["name"] = "Big Iron Bomb",
		},
		[3968] = {
			["name"] = "Goblin Land Mine",
		},
		[3969] = {
			["name"] = "Mechanical Dragonling",
		},
		[3971] = {
			["name"] = "Gnomish Cloaking Device",
		},
		[3972] = {
			["name"] = "Large Seaforium Charge",
		},
		[3973] = {
			["name"] = "Silver Contact",
		},
		[3977] = {
			["name"] = "Crude Scope",
		},
		[3978] = {
			["name"] = "Standard Scope",
		},
		[3979] = {
			["name"] = "Accurate Scope",
		},
		[6458] = {
			["name"] = "Ornate Spyglass",
		},
		[7430] = {
			["name"] = "Arclight Spanner",
		},
		[8243] = {
			["name"] = "Flash Bomb",
		},
		[8334] = {
			["name"] = "Practice Lock",
		},
		[8339] = {
			["name"] = "EZ-Thro Dynamite",
		},
		[8895] = {
			["name"] = "Goblin Rocket Boots",
		},
		[9269] = {
			["name"] = "Gnomish Universal Remote",
		},
		[9271] = {
			["name"] = "Aquadynamic Fish Attractor",
		},
		[9273] = {
			["name"] = "Goblin Jumper Cables",
		},
		[12584] = {
			["name"] = "Gold Power Core",
		},
		[12585] = {
			["name"] = "Solid Blasting Powder",
		},
		[12586] = {
			["name"] = "Solid Dynamite",
		},
		[12587] = {
			["name"] = "Bright-Eye Goggles",
		},
		[12589] = {
			["name"] = "Mithril Tube",
		},
		[12590] = {
			["name"] = "Gyromatic Micro-Adjustor",
		},
		[12591] = {
			["name"] = "Unstable Trigger",
		},
		[12594] = {
			["name"] = "Fire Goggles",
		},
		[12595] = {
			["name"] = "Mithril Blunderbuss",
		},
		[12596] = {
			["name"] = "Hi-Impact Mithril Slugs",
		},
		[12597] = {
			["name"] = "Deadly Scope",
		},
		[12599] = {
			["name"] = "Mithril Casing",
		},
		[12603] = {
			["name"] = "Mithril Frag Bomb",
		},
		[12607] = {
			["name"] = "Catseye Ultra Goggles",
		},
		[12614] = {
			["name"] = "Mithril Heavy-bore Rifle",
		},
		[12615] = {
			["name"] = "Spellpower Goggles Xtreme",
		},
		[12616] = {
			["name"] = "Parachute Cloak",
		},
		[12617] = {
			["name"] = "Deepdive Helmet",
		},
		[12618] = {
			["name"] = "Rose Colored Goggles",
		},
		[12619] = {
			["name"] = "Hi-Explosive Bomb",
		},
		[12620] = {
			["name"] = "Sniper Scope",
		},
		[12621] = {
			["name"] = "Mithril Gyro-Shot",
		},
		[12622] = {
			["name"] = "Green Lens",
		},
		[12624] = {
			["name"] = "Mithril Mechanical Dragonling",
		},
		[12715] = {
			["name"] = "Goblin Rocket Fuel Recipe",
		},
		[12716] = {
			["name"] = "Goblin Mortar",
		},
		[12717] = {
			["name"] = "Goblin Mining Helmet",
		},
		[12718] = {
			["name"] = "Goblin Construction Helmet",
		},
		[12754] = {
			["name"] = "The Big One",
		},
		[12755] = {
			["name"] = "Goblin Bomb Dispenser",
		},
		[12758] = {
			["name"] = "Goblin Rocket Helmet",
		},
		[12759] = {
			["name"] = "Gnomish Death Ray",
		},
		[12760] = {
			["name"] = "Goblin Sapper Charge",
		},
		[12895] = {
			["name"] = "Inlaid Mithril Cylinder Plans",
		},
		[12897] = {
			["name"] = "Gnomish Goggles",
		},
		[12899] = {
			["name"] = "Gnomish Shrink Ray",
		},
		[12902] = {
			["name"] = "Gnomish Net-o-Matic Projector",
		},
		[12903] = {
			["name"] = "Gnomish Harm Prevention Belt",
		},
		[12905] = {
			["name"] = "Gnomish Rocket Boots",
		},
		[12906] = {
			["name"] = "Gnomish Battle Chicken",
		},
		[12907] = {
			["name"] = "Gnomish Mind Control Cap",
		},
		[12908] = {
			["name"] = "Goblin Dragon Gun",
		},
		[13240] = {
			["name"] = "The Mortar: Reloaded",
		},
		[15255] = {
			["name"] = "Mechanical Repair Kit",
		},
		[15628] = {
			["name"] = "Pet Bombling",
		},
		[15633] = {
			["name"] = "Lil' Smoky",
		},
		[19567] = {
			["name"] = "Salt Shaker",
		},
		[19788] = {
			["name"] = "Dense Blasting Powder",
		},
		[19790] = {
			["name"] = "Thorium Grenade",
		},
		[19791] = {
			["name"] = "Thorium Widget",
		},
		[19792] = {
			["name"] = "Thorium Rifle",
		},
		[19793] = {
			["name"] = "Lifelike Mechanical Toad",
		},
		[19794] = {
			["name"] = "Spellpower Goggles Xtreme Plus",
		},
		[19795] = {
			["name"] = "Thorium Tube",
		},
		[19796] = {
			["name"] = "Dark Iron Rifle",
		},
		[19799] = {
			["name"] = "Dark Iron Bomb",
		},
		[19800] = {
			["name"] = "Thorium Shells",
		},
		[19814] = {
			["name"] = "Masterwork Target Dummy",
		},
		[19815] = {
			["name"] = "Delicate Arcanite Converter",
		},
		[19819] = {
			["name"] = "Voice Amplification Modulator",
		},
		[19825] = {
			["name"] = "Master Engineer's Goggles",
		},
		[19830] = {
			["name"] = "Arcanite Dragonling",
		},
		[19831] = {
			["name"] = "Arcane Bomb",
		},
		[19833] = {
			["name"] = "Flawless Arcanite Rifle",
		},
		[21940] = {
			["name"] = "SnowMaster 9000",
		},
		[22704] = {
			["name"] = "Field Repair Bot 74A",
		},
		[22793] = {
			["name"] = "Biznicks 247x128 Accurascope",
		},
		[22795] = {
			["name"] = "Core Marksman Rifle",
		},
		[22797] = {
			["name"] = "Force Reactive Disk",
		},
		[23066] = {
			["name"] = "Red Firework",
		},
		[23067] = {
			["name"] = "Blue Firework",
		},
		[23068] = {
			["name"] = "Green Firework",
		},
		[23069] = {
			["name"] = "EZ-Thro Dynamite II",
		},
		[23070] = {
			["name"] = "Dense Dynamite",
		},
		[23071] = {
			["name"] = "Truesilver Transformer",
		},
		[23077] = {
			["name"] = "Gyrofreeze Ice Reflector",
		},
		[23078] = {
			["name"] = "Goblin Jumper Cables XL",
		},
		[23079] = {
			["name"] = "Major Recombobulator",
		},
		[23080] = {
			["name"] = "Powerful Seaforium Charge",
		},
		[23081] = {
			["name"] = "Hyper-Radiant Flame Reflector",
		},
		[23082] = {
			["name"] = "Ultra-Flash Shadow Reflector",
		},
		[23096] = {
			["name"] = "Alarm-O-Bot",
		},
		[23129] = {
			["name"] = "World Enlarger",
		},
		[23486] = {
			["name"] = "Dimensional Ripper - Everlook",
		},
		[23489] = {
			["name"] = "Ultrasafe Transporter - Gadgetzan",
		},
		[23507] = {
			["name"] = "Snake Burst Firework",
		},
		[24356] = {
			["name"] = "Bloodvine Goggles",
		},
		[24357] = {
			["name"] = "Bloodvine Lens",
		},
		[26011] = {
			["name"] = "Tranquil Mechanical Yeti",
		},
		[26416] = {
			["name"] = "Small Blue Rocket",
		},
		[26417] = {
			["name"] = "Small Green Rocket",
		},
		[26418] = {
			["name"] = "Small Red Rocket",
		},
		[26420] = {
			["name"] = "Large Blue Rocket",
		},
		[26421] = {
			["name"] = "Large Green Rocket",
		},
		[26422] = {
			["name"] = "Large Red Rocket",
		},
		[26423] = {
			["name"] = "Blue Rocket Cluster",
		},
		[26424] = {
			["name"] = "Green Rocket Cluster",
		},
		[26425] = {
			["name"] = "Red Rocket Cluster",
		},
		[26426] = {
			["name"] = "Large Blue Rocket Cluster",
		},
		[26427] = {
			["name"] = "Large Green Rocket Cluster",
		},
		[26428] = {
			["name"] = "Large Red Rocket Cluster",
		},
		[26442] = {
			["name"] = "Firework Launcher",
		},
		[26443] = {
			["name"] = "Firework Cluster Launcher",
		},
		[28327] = {
			["name"] = "Steam Tonk Controller",
		},
		[424641] = {
			["name"] = "Shredder Autosalvage Unit",
		},
		[431362] = {
			["name"] = "Soul Vessel",
		},
		[435956] = {
			["name"] = "Polished Truesilver Gears",
		},
		[435958] = {
			["name"] = "Whirling Truesilver Gearwall",
		},
		[435960] = {
			["name"] = "Hyperconductive Goldwap",
		},
		[435964] = {
			["name"] = "High-Yield Radiation Bomb",
		},
		[435966] = {
			["name"] = "Ez-Thro Radiation Bomb",
		},
		[446236] = {
			["name"] = "Void-Powered Invoker's Vambraces",
		},
		[446237] = {
			["name"] = "Void-Powered Slayer's Vambraces",
		},
		[446238] = {
			["name"] = "Void-Powered Protector's Vambraces",
		},
		[461710] = {
			["name"] = "Fiery Core Sharpshooter Rifle",
		},
		[1213573] = {
			["name"] = "Arcane Megabomb",
		},
		[1213576] = {
			["name"] = "The Fumigator",
		},
		[1213578] = {
			["name"] = "Obsidian Bomb",
		},
		[1213586] = {
			["name"] = "G00 DV-1B3 Generator",
		},
		[1213588] = {
			["name"] = "Tuned Force Reactive Disk",
		},
		[1213646] = {
			["name"] = "Obsidian Blasting Powder",
		},
		[1214145] = {
			["name"] = "Obsidian Shotgun",
		},
		[1217207] = {
			["name"] = "Obsidian Scope",
		},
		[1221012] = {
			["name"] = "Creepy Censor Sensors",
		},
		[1226206] = {
			["name"] = "Tinkerbox",
		},
		[1226207] = {
			["name"] = "Tinkerbox: Teleport",
		},
		[1226208] = {
			["name"] = "Tinkerbox: Nitro Boosts",
		},
		[1226209] = {
			["name"] = "Tinkerbox: Magnetic Displacement",
		},
		[1226210] = {
			["name"] = "Tinker: Teleport",
		},
		[1226211] = {
			["name"] = "Tinker: Nitro Boosts",
		},
		[1226212] = {
			["name"] = "Tinker: Magnetic Displacement",
		},
		[1226213] = {
			["name"] = "Semisafe Transporter: New Avalon",
		},
		[1228088] = {
			["name"] = "Pop-Up Shrub",
		},
	})

end
