local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Firstaid
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 16 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(129, {
		[3275] = {
			["name"] = "Linen Bandage",
		},
		[3276] = {
			["name"] = "Heavy Linen Bandage",
		},
		[3277] = {
			["name"] = "Wool Bandage",
		},
		[3278] = {
			["name"] = "Heavy Wool Bandage",
		},
		[7924] = {
			["name"] = "First Aid",
		},
		[7928] = {
			["name"] = "Silk Bandage",
		},
		[7929] = {
			["name"] = "Heavy Silk Bandage",
		},
		[7934] = {
			["name"] = "Anti-Venom",
		},
		[7935] = {
			["name"] = "Strong Anti-Venom",
		},
		[10840] = {
			["name"] = "Mageweave Bandage",
		},
		[10841] = {
			["name"] = "Heavy Mageweave Bandage",
		},
		[10846] = {
			["name"] = "First Aid",
		},
		[18629] = {
			["name"] = "Runecloth Bandage",
		},
		[18630] = {
			["name"] = "Heavy Runecloth Bandage",
		},
		[23787] = {
			["name"] = "Powerful Anti-Venom",
		},
		[470349] = {
			["name"] = "Dense Runecloth Bandage",
		},
	})

end
