local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Fishing
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 2 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(356, {
		[7732] = {
			["name"] = "Fishing",
		},
		[18248] = {
			["name"] = "Fishing",
		},
	})

end
