local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Leatherworking
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 314 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(165, {
		[2149] = {
			["name"] = "Handstitched Leather Boots",
		},
		[2152] = {
			["name"] = "Light Armor Kit",
		},
		[2153] = {
			["name"] = "Handstitched Leather Pants",
		},
		[2158] = {
			["name"] = "Fine Leather Boots",
		},
		[2159] = {
			["name"] = "Fine Leather Cloak",
		},
		[2160] = {
			["name"] = "Embossed Leather Vest",
		},
		[2161] = {
			["name"] = "Embossed Leather Boots",
		},
		[2162] = {
			["name"] = "Embossed Leather Cloak",
		},
		[2163] = {
			["name"] = "White Leather Jerkin",
		},
		[2164] = {
			["name"] = "Fine Leather Gloves",
		},
		[2165] = {
			["name"] = "Medium Armor Kit",
		},
		[2166] = {
			["name"] = "Toughened Leather Armor",
		},
		[2167] = {
			["name"] = "Dark Leather Boots",
		},
		[2168] = {
			["name"] = "Dark Leather Cloak",
		},
		[2169] = {
			["name"] = "Dark Leather Tunic",
		},
		[2881] = {
			["name"] = "Light Leather",
		},
		[3753] = {
			["name"] = "Handstitched Leather Belt",
		},
		[3756] = {
			["name"] = "Embossed Leather Gloves",
		},
		[3759] = {
			["name"] = "Embossed Leather Pants",
		},
		[3760] = {
			["name"] = "Hillman's Cloak",
		},
		[3761] = {
			["name"] = "Fine Leather Tunic",
		},
		[3762] = {
			["name"] = "Hillman's Leather Vest",
		},
		[3763] = {
			["name"] = "Fine Leather Belt",
		},
		[3764] = {
			["name"] = "Hillman's Leather Gloves",
		},
		[3765] = {
			["name"] = "Dark Leather Gloves",
		},
		[3766] = {
			["name"] = "Dark Leather Belt",
		},
		[3767] = {
			["name"] = "Hillman's Belt",
		},
		[3768] = {
			["name"] = "Hillman's Shoulders",
		},
		[3769] = {
			["name"] = "Dark Leather Shoulders",
		},
		[3770] = {
			["name"] = "Toughened Leather Gloves",
		},
		[3771] = {
			["name"] = "Barbaric Gloves",
		},
		[3772] = {
			["name"] = "Green Leather Armor",
		},
		[3773] = {
			["name"] = "Guardian Armor",
		},
		[3774] = {
			["name"] = "Green Leather Belt",
		},
		[3775] = {
			["name"] = "Guardian Belt",
		},
		[3776] = {
			["name"] = "Green Leather Bracers",
		},
		[3777] = {
			["name"] = "Guardian Leather Bracers",
		},
		[3778] = {
			["name"] = "Gem-studded Leather Belt",
		},
		[3779] = {
			["name"] = "Barbaric Belt",
		},
		[3780] = {
			["name"] = "Heavy Armor Kit",
		},
		[3816] = {
			["name"] = "Cured Light Hide",
		},
		[3817] = {
			["name"] = "Cured Medium Hide",
		},
		[3818] = {
			["name"] = "Cured Heavy Hide",
		},
		[4096] = {
			["name"] = "Raptor Hide Harness",
		},
		[4097] = {
			["name"] = "Raptor Hide Belt",
		},
		[5244] = {
			["name"] = "Kodo Hide Bag",
		},
		[6661] = {
			["name"] = "Barbaric Harness",
		},
		[6702] = {
			["name"] = "Murloc Scale Belt",
		},
		[6703] = {
			["name"] = "Murloc Scale Breastplate",
		},
		[6704] = {
			["name"] = "Thick Murloc Armor",
		},
		[6705] = {
			["name"] = "Murloc Scale Bracers",
		},
		[7126] = {
			["name"] = "Handstitched Leather Vest",
		},
		[7133] = {
			["name"] = "Fine Leather Pants",
		},
		[7135] = {
			["name"] = "Dark Leather Pants",
		},
		[7147] = {
			["name"] = "Guardian Pants",
		},
		[7149] = {
			["name"] = "Barbaric Leggings",
		},
		[7151] = {
			["name"] = "Barbaric Shoulders",
		},
		[7153] = {
			["name"] = "Guardian Cloak",
		},
		[7156] = {
			["name"] = "Guardian Gloves",
		},
		[7953] = {
			["name"] = "Deviate Scale Cloak",
		},
		[7954] = {
			["name"] = "Deviate Scale Gloves",
		},
		[7955] = {
			["name"] = "Deviate Scale Belt",
		},
		[8322] = {
			["name"] = "Moonglow Vest",
		},
		[9058] = {
			["name"] = "Handstitched Leather Cloak",
		},
		[9059] = {
			["name"] = "Handstitched Leather Bracers",
		},
		[9060] = {
			["name"] = "Light Leather Quiver",
		},
		[9062] = {
			["name"] = "Small Leather Ammo Pouch",
		},
		[9064] = {
			["name"] = "Rugged Leather Pants",
		},
		[9065] = {
			["name"] = "Light Leather Bracers",
		},
		[9068] = {
			["name"] = "Light Leather Pants",
		},
		[9070] = {
			["name"] = "Black Whelp Cloak",
		},
		[9072] = {
			["name"] = "Red Whelp Gloves",
		},
		[9074] = {
			["name"] = "Nimble Leather Gloves",
		},
		[9145] = {
			["name"] = "Fletcher's Gloves",
		},
		[9146] = {
			["name"] = "Herbalist's Gloves",
		},
		[9147] = {
			["name"] = "Earthen Leather Shoulders",
		},
		[9148] = {
			["name"] = "Pilferer's Gloves",
		},
		[9149] = {
			["name"] = "Heavy Earthen Gloves",
		},
		[9193] = {
			["name"] = "Heavy Quiver",
		},
		[9194] = {
			["name"] = "Heavy Leather Ammo Pouch",
		},
		[9195] = {
			["name"] = "Dusky Leather Leggings",
		},
		[9196] = {
			["name"] = "Dusky Leather Armor",
		},
		[9197] = {
			["name"] = "Green Whelp Armor",
		},
		[9198] = {
			["name"] = "Frost Leather Cloak",
		},
		[9201] = {
			["name"] = "Dusky Bracers",
		},
		[9202] = {
			["name"] = "Green Whelp Bracers",
		},
		[9206] = {
			["name"] = "Dusky Belt",
		},
		[9207] = {
			["name"] = "Dusky Boots",
		},
		[9208] = {
			["name"] = "Swift Boots",
		},
		[10482] = {
			["name"] = "Cured Thick Hide",
		},
		[10487] = {
			["name"] = "Thick Armor Kit",
		},
		[10490] = {
			["name"] = "Comfortable Leather Hat",
		},
		[10499] = {
			["name"] = "Nightscape Tunic",
		},
		[10507] = {
			["name"] = "Nightscape Headband",
		},
		[10509] = {
			["name"] = "Turtle Scale Gloves",
		},
		[10511] = {
			["name"] = "Turtle Scale Breastplate",
		},
		[10516] = {
			["name"] = "Nightscape Shoulders",
		},
		[10518] = {
			["name"] = "Turtle Scale Bracers",
		},
		[10520] = {
			["name"] = "Big Voodoo Robe",
		},
		[10525] = {
			["name"] = "Tough Scorpid Breastplate",
		},
		[10529] = {
			["name"] = "Wild Leather Shoulders",
		},
		[10531] = {
			["name"] = "Big Voodoo Mask",
		},
		[10533] = {
			["name"] = "Tough Scorpid Bracers",
		},
		[10542] = {
			["name"] = "Tough Scorpid Gloves",
		},
		[10544] = {
			["name"] = "Wild Leather Vest",
		},
		[10546] = {
			["name"] = "Wild Leather Helmet",
		},
		[10548] = {
			["name"] = "Nightscape Pants",
		},
		[10550] = {
			["name"] = "Nightscape Cloak",
		},
		[10552] = {
			["name"] = "Turtle Scale Helm",
		},
		[10554] = {
			["name"] = "Tough Scorpid Boots",
		},
		[10556] = {
			["name"] = "Turtle Scale Leggings",
		},
		[10558] = {
			["name"] = "Nightscape Boots",
		},
		[10560] = {
			["name"] = "Big Voodoo Pants",
		},
		[10562] = {
			["name"] = "Big Voodoo Cloak",
		},
		[10564] = {
			["name"] = "Tough Scorpid Shoulders",
		},
		[10566] = {
			["name"] = "Wild Leather Boots",
		},
		[10568] = {
			["name"] = "Tough Scorpid Leggings",
		},
		[10570] = {
			["name"] = "Tough Scorpid Helm",
		},
		[10572] = {
			["name"] = "Wild Leather Leggings",
		},
		[10574] = {
			["name"] = "Wild Leather Cloak",
		},
		[10619] = {
			["name"] = "Dragonscale Gauntlets",
		},
		[10621] = {
			["name"] = "Wolfshead Helm",
		},
		[10630] = {
			["name"] = "Gauntlets of the Sea",
		},
		[10632] = {
			["name"] = "Helm of Fire",
		},
		[10647] = {
			["name"] = "Feathered Breastplate",
		},
		[10650] = {
			["name"] = "Dragonscale Breastplate",
		},
		[14930] = {
			["name"] = "Quickdraw Quiver",
		},
		[14932] = {
			["name"] = "Thick Leather Ammo Pouch",
		},
		[19047] = {
			["name"] = "Cured Rugged Hide",
		},
		[19048] = {
			["name"] = "Heavy Scorpid Bracers",
		},
		[19049] = {
			["name"] = "Wicked Leather Gauntlets",
		},
		[19050] = {
			["name"] = "Green Dragonscale Breastplate",
		},
		[19051] = {
			["name"] = "Heavy Scorpid Vest",
		},
		[19052] = {
			["name"] = "Wicked Leather Bracers",
		},
		[19053] = {
			["name"] = "Chimeric Gloves",
		},
		[19054] = {
			["name"] = "Red Dragonscale Breastplate",
		},
		[19055] = {
			["name"] = "Runic Leather Gauntlets",
		},
		[19058] = {
			["name"] = "Rugged Armor Kit",
		},
		[19059] = {
			["name"] = "Volcanic Leggings",
		},
		[19060] = {
			["name"] = "Green Dragonscale Leggings",
		},
		[19061] = {
			["name"] = "Living Shoulders",
		},
		[19062] = {
			["name"] = "Ironfeather Shoulders",
		},
		[19063] = {
			["name"] = "Chimeric Boots",
		},
		[19064] = {
			["name"] = "Heavy Scorpid Gauntlets",
		},
		[19065] = {
			["name"] = "Runic Leather Bracers",
		},
		[19066] = {
			["name"] = "Frostsaber Boots",
		},
		[19067] = {
			["name"] = "Stormshroud Pants",
		},
		[19068] = {
			["name"] = "Warbear Harness",
		},
		[19070] = {
			["name"] = "Heavy Scorpid Belt",
		},
		[19071] = {
			["name"] = "Wicked Leather Headband",
		},
		[19072] = {
			["name"] = "Runic Leather Belt",
		},
		[19073] = {
			["name"] = "Chimeric Leggings",
		},
		[19074] = {
			["name"] = "Frostsaber Leggings",
		},
		[19075] = {
			["name"] = "Heavy Scorpid Leggings",
		},
		[19076] = {
			["name"] = "Volcanic Breastplate",
		},
		[19077] = {
			["name"] = "Blue Dragonscale Breastplate",
		},
		[19078] = {
			["name"] = "Living Leggings",
		},
		[19079] = {
			["name"] = "Stormshroud Armor",
		},
		[19080] = {
			["name"] = "Warbear Woolies",
		},
		[19081] = {
			["name"] = "Chimeric Vest",
		},
		[19082] = {
			["name"] = "Runic Leather Headband",
		},
		[19083] = {
			["name"] = "Wicked Leather Pants",
		},
		[19084] = {
			["name"] = "Devilsaur Gauntlets",
		},
		[19085] = {
			["name"] = "Black Dragonscale Breastplate",
		},
		[19086] = {
			["name"] = "Ironfeather Breastplate",
		},
		[19087] = {
			["name"] = "Frostsaber Gloves",
		},
		[19088] = {
			["name"] = "Heavy Scorpid Helm",
		},
		[19089] = {
			["name"] = "Blue Dragonscale Shoulders",
		},
		[19090] = {
			["name"] = "Stormshroud Shoulders",
		},
		[19091] = {
			["name"] = "Runic Leather Pants",
		},
		[19092] = {
			["name"] = "Wicked Leather Belt",
		},
		[19093] = {
			["name"] = "Onyxia Scale Cloak",
		},
		[19094] = {
			["name"] = "Black Dragonscale Shoulders",
		},
		[19095] = {
			["name"] = "Living Breastplate",
		},
		[19097] = {
			["name"] = "Devilsaur Leggings",
		},
		[19098] = {
			["name"] = "Wicked Leather Armor",
		},
		[19100] = {
			["name"] = "Heavy Scorpid Shoulders",
		},
		[19101] = {
			["name"] = "Volcanic Shoulders",
		},
		[19102] = {
			["name"] = "Runic Leather Armor",
		},
		[19103] = {
			["name"] = "Runic Leather Shoulders",
		},
		[19104] = {
			["name"] = "Frostsaber Tunic",
		},
		[19107] = {
			["name"] = "Black Dragonscale Leggings",
		},
		[20648] = {
			["name"] = "Medium Leather",
		},
		[20649] = {
			["name"] = "Heavy Leather",
		},
		[20650] = {
			["name"] = "Thick Leather",
		},
		[20853] = {
			["name"] = "Corehound Boots",
		},
		[20854] = {
			["name"] = "Molten Helm",
		},
		[20855] = {
			["name"] = "Black Dragonscale Boots",
		},
		[21943] = {
			["name"] = "Gloves of the Greatfather",
		},
		[22331] = {
			["name"] = "Rugged Leather",
		},
		[22711] = {
			["name"] = "Shadowskin Gloves",
		},
		[22727] = {
			["name"] = "Core Armor Kit",
		},
		[22815] = {
			["name"] = "Gordok Ogre Suit",
		},
		[22921] = {
			["name"] = "Girdle of Insight",
		},
		[22922] = {
			["name"] = "Mongoose Boots",
		},
		[22923] = {
			["name"] = "Swift Flight Bracers",
		},
		[22926] = {
			["name"] = "Chromatic Cloak",
		},
		[22927] = {
			["name"] = "Hide of the Wild",
		},
		[22928] = {
			["name"] = "Shifting Cloak",
		},
		[23190] = {
			["name"] = "Heavy Leather Ball",
		},
		[23399] = {
			["name"] = "Barbaric Bracers",
		},
		[23703] = {
			["name"] = "Might of the Timbermaw",
		},
		[23704] = {
			["name"] = "Timbermaw Brawlers",
		},
		[23705] = {
			["name"] = "Dawn Treaders",
		},
		[23706] = {
			["name"] = "Golden Mantle of the Dawn",
		},
		[23707] = {
			["name"] = "Lava Belt",
		},
		[23708] = {
			["name"] = "Chromatic Gauntlets",
		},
		[23709] = {
			["name"] = "Corehound Belt",
		},
		[23710] = {
			["name"] = "Molten Belt",
		},
		[24121] = {
			["name"] = "Primal Batskin Jerkin",
		},
		[24122] = {
			["name"] = "Primal Batskin Gloves",
		},
		[24123] = {
			["name"] = "Primal Batskin Bracers",
		},
		[24124] = {
			["name"] = "Blood Tiger Breastplate",
		},
		[24125] = {
			["name"] = "Blood Tiger Shoulders",
		},
		[24654] = {
			["name"] = "Blue Dragonscale Leggings",
		},
		[24655] = {
			["name"] = "Green Dragonscale Gauntlets",
		},
		[24703] = {
			["name"] = "Dreamscale Breastplate",
		},
		[24846] = {
			["name"] = "Spitfire Bracers",
		},
		[24847] = {
			["name"] = "Spitfire Gauntlets",
		},
		[24848] = {
			["name"] = "Spitfire Breastplate",
		},
		[24849] = {
			["name"] = "Sandstalker Bracers",
		},
		[24850] = {
			["name"] = "Sandstalker Gauntlets",
		},
		[24851] = {
			["name"] = "Sandstalker Breastplate",
		},
		[24940] = {
			["name"] = "Black Whelp Tunic",
		},
		[26279] = {
			["name"] = "Stormshroud Gloves",
		},
		[28219] = {
			["name"] = "Polar Tunic",
		},
		[28220] = {
			["name"] = "Polar Gloves",
		},
		[28221] = {
			["name"] = "Polar Bracers",
		},
		[28222] = {
			["name"] = "Icy Scale Breastplate",
		},
		[28223] = {
			["name"] = "Icy Scale Gauntlets",
		},
		[28224] = {
			["name"] = "Icy Scale Bracers",
		},
		[28472] = {
			["name"] = "Bramblewood Helm",
		},
		[28473] = {
			["name"] = "Bramblewood Boots",
		},
		[28474] = {
			["name"] = "Bramblewood Belt",
		},
		[429354] = {
			["name"] = "Void-Touched Leather Gloves",
		},
		[429869] = {
			["name"] = "Void-Touched Leather Gauntlets",
		},
		[435819] = {
			["name"] = "Faintly Glowing Leather",
		},
		[435904] = {
			["name"] = "Glowing Gneuro-Linked Cowl",
		},
		[435949] = {
			["name"] = "Glowing Hyperconductive Scale Coif",
		},
		[435951] = {
			["name"] = "Gneuro-Conductive Channeler's Hood",
		},
		[435953] = {
			["name"] = "Rad-Resistant Scale Hood",
		},
		[439105] = {
			["name"] = "Big Voodoo Mask",
		},
		[439108] = {
			["name"] = "Big Voodoo Robe",
		},
		[439110] = {
			["name"] = "Guardian Leather Bracers",
		},
		[439112] = {
			["name"] = "Guardian Belt",
		},
		[439114] = {
			["name"] = "Guardian Pants",
		},
		[439116] = {
			["name"] = "Turtle Scale Breastplate",
		},
		[439118] = {
			["name"] = "Turtle Scale Gloves",
		},
		[446183] = {
			["name"] = "Paranoia Mantle",
		},
		[446185] = {
			["name"] = "Shrieking Spaulders",
		},
		[446186] = {
			["name"] = "Cacophonous Chain Shoulderguards",
		},
		[446189] = {
			["name"] = "Shoulderpads of Obsession",
		},
		[446190] = {
			["name"] = "Wailing Chain Mantle",
		},
		[446192] = {
			["name"] = "Membrane of Dark Neurosis",
		},
		[451706] = {
			["name"] = "Screaming Chain Pauldrons",
		},
		[461645] = {
			["name"] = "Honed Blue Dragonscale Shoulders",
		},
		[461649] = {
			["name"] = "Living Green Dragonscale Leggings",
		},
		[461653] = {
			["name"] = "Brilliant Chromatic Cloak",
		},
		[461655] = {
			["name"] = "Hardened Black Dragonscale Breastplate",
		},
		[461657] = {
			["name"] = "Hardened Black Dragonscale Leggings",
		},
		[461659] = {
			["name"] = "Hardened Black Dragonscale Shoulders",
		},
		[461661] = {
			["name"] = "Masterwork Volcanic Breastplate",
		},
		[461663] = {
			["name"] = "Masterwork Volcanic Shoulders",
		},
		[461665] = {
			["name"] = "Masterwork Volcanic Leggings",
		},
		[461673] = {
			["name"] = "Honed Blue Dragonscale Breastplate",
		},
		[461677] = {
			["name"] = "Living Green Dragonscale Gauntlets",
		},
		[461690] = {
			["name"] = "Mastercrafted Shifting Cloak",
		},
		[461692] = {
			["name"] = "Synthetic Gordok Ogre Suit",
		},
		[461706] = {
			["name"] = "Swift Flight Vambraces",
		},
		[461720] = {
			["name"] = "Living Green Dragonscale Breastplate",
		},
		[461722] = {
			["name"] = "Devilcore Gauntlets",
		},
		[461724] = {
			["name"] = "Devilcore Leggings",
		},
		[461754] = {
			["name"] = "Girdle of Arcane Insight",
		},
		[462227] = {
			["name"] = "Honed Blue Dragonscale Leggings",
		},
		[1213513] = {
			["name"] = "Glowing Chitin Armor Kit",
		},
		[1213519] = {
			["name"] = "Sharpened Chitin Armor Kit",
		},
		[1213521] = {
			["name"] = "Razorbramble Cowl",
		},
		[1213523] = {
			["name"] = "Razorbramble Shoulderpads",
		},
		[1213525] = {
			["name"] = "Razorbramble Leathers",
		},
		[1213717] = {
			["name"] = "Sandstalker Bracers",
		},
		[1213720] = {
			["name"] = "Sandstalker Gauntlets",
		},
		[1213723] = {
			["name"] = "Sandstalker Breastplate",
		},
		[1213726] = {
			["name"] = "Spitfire Bracers",
		},
		[1213728] = {
			["name"] = "Spitfire Gauntlets",
		},
		[1213731] = {
			["name"] = "Spitfire Breastplate",
		},
		[1213734] = {
			["name"] = "Bramblewood Belt",
		},
		[1213736] = {
			["name"] = "Bramblewood Boots",
		},
		[1213738] = {
			["name"] = "Bramblewood Helm",
		},
		[1213751] = {
			["name"] = "Dreamscale Breastplate",
		},
		[1214303] = {
			["name"] = "Dreamscale Kilt",
		},
		[1223774] = {
			["name"] = "Icy Scale Breastplate",
		},
		[1223776] = {
			["name"] = "Icy Scale Gauntlets",
		},
		[1223778] = {
			["name"] = "Icy Scale Bracers",
		},
		[1223780] = {
			["name"] = "Polar Tunic",
		},
		[1223782] = {
			["name"] = "Polar Gloves",
		},
		[1223784] = {
			["name"] = "Polar Bracers",
		},
		[1224615] = {
			["name"] = "Scarlet Infiltrator's Bandana",
		},
		[1224616] = {
			["name"] = "Scarlet Infiltrator's Shoulderpads",
		},
		[1224617] = {
			["name"] = "Scarlet Infiltrator's Vest",
		},
		[1224618] = {
			["name"] = "Scarlet Infiltrator's Bracers",
		},
		[1224619] = {
			["name"] = "Scarlet Infiltrator's Gloves",
		},
		[1224620] = {
			["name"] = "Scarlet Infiltrator's Belt",
		},
		[1224621] = {
			["name"] = "Scarlet Infiltrator's Trousers",
		},
		[1224622] = {
			["name"] = "Scarlet Infiltrator's Shoes",
		},
		[1224623] = {
			["name"] = "Scarlet Huntsman's Coif",
		},
		[1224624] = {
			["name"] = "Scarlet Huntsman's Pauldrons",
		},
		[1224625] = {
			["name"] = "Scarlet Huntsman's Chain",
		},
		[1224626] = {
			["name"] = "Scarlet Huntsman's Wristguards",
		},
		[1224627] = {
			["name"] = "Scarlet Huntsman's Handguards",
		},
		[1224628] = {
			["name"] = "Scarlet Huntsman's Clasp",
		},
		[1224629] = {
			["name"] = "Scarlet Huntsman's Legguards",
		},
		[1224630] = {
			["name"] = "Scarlet Huntsman's Boots",
		},
		[1226689] = {
			["name"] = "Scarlet Quiver",
		},
		[1226690] = {
			["name"] = "Scarlet Ammo Pouch",
		},
	})

end
