local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Mining
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 13 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(186, {
		[2657] = {
			["name"] = "Smelt Copper",
		},
		[2658] = {
			["name"] = "Smelt Silver",
		},
		[2659] = {
			["name"] = "Smelt Bronze",
		},
		[3304] = {
			["name"] = "Smelt Tin",
		},
		[3307] = {
			["name"] = "Smelt Iron",
		},
		[3308] = {
			["name"] = "Smelt Gold",
		},
		[3569] = {
			["name"] = "Smelt Steel",
		},
		[10097] = {
			["name"] = "Smelt Mithril",
		},
		[10098] = {
			["name"] = "Smelt Truesilver",
		},
		[14891] = {
			["name"] = "Smelt Dark Iron",
		},
		[16153] = {
			["name"] = "Smelt Thorium",
		},
		[22967] = {
			["name"] = "Smelt Elementium",
		},
		[1213638] = {
			["name"] = "Smelt Obsidian-Infused Thorium Bar",
		},
	})

end
