local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB names — WoW Vanilla, enUS, Tailoring
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 291 recipes

if GetLocale() ~= "enUS" then return end
local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadNames(197, {
		[2385] = {
			["name"] = "Brown Linen Vest",
		},
		[2386] = {
			["name"] = "Linen Boots",
		},
		[2387] = {
			["name"] = "Linen Cloak",
		},
		[2389] = {
			["name"] = "Red Linen Robe",
		},
		[2392] = {
			["name"] = "Red Linen Shirt",
		},
		[2393] = {
			["name"] = "White Linen Shirt",
		},
		[2394] = {
			["name"] = "Blue Linen Shirt",
		},
		[2395] = {
			["name"] = "Barbaric Linen Vest",
		},
		[2396] = {
			["name"] = "Green Linen Shirt",
		},
		[2397] = {
			["name"] = "Reinforced Linen Cape",
		},
		[2399] = {
			["name"] = "Green Woolen Vest",
		},
		[2401] = {
			["name"] = "Woolen Boots",
		},
		[2402] = {
			["name"] = "Woolen Cape",
		},
		[2403] = {
			["name"] = "Gray Woolen Robe",
		},
		[2406] = {
			["name"] = "Gray Woolen Shirt",
		},
		[2963] = {
			["name"] = "Bolt of Linen Cloth",
		},
		[2964] = {
			["name"] = "Bolt of Woolen Cloth",
		},
		[3755] = {
			["name"] = "Linen Bag",
		},
		[3757] = {
			["name"] = "Woolen Bag",
		},
		[3758] = {
			["name"] = "Green Woolen Bag",
		},
		[3813] = {
			["name"] = "Small Silk Pack",
		},
		[3839] = {
			["name"] = "Bolt of Silk Cloth",
		},
		[3840] = {
			["name"] = "Heavy Linen Gloves",
		},
		[3841] = {
			["name"] = "Green Linen Bracers",
		},
		[3842] = {
			["name"] = "Handstitched Linen Britches",
		},
		[3843] = {
			["name"] = "Heavy Woolen Gloves",
		},
		[3844] = {
			["name"] = "Heavy Woolen Cloak",
		},
		[3845] = {
			["name"] = "Soft-soled Linen Boots",
		},
		[3847] = {
			["name"] = "Red Woolen Boots",
		},
		[3848] = {
			["name"] = "Double-stitched Woolen Shoulders",
		},
		[3849] = {
			["name"] = "Reinforced Woolen Shoulders",
		},
		[3850] = {
			["name"] = "Heavy Woolen Pants",
		},
		[3851] = {
			["name"] = "Phoenix Pants",
		},
		[3852] = {
			["name"] = "Gloves of Meditation",
		},
		[3854] = {
			["name"] = "Azure Silk Gloves",
		},
		[3855] = {
			["name"] = "Spidersilk Boots",
		},
		[3856] = {
			["name"] = "Spider Silk Slippers",
		},
		[3857] = {
			["name"] = "Enchanter's Cowl",
		},
		[3858] = {
			["name"] = "Shadow Hood",
		},
		[3859] = {
			["name"] = "Azure Silk Vest",
		},
		[3860] = {
			["name"] = "Boots of the Enchanter",
		},
		[3861] = {
			["name"] = "Long Silken Cloak",
		},
		[3862] = {
			["name"] = "Icy Cloak",
		},
		[3863] = {
			["name"] = "Spider Belt",
		},
		[3864] = {
			["name"] = "Star Belt",
		},
		[3865] = {
			["name"] = "Bolt of Mageweave",
		},
		[3866] = {
			["name"] = "Stylish Red Shirt",
		},
		[3868] = {
			["name"] = "Phoenix Gloves",
		},
		[3869] = {
			["name"] = "Bright Yellow Shirt",
		},
		[3870] = {
			["name"] = "Dark Silk Shirt",
		},
		[3871] = {
			["name"] = "Formal White Shirt",
		},
		[3872] = {
			["name"] = "Rich Purple Silk Shirt",
		},
		[3873] = {
			["name"] = "Black Swashbuckler's Shirt",
		},
		[3914] = {
			["name"] = "Brown Linen Pants",
		},
		[3915] = {
			["name"] = "Brown Linen Shirt",
		},
		[6521] = {
			["name"] = "Pearl-clasped Cloak",
		},
		[6686] = {
			["name"] = "Red Linen Bag",
		},
		[6688] = {
			["name"] = "Red Woolen Bag",
		},
		[6690] = {
			["name"] = "Lesser Wizard's Robe",
		},
		[6692] = {
			["name"] = "Robes of Arcana",
		},
		[6693] = {
			["name"] = "Green Silk Pack",
		},
		[6695] = {
			["name"] = "Black Silk Pack",
		},
		[7623] = {
			["name"] = "Brown Linen Robe",
		},
		[7624] = {
			["name"] = "White Linen Robe",
		},
		[7629] = {
			["name"] = "Red Linen Vest",
		},
		[7630] = {
			["name"] = "Blue Linen Vest",
		},
		[7633] = {
			["name"] = "Blue Linen Robe",
		},
		[7636] = {
			["name"] = "Green Woolen Robe",
		},
		[7639] = {
			["name"] = "Blue Overalls",
		},
		[7643] = {
			["name"] = "Greater Adept's Robe",
		},
		[7892] = {
			["name"] = "Stylish Blue Shirt",
		},
		[7893] = {
			["name"] = "Stylish Green Shirt",
		},
		[8465] = {
			["name"] = "Simple Dress",
		},
		[8467] = {
			["name"] = "White Woolen Dress",
		},
		[8483] = {
			["name"] = "White Swashbuckler's Shirt",
		},
		[8489] = {
			["name"] = "Red Swashbuckler's Shirt",
		},
		[8758] = {
			["name"] = "Azure Silk Pants",
		},
		[8760] = {
			["name"] = "Azure Silk Hood",
		},
		[8762] = {
			["name"] = "Silk Headband",
		},
		[8764] = {
			["name"] = "Earthen Vest",
		},
		[8766] = {
			["name"] = "Azure Silk Belt",
		},
		[8770] = {
			["name"] = "Robe of Power",
		},
		[8772] = {
			["name"] = "Crimson Silk Belt",
		},
		[8774] = {
			["name"] = "Green Silken Shoulders",
		},
		[8776] = {
			["name"] = "Linen Belt",
		},
		[8778] = {
			["name"] = "Boots of Darkness",
		},
		[8780] = {
			["name"] = "Hands of Darkness",
		},
		[8782] = {
			["name"] = "Truefaith Gloves",
		},
		[8784] = {
			["name"] = "Green Silk Armor",
		},
		[8786] = {
			["name"] = "Azure Silk Cloak",
		},
		[8789] = {
			["name"] = "Crimson Silk Cloak",
		},
		[8791] = {
			["name"] = "Crimson Silk Vest",
		},
		[8793] = {
			["name"] = "Crimson Silk Shoulders",
		},
		[8795] = {
			["name"] = "Azure Shoulders",
		},
		[8797] = {
			["name"] = "Earthen Silk Belt",
		},
		[8799] = {
			["name"] = "Crimson Silk Pantaloons",
		},
		[8802] = {
			["name"] = "Crimson Silk Robe",
		},
		[8804] = {
			["name"] = "Crimson Silk Gloves",
		},
		[12044] = {
			["name"] = "Simple Linen Pants",
		},
		[12045] = {
			["name"] = "Simple Linen Boots",
		},
		[12046] = {
			["name"] = "Simple Kilt",
		},
		[12047] = {
			["name"] = "Colorful Kilt",
		},
		[12048] = {
			["name"] = "Black Mageweave Vest",
		},
		[12049] = {
			["name"] = "Black Mageweave Leggings",
		},
		[12050] = {
			["name"] = "Black Mageweave Robe",
		},
		[12052] = {
			["name"] = "Shadoweave Pants",
		},
		[12053] = {
			["name"] = "Black Mageweave Gloves",
		},
		[12055] = {
			["name"] = "Shadoweave Robe",
		},
		[12056] = {
			["name"] = "Red Mageweave Vest",
		},
		[12059] = {
			["name"] = "White Bandit Mask",
		},
		[12060] = {
			["name"] = "Red Mageweave Pants",
		},
		[12061] = {
			["name"] = "Orange Mageweave Shirt",
		},
		[12062] = {
			["name"] = "Stormcloth Pants",
		},
		[12063] = {
			["name"] = "Stormcloth Gloves",
		},
		[12064] = {
			["name"] = "Orange Martial Shirt",
		},
		[12065] = {
			["name"] = "Mageweave Bag",
		},
		[12066] = {
			["name"] = "Red Mageweave Gloves",
		},
		[12067] = {
			["name"] = "Dreamweave Gloves",
		},
		[12068] = {
			["name"] = "Stormcloth Vest",
		},
		[12069] = {
			["name"] = "Cindercloth Robe",
		},
		[12070] = {
			["name"] = "Dreamweave Vest",
		},
		[12071] = {
			["name"] = "Shadoweave Gloves",
		},
		[12072] = {
			["name"] = "Black Mageweave Headband",
		},
		[12073] = {
			["name"] = "Black Mageweave Boots",
		},
		[12074] = {
			["name"] = "Black Mageweave Shoulders",
		},
		[12075] = {
			["name"] = "Lavender Mageweave Shirt",
		},
		[12076] = {
			["name"] = "Shadoweave Shoulders",
		},
		[12077] = {
			["name"] = "Simple Black Dress",
		},
		[12078] = {
			["name"] = "Red Mageweave Shoulders",
		},
		[12079] = {
			["name"] = "Red Mageweave Bag",
		},
		[12080] = {
			["name"] = "Pink Mageweave Shirt",
		},
		[12081] = {
			["name"] = "Admiral's Hat",
		},
		[12082] = {
			["name"] = "Shadoweave Boots",
		},
		[12083] = {
			["name"] = "Stormcloth Headband",
		},
		[12084] = {
			["name"] = "Red Mageweave Headband",
		},
		[12085] = {
			["name"] = "Tuxedo Shirt",
		},
		[12086] = {
			["name"] = "Shadoweave Mask",
		},
		[12087] = {
			["name"] = "Stormcloth Shoulders",
		},
		[12088] = {
			["name"] = "Cindercloth Boots",
		},
		[12089] = {
			["name"] = "Tuxedo Pants",
		},
		[12090] = {
			["name"] = "Stormcloth Boots",
		},
		[12091] = {
			["name"] = "White Wedding Dress",
		},
		[12092] = {
			["name"] = "Dreamweave Circlet",
		},
		[12093] = {
			["name"] = "Tuxedo Jacket",
		},
		[18401] = {
			["name"] = "Bolt of Runecloth",
		},
		[18402] = {
			["name"] = "Runecloth Belt",
		},
		[18403] = {
			["name"] = "Frostweave Tunic",
		},
		[18404] = {
			["name"] = "Frostweave Robe",
		},
		[18405] = {
			["name"] = "Runecloth Bag",
		},
		[18406] = {
			["name"] = "Runecloth Robe",
		},
		[18407] = {
			["name"] = "Runecloth Tunic",
		},
		[18408] = {
			["name"] = "Cindercloth Vest",
		},
		[18409] = {
			["name"] = "Runecloth Cloak",
		},
		[18410] = {
			["name"] = "Ghostweave Belt",
		},
		[18411] = {
			["name"] = "Frostweave Gloves",
		},
		[18412] = {
			["name"] = "Cindercloth Gloves",
		},
		[18413] = {
			["name"] = "Ghostweave Gloves",
		},
		[18414] = {
			["name"] = "Brightcloth Robe",
		},
		[18415] = {
			["name"] = "Brightcloth Gloves",
		},
		[18416] = {
			["name"] = "Ghostweave Vest",
		},
		[18417] = {
			["name"] = "Runecloth Gloves",
		},
		[18418] = {
			["name"] = "Cindercloth Cloak",
		},
		[18419] = {
			["name"] = "Felcloth Pants",
		},
		[18420] = {
			["name"] = "Brightcloth Cloak",
		},
		[18421] = {
			["name"] = "Wizardweave Leggings",
		},
		[18422] = {
			["name"] = "Cloak of Fire",
		},
		[18423] = {
			["name"] = "Runecloth Boots",
		},
		[18424] = {
			["name"] = "Frostweave Pants",
		},
		[18434] = {
			["name"] = "Cindercloth Pants",
		},
		[18436] = {
			["name"] = "Robe of Winter Night",
		},
		[18437] = {
			["name"] = "Felcloth Boots",
		},
		[18438] = {
			["name"] = "Runecloth Pants",
		},
		[18439] = {
			["name"] = "Brightcloth Pants",
		},
		[18440] = {
			["name"] = "Mooncloth Leggings",
		},
		[18441] = {
			["name"] = "Ghostweave Pants",
		},
		[18442] = {
			["name"] = "Felcloth Hood",
		},
		[18444] = {
			["name"] = "Runecloth Headband",
		},
		[18445] = {
			["name"] = "Mooncloth Bag",
		},
		[18446] = {
			["name"] = "Wizardweave Robe",
		},
		[18447] = {
			["name"] = "Mooncloth Vest",
		},
		[18448] = {
			["name"] = "Mooncloth Shoulders",
		},
		[18449] = {
			["name"] = "Runecloth Shoulders",
		},
		[18450] = {
			["name"] = "Wizardweave Turban",
		},
		[18451] = {
			["name"] = "Felcloth Robe",
		},
		[18452] = {
			["name"] = "Mooncloth Circlet",
		},
		[18453] = {
			["name"] = "Felcloth Shoulders",
		},
		[18454] = {
			["name"] = "Gloves of Spell Mastery",
		},
		[18455] = {
			["name"] = "Bottomless Bag",
		},
		[18456] = {
			["name"] = "Truefaith Vestments",
		},
		[18457] = {
			["name"] = "Robe of the Archmage",
		},
		[18458] = {
			["name"] = "Robe of the Void",
		},
		[18560] = {
			["name"] = "Mooncloth",
		},
		[19435] = {
			["name"] = "Mooncloth Boots",
		},
		[20848] = {
			["name"] = "Flarecore Mantle",
		},
		[20849] = {
			["name"] = "Flarecore Gloves",
		},
		[21945] = {
			["name"] = "Green Holiday Shirt",
		},
		[22759] = {
			["name"] = "Flarecore Wraps",
		},
		[22813] = {
			["name"] = "Gordok Ogre Suit",
		},
		[22866] = {
			["name"] = "Belt of the Archmage",
		},
		[22867] = {
			["name"] = "Felcloth Gloves",
		},
		[22868] = {
			["name"] = "Inferno Gloves",
		},
		[22869] = {
			["name"] = "Mooncloth Gloves",
		},
		[22870] = {
			["name"] = "Cloak of Warding",
		},
		[22902] = {
			["name"] = "Mooncloth Robe",
		},
		[23662] = {
			["name"] = "Wisdom of the Timbermaw",
		},
		[23663] = {
			["name"] = "Mantle of the Timbermaw",
		},
		[23664] = {
			["name"] = "Argent Boots",
		},
		[23665] = {
			["name"] = "Argent Shoulders",
		},
		[23666] = {
			["name"] = "Flarecore Robe",
		},
		[23667] = {
			["name"] = "Flarecore Leggings",
		},
		[24091] = {
			["name"] = "Bloodvine Vest",
		},
		[24092] = {
			["name"] = "Bloodvine Leggings",
		},
		[24093] = {
			["name"] = "Bloodvine Boots",
		},
		[24901] = {
			["name"] = "Runed Stygian Leggings",
		},
		[24902] = {
			["name"] = "Runed Stygian Belt",
		},
		[24903] = {
			["name"] = "Runed Stygian Boots",
		},
		[26085] = {
			["name"] = "Soul Pouch",
		},
		[26086] = {
			["name"] = "Felcloth Bag",
		},
		[26087] = {
			["name"] = "Core Felcloth Bag",
		},
		[26403] = {
			["name"] = "Festive Red Dress",
		},
		[26407] = {
			["name"] = "Festive Red Pant Suit",
		},
		[27658] = {
			["name"] = "Enchanted Mageweave Pouch",
		},
		[27659] = {
			["name"] = "Enchanted Runecloth Bag",
		},
		[27660] = {
			["name"] = "Big Bag of Enchantment",
		},
		[27724] = {
			["name"] = "Cenarion Herb Bag",
		},
		[27725] = {
			["name"] = "Satchel of Cenarius",
		},
		[28205] = {
			["name"] = "Glacial Gloves",
		},
		[28207] = {
			["name"] = "Glacial Vest",
		},
		[28208] = {
			["name"] = "Glacial Cloak",
		},
		[28209] = {
			["name"] = "Glacial Wrists",
		},
		[28210] = {
			["name"] = "Gaea's Embrace",
		},
		[28480] = {
			["name"] = "Sylvan Vest",
		},
		[28481] = {
			["name"] = "Sylvan Crown",
		},
		[28482] = {
			["name"] = "Sylvan Shoulders",
		},
		[428424] = {
			["name"] = "Phoenix Bindings",
		},
		[429351] = {
			["name"] = "Extraplanar Spidersilk Boots",
		},
		[435610] = {
			["name"] = "Gneuro-Linked Arcano-Filament Monocle",
		},
		[435827] = {
			["name"] = "Hyperconductive Arcano-Filament",
		},
		[435841] = {
			["name"] = "Invoker's Cord",
		},
		[435848] = {
			["name"] = "Invoker's Mantle",
		},
		[439085] = {
			["name"] = "Crimson Silk Robe",
		},
		[439086] = {
			["name"] = "Black Mageweave Vest",
		},
		[439088] = {
			["name"] = "Black Mageweave Leggings",
		},
		[439091] = {
			["name"] = "Earthen Silk Belt",
		},
		[439093] = {
			["name"] = "Crimson Silk Shoulders",
		},
		[439094] = {
			["name"] = "Long Silken Cloak",
		},
		[439097] = {
			["name"] = "Boots of the Enchanter",
		},
		[439098] = {
			["name"] = "Crimson Silk Belt",
		},
		[439100] = {
			["name"] = "Earthen Vest",
		},
		[439102] = {
			["name"] = "Enchanter's Cowl",
		},
		[446193] = {
			["name"] = "Fractured Mind Pauldrons",
		},
		[446194] = {
			["name"] = "Mantle of Insanity",
		},
		[446195] = {
			["name"] = "Shoulderpads of the Deranged",
		},
		[461692] = {
			["name"] = "Synthetic Gordok Ogre Suit",
		},
		[461708] = {
			["name"] = "Incandescent Mooncloth Robe",
		},
		[461727] = {
			["name"] = "Leather-Reinforced Runecloth Bag",
		},
		[461747] = {
			["name"] = "Incandescent Mooncloth Vest",
		},
		[461750] = {
			["name"] = "Incandescent Mooncloth Circlet",
		},
		[461752] = {
			["name"] = "Incandescent Mooncloth Leggings",
		},
		[462282] = {
			["name"] = "Embroidered Belt of the Archmage",
		},
		[463972] = {
			["name"] = "Bottomless Bag",
		},
		[1213527] = {
			["name"] = "Vampiric Cowl",
		},
		[1213530] = {
			["name"] = "Vampiric Shawl",
		},
		[1213532] = {
			["name"] = "Vampiric Robe",
		},
		[1213534] = {
			["name"] = "Qiraji Silk Scarf",
		},
		[1213536] = {
			["name"] = "Qiraji Silk Cape",
		},
		[1213538] = {
			["name"] = "Qiraji Silk Cloak",
		},
		[1213540] = {
			["name"] = "Qiraji Silk Drape",
		},
		[1213740] = {
			["name"] = "Sylvan Shoulders",
		},
		[1213742] = {
			["name"] = "Sylvan Crown",
		},
		[1213744] = {
			["name"] = "Sylvan Vest",
		},
		[1214173] = {
			["name"] = "Bolt of Qiraji Silk",
		},
		[1214306] = {
			["name"] = "Dreamscale Bracers",
		},
		[1214307] = {
			["name"] = "Dreamscale Mitts",
		},
		[1223760] = {
			["name"] = "Glacial Vest",
		},
		[1223762] = {
			["name"] = "Glacial Cloak",
		},
		[1223764] = {
			["name"] = "Glacial Gloves",
		},
		[1223766] = {
			["name"] = "Glacial Wrists",
		},
		[1223768] = {
			["name"] = "Frosty Vest",
		},
		[1223770] = {
			["name"] = "Frosty Gloves",
		},
		[1223772] = {
			["name"] = "Frosty Wrists",
		},
		[1224607] = {
			["name"] = "Scarlet Augur's Hood",
		},
		[1224608] = {
			["name"] = "Scarlet Augur's Mantle",
		},
		[1224609] = {
			["name"] = "Scarlet Augur's Vestaments",
		},
		[1224610] = {
			["name"] = "Scarlet Augur's Cuffs",
		},
		[1224611] = {
			["name"] = "Scarlet Augur's Mitts",
		},
		[1224612] = {
			["name"] = "Scarlet Augur's Strap",
		},
		[1224613] = {
			["name"] = "Scarlet Augur's Leggings",
		},
		[1224614] = {
			["name"] = "Scarlet Augur's Soles",
		},
		[1227723] = {
			["name"] = "Crusader's Knapsack",
		},
		[1227724] = {
			["name"] = "Crimson Dawnwoven Bag",
		},
	})

end
