local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB recipe acquisition methods - WoW Vanilla (locale-independent)
-- Auto-generated by tools/build-acquire-methods.py from wago.tools DB2. Do not hand-edit.
--
-- SkillLineAbility.AcquireMethod. 1 = granted automatically when the
-- character learns the profession, which is why nothing in the world
-- teaches these and no source database lists them.
--
-- Value 0 is OMITTED, not zero: it is the default and the large majority.
-- build 1.15.8.67156 - 1564 recipes, distribution {'0': 1536, '1': 28}

local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib then return end

lib:LoadAcquireMethods({
[2149]=1,
[2152]=1,
[2329]=1,
[2330]=1,
[2387]=1,
[2538]=1,
[2540]=1,
[2657]=1,
[2660]=1,
[2663]=1,
[2881]=1,
[2963]=1,
[3115]=1,
[3275]=1,
[3915]=1,
[3918]=1,
[3919]=1,
[3920]=1,
[7126]=1,
[7183]=1,
[7418]=1,
[7421]=1,
[7428]=1,
[8604]=1,
[9058]=1,
[9059]=1,
[12044]=1,
[12260]=1,
})

end
