local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB core data — WoW Vanilla, Enchanting (locale-independent)
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 199 recipes

local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadCore(333, {
		[7418] = {
			["difficulty"] = {
				70,
				80,
				90,
				110,
			},
			["enchantId"] = 41,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[10940] = 1,
			},
			["requiredSkill"] = 70,
			["stats"] = {
				["ITEM_MOD_HEALTH"] = 5,
			},
			["teaches"] = 7418,
		},
		[7420] = {
			["difficulty"] = {
				1,
				35,
				70,
				110,
			},
			["enchantId"] = 41,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[10940] = 1,
			},
			["stats"] = {
				["ITEM_MOD_HEALTH"] = 5,
			},
			["teaches"] = 7420,
		},
		[7421] = {
			["craftedItemId"] = 6218,
			["difficulty"] = {
				1,
				3,
				5,
				10,
			},
			["reagents"] = {
				[6217] = 1,
				[10938] = 1,
				[10940] = 1,
			},
			["requiredSkill"] = 1,
			["teaches"] = 7421,
		},
		[7426] = {
			["difficulty"] = {
				1,
				45,
				90,
				130,
			},
			["enchantId"] = 44,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[10938] = 1,
				[10940] = 2,
			},
			["teaches"] = 7426,
		},
		[7428] = {
			["difficulty"] = {
				1,
				40,
				80,
				120,
			},
			["enchantId"] = 924,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[10938] = 1,
				[10940] = 1,
			},
			["stats"] = {
				["DEFENSE"] = 1,
			},
			["teaches"] = 7428,
		},
		[7443] = {
			["difficulty"] = {
				20,
				80,
				100,
				120,
			},
			["enchantId"] = 24,
			["enchantSlot"] = "CHEST",
			["itemId"] = 6342,
			["reagents"] = {
				[10938] = 1,
			},
			["requiredSkill"] = 20,
			["stats"] = {
				["ITEM_MOD_MANA"] = 5,
			},
			["teaches"] = 7443,
		},
		[7454] = {
			["difficulty"] = {
				1,
				48,
				95,
				135,
			},
			["enchantId"] = 65,
			["enchantSlot"] = "BACK",
			["reagents"] = {
				[10938] = 2,
				[10940] = 1,
			},
			["stats"] = {
				["RESISTANCE1_NAME"] = 1,
				["RESISTANCE2_NAME"] = 1,
				["RESISTANCE3_NAME"] = 1,
				["RESISTANCE4_NAME"] = 1,
				["RESISTANCE5_NAME"] = 1,
				["RESISTANCE6_NAME"] = 1,
			},
			["teaches"] = 7454,
		},
		[7457] = {
			["difficulty"] = {
				1,
				50,
				100,
				140,
			},
			["enchantId"] = 66,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[10940] = 3,
			},
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 1,
			},
			["teaches"] = 7457,
		},
		[7745] = {
			["difficulty"] = {
				1,
				65,
				130,
				170,
			},
			["enchantId"] = 241,
			["enchantSlot"] = "WEAPON2H",
			["reagents"] = {
				[10940] = 4,
				[10978] = 1,
			},
			["teaches"] = 7745,
		},
		[7748] = {
			["difficulty"] = {
				1,
				53,
				105,
				145,
			},
			["enchantId"] = 242,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[10938] = 2,
				[10940] = 2,
			},
			["stats"] = {
				["ITEM_MOD_HEALTH"] = 15,
			},
			["teaches"] = 7748,
		},
		[7766] = {
			["difficulty"] = {
				60,
				105,
				125,
				145,
			},
			["enchantId"] = 243,
			["enchantSlot"] = "WRIST",
			["itemId"] = 6344,
			["reagents"] = {
				[10938] = 2,
			},
			["requiredSkill"] = 60,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 1,
			},
			["teaches"] = 7766,
		},
		[7771] = {
			["difficulty"] = {
				90,
				110,
				130,
				150,
			},
			["enchantId"] = 783,
			["enchantSlot"] = "BACK",
			["itemId"] = 6345,
			["reagents"] = {
				[10939] = 1,
				[10940] = 3,
			},
			["requiredSkill"] = 90,
			["stats"] = {
				["RESISTANCE0_NAME"] = 10,
			},
			["teaches"] = 7771,
		},
		[7776] = {
			["difficulty"] = {
				80,
				115,
				135,
				155,
			},
			["enchantId"] = 246,
			["enchantSlot"] = "CHEST",
			["itemId"] = 6346,
			["reagents"] = {
				[10938] = 1,
				[10939] = 1,
			},
			["requiredSkill"] = 80,
			["stats"] = {
				["ITEM_MOD_MANA"] = 20,
			},
			["teaches"] = 7776,
		},
		[7779] = {
			["difficulty"] = {
				1,
				58,
				115,
				155,
			},
			["enchantId"] = 247,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[10939] = 1,
				[10940] = 2,
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 1,
			},
			["teaches"] = 7779,
		},
		[7782] = {
			["difficulty"] = {
				80,
				115,
				135,
				155,
			},
			["enchantId"] = 248,
			["enchantSlot"] = "WRIST",
			["itemId"] = 6347,
			["reagents"] = {
				[10940] = 5,
			},
			["requiredSkill"] = 80,
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 1,
			},
			["teaches"] = 7782,
		},
		[7786] = {
			["difficulty"] = {
				90,
				120,
				140,
				160,
			},
			["enchantId"] = 249,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 6348,
			["reagents"] = {
				[10939] = 2,
				[10940] = 4,
			},
			["requiredSkill"] = 90,
			["teaches"] = 7786,
		},
		[7788] = {
			["difficulty"] = {
				1,
				60,
				120,
				160,
			},
			["enchantId"] = 250,
			["enchantSlot"] = "WEAPON1H",
			["reagents"] = {
				[10939] = 1,
				[10940] = 2,
				[10978] = 1,
			},
			["teaches"] = 7788,
		},
		[7793] = {
			["difficulty"] = {
				100,
				130,
				150,
				170,
			},
			["enchantId"] = 723,
			["enchantSlot"] = "WEAPON2H",
			["itemId"] = 6349,
			["reagents"] = {
				[10939] = 3,
			},
			["requiredSkill"] = 100,
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 3,
			},
			["teaches"] = 7793,
		},
		[7795] = {
			["craftedItemId"] = 6339,
			["difficulty"] = {
				1,
				65,
				130,
				170,
			},
			["reagents"] = {
				[1210] = 1,
				[6338] = 1,
				[10939] = 3,
				[10940] = 6,
			},
			["teaches"] = 7795,
		},
		[7857] = {
			["difficulty"] = {
				1,
				73,
				145,
				185,
			},
			["enchantId"] = 254,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[10940] = 4,
				[10998] = 1,
			},
			["stats"] = {
				["ITEM_MOD_HEALTH"] = 25,
			},
			["teaches"] = 7857,
		},
		[7859] = {
			["difficulty"] = {
				120,
				145,
				165,
				185,
			},
			["enchantId"] = 255,
			["enchantSlot"] = "WRIST",
			["itemId"] = 6375,
			["reagents"] = {
				[10998] = 2,
			},
			["requiredSkill"] = 120,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 3,
			},
			["teaches"] = 7859,
		},
		[7861] = {
			["difficulty"] = {
				1,
				75,
				150,
				190,
			},
			["enchantId"] = 256,
			["enchantSlot"] = "BACK",
			["reagents"] = {
				[6371] = 1,
				[10998] = 1,
			},
			["stats"] = {
				["RESISTANCE2_NAME"] = 5,
			},
			["teaches"] = 7861,
		},
		[7863] = {
			["difficulty"] = {
				125,
				150,
				170,
				190,
			},
			["enchantId"] = 66,
			["enchantSlot"] = "FEET",
			["itemId"] = 6376,
			["reagents"] = {
				[10940] = 8,
			},
			["requiredSkill"] = 125,
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 1,
			},
			["teaches"] = 7863,
		},
		[7867] = {
			["difficulty"] = {
				125,
				150,
				170,
				190,
			},
			["enchantId"] = 247,
			["enchantSlot"] = "FEET",
			["itemId"] = 6377,
			["reagents"] = {
				[10940] = 6,
				[10998] = 2,
			},
			["requiredSkill"] = 125,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 1,
			},
			["teaches"] = 7867,
		},
		[13378] = {
			["difficulty"] = {
				1,
				65,
				130,
				170,
			},
			["enchantId"] = 66,
			["reagents"] = {
				[10940] = 2,
				[10998] = 1,
			},
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 1,
			},
			["teaches"] = 13378,
		},
		[13380] = {
			["difficulty"] = {
				110,
				135,
				155,
				175,
			},
			["enchantId"] = 255,
			["enchantSlot"] = "WEAPON2H",
			["itemId"] = 11038,
			["reagents"] = {
				[10940] = 6,
				[10998] = 1,
			},
			["requiredSkill"] = 110,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 3,
			},
			["teaches"] = 13380,
		},
		[13419] = {
			["difficulty"] = {
				110,
				135,
				155,
				175,
			},
			["enchantId"] = 247,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 11039,
			["reagents"] = {
				[10998] = 1,
			},
			["requiredSkill"] = 110,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 1,
			},
			["teaches"] = 13419,
		},
		[13421] = {
			["difficulty"] = {
				1,
				70,
				140,
				180,
			},
			["enchantId"] = 744,
			["enchantSlot"] = "BACK",
			["reagents"] = {
				[10940] = 6,
				[10978] = 1,
			},
			["stats"] = {
				["RESISTANCE0_NAME"] = 20,
			},
			["teaches"] = 13421,
		},
		[13464] = {
			["difficulty"] = {
				115,
				140,
				160,
				180,
			},
			["enchantId"] = 848,
			["enchantSlot"] = "SHIELD",
			["itemId"] = 11081,
			["reagents"] = {
				[10940] = 1,
				[10978] = 1,
				[10998] = 1,
			},
			["requiredSkill"] = 115,
			["stats"] = {
				["RESISTANCE0_NAME"] = 30,
			},
			["teaches"] = 13464,
		},
		[13485] = {
			["difficulty"] = {
				1,
				78,
				155,
				195,
			},
			["enchantId"] = 255,
			["enchantSlot"] = "SHIELD",
			["reagents"] = {
				[10940] = 4,
				[10998] = 2,
			},
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 3,
			},
			["teaches"] = 13485,
		},
		[13501] = {
			["difficulty"] = {
				1,
				78,
				155,
				195,
			},
			["enchantId"] = 724,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[11083] = 2,
			},
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 3,
			},
			["teaches"] = 13501,
		},
		[13503] = {
			["difficulty"] = {
				1,
				83,
				165,
				205,
			},
			["enchantId"] = 241,
			["enchantSlot"] = "WEAPON1H",
			["reagents"] = {
				[11083] = 2,
				[11084] = 1,
			},
			["teaches"] = 13503,
		},
		[13522] = {
			["difficulty"] = {
				135,
				160,
				180,
				200,
			},
			["enchantId"] = 804,
			["enchantSlot"] = "BACK",
			["itemId"] = 11098,
			["reagents"] = {
				[6048] = 1,
				[11082] = 1,
			},
			["requiredSkill"] = 135,
			["stats"] = {
				["RESISTANCE5_NAME"] = 10,
			},
			["teaches"] = 13522,
		},
		[13529] = {
			["difficulty"] = {
				1,
				85,
				170,
				210,
			},
			["enchantId"] = 943,
			["enchantSlot"] = "WEAPON2H",
			["reagents"] = {
				[11083] = 3,
				[11084] = 1,
			},
			["teaches"] = 13529,
		},
		[13536] = {
			["difficulty"] = {
				140,
				165,
				185,
				205,
			},
			["enchantId"] = 823,
			["enchantSlot"] = "WRIST",
			["itemId"] = 11101,
			["reagents"] = {
				[11083] = 2,
			},
			["requiredSkill"] = 140,
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 3,
			},
			["teaches"] = 13536,
		},
		[13538] = {
			["difficulty"] = {
				1,
				83,
				165,
				205,
			},
			["enchantId"] = 63,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[10940] = 2,
				[11082] = 1,
				[11084] = 1,
			},
			["teaches"] = 13538,
		},
		[13607] = {
			["difficulty"] = {
				1,
				85,
				170,
				210,
			},
			["enchantId"] = 843,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[10998] = 2,
				[11082] = 1,
			},
			["stats"] = {
				["ITEM_MOD_MANA"] = 30,
			},
			["teaches"] = 13607,
		},
		[13612] = {
			["difficulty"] = {
				145,
				170,
				190,
				210,
			},
			["enchantId"] = 844,
			["enchantSlot"] = "HANDS",
			["itemId"] = 11150,
			["reagents"] = {
				[2772] = 3,
				[11083] = 1,
			},
			["requiredSkill"] = 145,
			["teaches"] = 13612,
		},
		[13617] = {
			["difficulty"] = {
				145,
				170,
				190,
				210,
			},
			["enchantId"] = 845,
			["enchantSlot"] = "HANDS",
			["itemId"] = 11151,
			["reagents"] = {
				[3356] = 3,
				[11083] = 1,
			},
			["requiredSkill"] = 145,
			["teaches"] = 13617,
		},
		[13620] = {
			["difficulty"] = {
				145,
				170,
				190,
				210,
			},
			["enchantId"] = 846,
			["enchantSlot"] = "HANDS",
			["itemId"] = 11152,
			["reagents"] = {
				[6370] = 3,
				[11083] = 1,
			},
			["requiredSkill"] = 145,
			["teaches"] = 13620,
		},
		[13622] = {
			["difficulty"] = {
				1,
				88,
				175,
				215,
			},
			["enchantId"] = 723,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[11082] = 2,
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 3,
			},
			["teaches"] = 13622,
		},
		[13626] = {
			["difficulty"] = {
				1,
				88,
				175,
				215,
			},
			["enchantId"] = 847,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[11082] = 1,
				[11083] = 1,
				[11084] = 1,
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 1,
				["ITEM_MOD_INTELLECT_SHORT"] = 1,
				["ITEM_MOD_SPIRIT_SHORT"] = 1,
				["ITEM_MOD_STAMINA_SHORT"] = 1,
				["ITEM_MOD_STRENGTH_SHORT"] = 1,
			},
			["teaches"] = 13626,
		},
		[13628] = {
			["craftedItemId"] = 11130,
			["difficulty"] = {
				1,
				88,
				175,
				215,
			},
			["reagents"] = {
				[5500] = 1,
				[11082] = 2,
				[11083] = 2,
				[11128] = 1,
			},
			["teaches"] = 13628,
		},
		[13631] = {
			["difficulty"] = {
				1,
				88,
				175,
				215,
			},
			["enchantId"] = 724,
			["reagents"] = {
				[11083] = 1,
				[11134] = 1,
			},
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 3,
			},
			["teaches"] = 13631,
		},
		[13635] = {
			["difficulty"] = {
				1,
				88,
				175,
				215,
			},
			["enchantId"] = 848,
			["enchantSlot"] = "BACK",
			["reagents"] = {
				[11083] = 3,
				[11138] = 1,
			},
			["stats"] = {
				["RESISTANCE0_NAME"] = 30,
			},
			["teaches"] = 13635,
		},
		[13637] = {
			["difficulty"] = {
				1,
				90,
				180,
				220,
			},
			["enchantId"] = 849,
			["enchantSlot"] = "FEET",
			["reagents"] = {
				[11083] = 1,
				[11134] = 1,
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 3,
			},
			["teaches"] = 13637,
		},
		[13640] = {
			["difficulty"] = {
				1,
				90,
				180,
				220,
			},
			["enchantId"] = 850,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[11083] = 3,
			},
			["stats"] = {
				["ITEM_MOD_HEALTH"] = 35,
			},
			["teaches"] = 13640,
		},
		[13642] = {
			["difficulty"] = {
				1,
				93,
				185,
				225,
			},
			["enchantId"] = 851,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[11134] = 1,
			},
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 5,
			},
			["teaches"] = 13642,
		},
		[13644] = {
			["difficulty"] = {
				1,
				95,
				190,
				230,
			},
			["enchantId"] = 724,
			["enchantSlot"] = "FEET",
			["reagents"] = {
				[11083] = 4,
			},
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 3,
			},
			["teaches"] = 13644,
		},
		[13646] = {
			["difficulty"] = {
				170,
				190,
				210,
				230,
			},
			["enchantId"] = 925,
			["enchantSlot"] = "WRIST",
			["itemId"] = 11163,
			["reagents"] = {
				[11083] = 2,
				[11134] = 1,
			},
			["requiredSkill"] = 170,
			["stats"] = {
				["DEFENSE"] = 2,
			},
			["teaches"] = 13646,
		},
		[13648] = {
			["difficulty"] = {
				1,
				95,
				190,
				230,
			},
			["enchantId"] = 852,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[11083] = 6,
			},
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 5,
			},
			["teaches"] = 13648,
		},
		[13653] = {
			["difficulty"] = {
				175,
				195,
				215,
				235,
			},
			["enchantId"] = 853,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 11164,
			["reagents"] = {
				[5637] = 2,
				[11134] = 1,
				[11138] = 1,
			},
			["requiredSkill"] = 175,
			["teaches"] = 13653,
		},
		[13655] = {
			["difficulty"] = {
				175,
				195,
				215,
				235,
			},
			["enchantId"] = 854,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 11165,
			["reagents"] = {
				[7067] = 1,
				[11134] = 1,
				[11138] = 1,
			},
			["requiredSkill"] = 175,
			["teaches"] = 13655,
		},
		[13657] = {
			["difficulty"] = {
				1,
				98,
				195,
				235,
			},
			["enchantId"] = 2463,
			["enchantSlot"] = "BACK",
			["reagents"] = {
				[7068] = 1,
				[11134] = 1,
			},
			["stats"] = {
				["RESISTANCE2_NAME"] = 7,
			},
			["teaches"] = 13657,
		},
		[13659] = {
			["difficulty"] = {
				1,
				100,
				200,
				240,
			},
			["enchantId"] = 851,
			["reagents"] = {
				[11135] = 1,
				[11137] = 1,
			},
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 5,
			},
			["teaches"] = 13659,
		},
		[13661] = {
			["difficulty"] = {
				1,
				100,
				200,
				240,
			},
			["enchantId"] = 856,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[11137] = 1,
			},
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 5,
			},
			["teaches"] = 13661,
		},
		[13663] = {
			["difficulty"] = {
				1,
				103,
				205,
				245,
			},
			["enchantId"] = 857,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[11135] = 1,
			},
			["stats"] = {
				["ITEM_MOD_MANA"] = 50,
			},
			["teaches"] = 13663,
		},
		[13687] = {
			["difficulty"] = {
				190,
				210,
				230,
				250,
			},
			["enchantId"] = 255,
			["enchantSlot"] = "FEET",
			["itemId"] = 11167,
			["reagents"] = {
				[11134] = 2,
				[11135] = 1,
			},
			["requiredSkill"] = 190,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 3,
			},
			["teaches"] = 13687,
		},
		[13689] = {
			["difficulty"] = {
				195,
				215,
				235,
				255,
			},
			["enchantId"] = 863,
			["itemId"] = 11168,
			["reagents"] = {
				[11135] = 2,
				[11137] = 2,
				[11139] = 1,
			},
			["requiredSkill"] = 195,
			["stats"] = {
				["BLOCK_PCT"] = 2,
			},
			["teaches"] = 13689,
		},
		[13693] = {
			["difficulty"] = {
				1,
				108,
				215,
				255,
			},
			["enchantId"] = 943,
			["enchantSlot"] = "WEAPON1H",
			["reagents"] = {
				[11135] = 2,
				[11139] = 1,
			},
			["teaches"] = 13693,
		},
		[13695] = {
			["difficulty"] = {
				1,
				110,
				220,
				260,
			},
			["enchantId"] = 1897,
			["enchantSlot"] = "WEAPON2H",
			["reagents"] = {
				[11137] = 4,
				[11139] = 1,
			},
			["teaches"] = 13695,
		},
		[13698] = {
			["difficulty"] = {
				200,
				220,
				240,
				260,
			},
			["enchantId"] = 865,
			["enchantSlot"] = "HANDS",
			["itemId"] = 11166,
			["reagents"] = {
				[7392] = 3,
				[11137] = 1,
			},
			["requiredSkill"] = 200,
			["teaches"] = 13698,
		},
		[13700] = {
			["difficulty"] = {
				1,
				110,
				220,
				260,
			},
			["enchantId"] = 866,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[11135] = 2,
				[11137] = 2,
				[11139] = 1,
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 2,
				["ITEM_MOD_INTELLECT_SHORT"] = 2,
				["ITEM_MOD_SPIRIT_SHORT"] = 2,
				["ITEM_MOD_STAMINA_SHORT"] = 2,
				["ITEM_MOD_STRENGTH_SHORT"] = 2,
			},
			["teaches"] = 13700,
		},
		[13702] = {
			["craftedItemId"] = 11145,
			["difficulty"] = {
				1,
				110,
				220,
				260,
			},
			["reagents"] = {
				[7971] = 1,
				[11135] = 2,
				[11137] = 2,
				[11144] = 1,
			},
			["teaches"] = 13702,
		},
		[13746] = {
			["difficulty"] = {
				1,
				113,
				225,
				265,
			},
			["enchantId"] = 884,
			["enchantSlot"] = "BACK",
			["reagents"] = {
				[11137] = 3,
			},
			["stats"] = {
				["RESISTANCE0_NAME"] = 50,
			},
			["teaches"] = 13746,
		},
		[13794] = {
			["difficulty"] = {
				1,
				113,
				225,
				265,
			},
			["enchantId"] = 903,
			["enchantSlot"] = "BACK",
			["reagents"] = {
				[11174] = 1,
			},
			["stats"] = {
				["RESISTANCE1_NAME"] = 3,
				["RESISTANCE2_NAME"] = 3,
				["RESISTANCE3_NAME"] = 3,
				["RESISTANCE4_NAME"] = 3,
				["RESISTANCE5_NAME"] = 3,
				["RESISTANCE6_NAME"] = 3,
			},
			["teaches"] = 13794,
		},
		[13815] = {
			["difficulty"] = {
				1,
				115,
				230,
				270,
			},
			["enchantId"] = 904,
			["enchantSlot"] = "HANDS",
			["reagents"] = {
				[11137] = 1,
				[11174] = 1,
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 5,
			},
			["teaches"] = 13815,
		},
		[13817] = {
			["difficulty"] = {
				210,
				230,
				250,
				270,
			},
			["enchantId"] = 852,
			["itemId"] = 11202,
			["reagents"] = {
				[11137] = 5,
			},
			["requiredSkill"] = 210,
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 5,
			},
			["teaches"] = 13817,
		},
		[13822] = {
			["difficulty"] = {
				1,
				115,
				230,
				270,
			},
			["enchantId"] = 905,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[11174] = 2,
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 5,
			},
			["teaches"] = 13822,
		},
		[13836] = {
			["difficulty"] = {
				1,
				118,
				235,
				275,
			},
			["enchantId"] = 852,
			["enchantSlot"] = "FEET",
			["reagents"] = {
				[11137] = 5,
			},
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 5,
			},
			["teaches"] = 13836,
		},
		[13841] = {
			["difficulty"] = {
				215,
				235,
				255,
				275,
			},
			["enchantId"] = 906,
			["enchantSlot"] = "HANDS",
			["itemId"] = 11203,
			["reagents"] = {
				[6037] = 3,
				[11137] = 3,
			},
			["requiredSkill"] = 215,
			["teaches"] = 13841,
		},
		[13846] = {
			["difficulty"] = {
				220,
				240,
				260,
				280,
			},
			["enchantId"] = 907,
			["enchantSlot"] = "WRIST",
			["itemId"] = 11204,
			["reagents"] = {
				[11137] = 1,
				[11174] = 3,
			},
			["requiredSkill"] = 220,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 7,
			},
			["teaches"] = 13846,
		},
		[13858] = {
			["difficulty"] = {
				1,
				120,
				240,
				280,
			},
			["enchantId"] = 908,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[11137] = 6,
			},
			["stats"] = {
				["ITEM_MOD_HEALTH"] = 50,
			},
			["teaches"] = 13858,
		},
		[13868] = {
			["difficulty"] = {
				225,
				245,
				265,
				285,
			},
			["enchantId"] = 909,
			["enchantSlot"] = "HANDS",
			["itemId"] = 11205,
			["reagents"] = {
				[8838] = 3,
				[11137] = 3,
			},
			["requiredSkill"] = 225,
			["teaches"] = 13868,
		},
		[13882] = {
			["difficulty"] = {
				225,
				245,
				265,
				285,
			},
			["enchantId"] = 849,
			["enchantSlot"] = "BACK",
			["itemId"] = 11206,
			["reagents"] = {
				[11174] = 2,
			},
			["requiredSkill"] = 225,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 3,
			},
			["teaches"] = 13882,
		},
		[13887] = {
			["difficulty"] = {
				1,
				123,
				245,
				285,
			},
			["enchantId"] = 856,
			["enchantSlot"] = "HANDS",
			["reagents"] = {
				[11137] = 3,
				[11174] = 2,
			},
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 5,
			},
			["teaches"] = 13887,
		},
		[13890] = {
			["difficulty"] = {
				1,
				123,
				245,
				285,
			},
			["enchantId"] = 911,
			["enchantSlot"] = "FEET",
			["reagents"] = {
				[7909] = 1,
				[11174] = 1,
				[11177] = 1,
			},
			["teaches"] = 13890,
		},
		[13898] = {
			["difficulty"] = {
				265,
				285,
				305,
				325,
			},
			["enchantId"] = 803,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 11207,
			["reagents"] = {
				[7078] = 1,
				[11177] = 4,
			},
			["requiredSkill"] = 265,
			["teaches"] = 13898,
		},
		[13905] = {
			["difficulty"] = {
				1,
				125,
				250,
				290,
			},
			["enchantId"] = 907,
			["reagents"] = {
				[11175] = 1,
				[11176] = 2,
			},
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 7,
			},
			["teaches"] = 13905,
		},
		[13915] = {
			["difficulty"] = {
				230,
				250,
				270,
				290,
			},
			["enchantId"] = 912,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 11208,
			["reagents"] = {
				[9224] = 1,
				[11176] = 2,
				[11177] = 1,
			},
			["requiredSkill"] = 230,
			["teaches"] = 13915,
		},
		[13917] = {
			["difficulty"] = {
				1,
				125,
				250,
				290,
			},
			["enchantId"] = 913,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[11174] = 2,
				[11175] = 1,
			},
			["stats"] = {
				["ITEM_MOD_MANA"] = 65,
			},
			["teaches"] = 13917,
		},
		[13931] = {
			["difficulty"] = {
				235,
				255,
				275,
				295,
			},
			["enchantId"] = 923,
			["enchantSlot"] = "WRIST",
			["itemId"] = 11223,
			["reagents"] = {
				[11175] = 1,
				[11176] = 2,
			},
			["requiredSkill"] = 235,
			["stats"] = {
				["DEFENSE"] = 3,
			},
			["teaches"] = 13931,
		},
		[13933] = {
			["difficulty"] = {
				235,
				255,
				275,
				295,
			},
			["enchantId"] = 926,
			["itemId"] = 11224,
			["reagents"] = {
				[3829] = 1,
				[11178] = 1,
			},
			["requiredSkill"] = 235,
			["stats"] = {
				["RESISTANCE4_NAME"] = 8,
			},
			["teaches"] = 13933,
		},
		[13935] = {
			["difficulty"] = {
				1,
				128,
				255,
				295,
			},
			["enchantId"] = 904,
			["enchantSlot"] = "FEET",
			["reagents"] = {
				[11175] = 2,
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 5,
			},
			["teaches"] = 13935,
		},
		[13937] = {
			["difficulty"] = {
				1,
				130,
				260,
				300,
			},
			["enchantId"] = 963,
			["enchantSlot"] = "WEAPON2H",
			["reagents"] = {
				[11176] = 2,
				[11178] = 2,
			},
			["teaches"] = 13937,
		},
		[13939] = {
			["difficulty"] = {
				1,
				130,
				260,
				300,
			},
			["enchantId"] = 927,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[11175] = 1,
				[11176] = 2,
			},
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 7,
			},
			["teaches"] = 13939,
		},
		[13941] = {
			["difficulty"] = {
				1,
				133,
				265,
				305,
			},
			["enchantId"] = 928,
			["enchantSlot"] = "CHEST",
			["reagents"] = {
				[11175] = 2,
				[11176] = 3,
				[11178] = 1,
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 3,
				["ITEM_MOD_INTELLECT_SHORT"] = 3,
				["ITEM_MOD_SPIRIT_SHORT"] = 3,
				["ITEM_MOD_STAMINA_SHORT"] = 3,
				["ITEM_MOD_STRENGTH_SHORT"] = 3,
			},
			["teaches"] = 13941,
		},
		[13943] = {
			["difficulty"] = {
				1,
				133,
				265,
				305,
			},
			["enchantId"] = 805,
			["enchantSlot"] = "WEAPON1H",
			["reagents"] = {
				[11175] = 2,
				[11178] = 2,
			},
			["teaches"] = 13943,
		},
		[13945] = {
			["difficulty"] = {
				245,
				265,
				285,
				305,
			},
			["enchantId"] = 929,
			["enchantSlot"] = "WRIST",
			["itemId"] = 11225,
			["reagents"] = {
				[11176] = 5,
			},
			["requiredSkill"] = 245,
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 7,
			},
			["teaches"] = 13945,
		},
		[13947] = {
			["difficulty"] = {
				250,
				270,
				290,
				310,
			},
			["enchantId"] = 930,
			["enchantSlot"] = "HANDS",
			["itemId"] = 11226,
			["reagents"] = {
				[11176] = 3,
				[11178] = 2,
			},
			["requiredSkill"] = 250,
			["teaches"] = 13947,
		},
		[13948] = {
			["difficulty"] = {
				1,
				135,
				270,
				310,
			},
			["enchantId"] = 931,
			["enchantSlot"] = "HANDS",
			["reagents"] = {
				[8153] = 2,
				[11178] = 2,
			},
			["stats"] = {
				["RANGED_HASTE_PCT"] = 1,
			},
			["teaches"] = 13948,
		},
		[14293] = {
			["craftedItemId"] = 11287,
			["difficulty"] = {
				1,
				38,
				75,
				115,
			},
			["reagents"] = {
				[4470] = 1,
				[10938] = 1,
			},
			["teaches"] = 14293,
		},
		[14807] = {
			["craftedItemId"] = 11288,
			["difficulty"] = {
				1,
				55,
				110,
				150,
			},
			["reagents"] = {
				[4470] = 1,
				[10939] = 1,
			},
			["teaches"] = 14807,
		},
		[14809] = {
			["craftedItemId"] = 11289,
			["difficulty"] = {
				1,
				88,
				175,
				215,
			},
			["reagents"] = {
				[11083] = 1,
				[11134] = 1,
				[11291] = 1,
			},
			["teaches"] = 14809,
		},
		[14810] = {
			["craftedItemId"] = 11290,
			["difficulty"] = {
				1,
				98,
				195,
				235,
			},
			["reagents"] = {
				[11135] = 1,
				[11137] = 1,
				[11291] = 1,
			},
			["teaches"] = 14810,
		},
		[15596] = {
			["craftedItemId"] = 11811,
			["difficulty"] = {
				265,
				285,
				305,
				325,
			},
			["itemId"] = 11813,
			["reagents"] = {
				[7078] = 1,
				[11382] = 1,
				[14343] = 3,
			},
			["requiredSkill"] = 265,
			["teaches"] = 15596,
		},
		[17180] = {
			["craftedItemId"] = 12655,
			["difficulty"] = {
				1,
				125,
				250,
				260,
			},
			["reagents"] = {
				[11176] = 3,
				[12359] = 1,
			},
			["teaches"] = 17180,
		},
		[17181] = {
			["craftedItemId"] = 12810,
			["difficulty"] = {
				1,
				125,
				250,
				260,
			},
			["reagents"] = {
				[8170] = 1,
				[16202] = 1,
			},
			["teaches"] = 17181,
		},
		[20008] = {
			["difficulty"] = {
				255,
				275,
				295,
				315,
			},
			["enchantId"] = 1883,
			["enchantSlot"] = "WRIST",
			["itemId"] = 16214,
			["reagents"] = {
				[16202] = 3,
			},
			["requiredSkill"] = 255,
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 7,
			},
			["teaches"] = 20008,
		},
		[20009] = {
			["difficulty"] = {
				270,
				290,
				310,
				330,
			},
			["enchantId"] = 1884,
			["enchantSlot"] = "WRIST",
			["itemId"] = 16218,
			["reagents"] = {
				[11176] = 10,
				[16202] = 3,
			},
			["requiredSkill"] = 270,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 9,
			},
			["teaches"] = 20009,
		},
		[20010] = {
			["difficulty"] = {
				295,
				315,
				335,
				355,
			},
			["enchantId"] = 1885,
			["enchantSlot"] = "WRIST",
			["itemId"] = 16246,
			["reagents"] = {
				[16203] = 6,
				[16204] = 6,
			},
			["requiredSkill"] = 295,
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 9,
			},
			["teaches"] = 20010,
		},
		[20011] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 1886,
			["enchantSlot"] = "WRIST",
			["itemId"] = 16251,
			["reagents"] = {
				[16204] = 15,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 9,
			},
			["teaches"] = 20011,
		},
		[20012] = {
			["difficulty"] = {
				270,
				290,
				310,
				330,
			},
			["enchantId"] = 1887,
			["enchantSlot"] = "HANDS",
			["itemId"] = 16219,
			["reagents"] = {
				[16202] = 3,
				[16204] = 3,
			},
			["requiredSkill"] = 270,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 7,
			},
			["teaches"] = 20012,
		},
		[20013] = {
			["difficulty"] = {
				295,
				315,
				335,
				355,
			},
			["enchantId"] = 927,
			["enchantSlot"] = "HANDS",
			["itemId"] = 16244,
			["reagents"] = {
				[16203] = 4,
				[16204] = 4,
			},
			["requiredSkill"] = 295,
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 7,
			},
			["teaches"] = 20013,
		},
		[20014] = {
			["difficulty"] = {
				265,
				285,
				305,
				325,
			},
			["enchantId"] = 1888,
			["enchantSlot"] = "BACK",
			["itemId"] = 16216,
			["reagents"] = {
				[7075] = 1,
				[7077] = 1,
				[7079] = 1,
				[7081] = 1,
				[7972] = 1,
				[16202] = 2,
			},
			["requiredSkill"] = 265,
			["stats"] = {
				["RESISTANCE1_NAME"] = 5,
				["RESISTANCE2_NAME"] = 5,
				["RESISTANCE3_NAME"] = 5,
				["RESISTANCE4_NAME"] = 5,
				["RESISTANCE5_NAME"] = 5,
				["RESISTANCE6_NAME"] = 5,
			},
			["teaches"] = 20014,
		},
		[20015] = {
			["difficulty"] = {
				285,
				305,
				325,
				345,
			},
			["enchantId"] = 1889,
			["enchantSlot"] = "BACK",
			["itemId"] = 16224,
			["reagents"] = {
				[16204] = 8,
			},
			["requiredSkill"] = 285,
			["stats"] = {
				["RESISTANCE0_NAME"] = 70,
			},
			["teaches"] = 20015,
		},
		[20016] = {
			["difficulty"] = {
				280,
				300,
				320,
				340,
			},
			["enchantId"] = 1890,
			["itemId"] = 16222,
			["reagents"] = {
				[16203] = 2,
				[16204] = 4,
			},
			["requiredSkill"] = 280,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 9,
			},
			["teaches"] = 20016,
		},
		[20017] = {
			["difficulty"] = {
				265,
				285,
				305,
				325,
			},
			["enchantId"] = 929,
			["itemId"] = 16217,
			["reagents"] = {
				[11176] = 10,
			},
			["requiredSkill"] = 265,
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 7,
			},
			["teaches"] = 20017,
		},
		[20020] = {
			["difficulty"] = {
				260,
				280,
				300,
				320,
			},
			["enchantId"] = 929,
			["enchantSlot"] = "FEET",
			["itemId"] = 16215,
			["reagents"] = {
				[11176] = 10,
			},
			["requiredSkill"] = 260,
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 7,
			},
			["teaches"] = 20020,
		},
		[20023] = {
			["difficulty"] = {
				295,
				315,
				335,
				355,
			},
			["enchantId"] = 1887,
			["enchantSlot"] = "FEET",
			["itemId"] = 16245,
			["reagents"] = {
				[16203] = 8,
			},
			["requiredSkill"] = 295,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 7,
			},
			["teaches"] = 20023,
		},
		[20024] = {
			["difficulty"] = {
				275,
				295,
				315,
				335,
			},
			["enchantId"] = 851,
			["enchantSlot"] = "FEET",
			["itemId"] = 16220,
			["reagents"] = {
				[16202] = 1,
				[16203] = 2,
			},
			["requiredSkill"] = 275,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 5,
			},
			["teaches"] = 20024,
		},
		[20025] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 1891,
			["enchantSlot"] = "CHEST",
			["itemId"] = 16253,
			["reagents"] = {
				[14344] = 4,
				[16203] = 10,
				[16204] = 15,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 4,
				["ITEM_MOD_INTELLECT_SHORT"] = 4,
				["ITEM_MOD_SPIRIT_SHORT"] = 4,
				["ITEM_MOD_STAMINA_SHORT"] = 4,
				["ITEM_MOD_STRENGTH_SHORT"] = 4,
			},
			["teaches"] = 20025,
		},
		[20026] = {
			["difficulty"] = {
				275,
				295,
				315,
				335,
			},
			["enchantId"] = 1892,
			["enchantSlot"] = "CHEST",
			["itemId"] = 16221,
			["reagents"] = {
				[14343] = 1,
				[16204] = 6,
			},
			["requiredSkill"] = 275,
			["stats"] = {
				["ITEM_MOD_HEALTH"] = 100,
			},
			["teaches"] = 20026,
		},
		[20028] = {
			["difficulty"] = {
				290,
				310,
				330,
				350,
			},
			["enchantId"] = 1893,
			["enchantSlot"] = "CHEST",
			["itemId"] = 16242,
			["reagents"] = {
				[14343] = 1,
				[16203] = 3,
			},
			["requiredSkill"] = 290,
			["stats"] = {
				["ITEM_MOD_MANA"] = 100,
			},
			["teaches"] = 20028,
		},
		[20029] = {
			["difficulty"] = {
				285,
				305,
				325,
				345,
			},
			["enchantId"] = 1894,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 16223,
			["reagents"] = {
				[7080] = 1,
				[7082] = 1,
				[13467] = 1,
				[14343] = 4,
			},
			["requiredSkill"] = 285,
			["teaches"] = 20029,
		},
		[20030] = {
			["difficulty"] = {
				295,
				315,
				335,
				355,
			},
			["enchantId"] = 1896,
			["enchantSlot"] = "WEAPON2H",
			["itemId"] = 16247,
			["reagents"] = {
				[14344] = 4,
				[16204] = 10,
			},
			["requiredSkill"] = 295,
			["teaches"] = 20030,
		},
		[20031] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 1897,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 16250,
			["reagents"] = {
				[14344] = 2,
				[16203] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 20031,
		},
		[20032] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 1898,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 16254,
			["reagents"] = {
				[12803] = 6,
				[12808] = 6,
				[14344] = 6,
			},
			["requiredSkill"] = 300,
			["teaches"] = 20032,
		},
		[20033] = {
			["difficulty"] = {
				295,
				315,
				335,
				355,
			},
			["enchantId"] = 1899,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 16248,
			["reagents"] = {
				[12808] = 4,
				[14344] = 4,
			},
			["requiredSkill"] = 295,
			["teaches"] = 20033,
		},
		[20034] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 1900,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 16252,
			["reagents"] = {
				[12811] = 2,
				[14344] = 4,
			},
			["requiredSkill"] = 300,
			["teaches"] = 20034,
		},
		[20035] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 1903,
			["enchantSlot"] = "WEAPON2H",
			["itemId"] = 16255,
			["reagents"] = {
				[14344] = 2,
				[16203] = 12,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 9,
			},
			["teaches"] = 20035,
		},
		[20036] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 1904,
			["enchantSlot"] = "WEAPON2H",
			["itemId"] = 16249,
			["reagents"] = {
				[14344] = 2,
				[16203] = 12,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 9,
			},
			["teaches"] = 20036,
		},
		[20051] = {
			["craftedItemId"] = 16207,
			["difficulty"] = {
				290,
				310,
				330,
				350,
			},
			["itemId"] = 16243,
			["reagents"] = {
				[13926] = 1,
				[14343] = 4,
				[14344] = 2,
				[16203] = 4,
				[16204] = 10,
				[16206] = 1,
			},
			["requiredSkill"] = 290,
			["teaches"] = 20051,
		},
		[21931] = {
			["difficulty"] = {
				190,
				210,
				230,
				250,
			},
			["enchantId"] = 2443,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 17725,
			["reagents"] = {
				[3819] = 2,
				[11135] = 3,
				[11137] = 3,
				[11139] = 1,
			},
			["requiredSkill"] = 190,
			["stats"] = {
				["ITEM_MOD_SPELL_POWER"] = 7,
			},
			["teaches"] = 21931,
		},
		[22749] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2504,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 18259,
			["reagents"] = {
				[7078] = 4,
				[7080] = 4,
				[7082] = 4,
				[13926] = 2,
				[14344] = 4,
				[16203] = 12,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 30,
				["ITEM_MOD_SPELL_POWER"] = 30,
			},
			["teaches"] = 22749,
		},
		[22750] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2505,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 18260,
			["reagents"] = {
				[7080] = 6,
				[12803] = 6,
				[12811] = 1,
				[14344] = 4,
				[16203] = 8,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 55,
			},
			["teaches"] = 22750,
		},
		[23799] = {
			["difficulty"] = {
				290,
				310,
				330,
				350,
			},
			["enchantId"] = 2563,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 19444,
			["reagents"] = {
				[7076] = 2,
				[14344] = 6,
				[16203] = 6,
				[16204] = 4,
			},
			["requiredSkill"] = 290,
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 15,
			},
			["teaches"] = 23799,
		},
		[23800] = {
			["difficulty"] = {
				290,
				310,
				330,
				350,
			},
			["enchantId"] = 2564,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 19445,
			["reagents"] = {
				[7082] = 2,
				[14344] = 6,
				[16203] = 6,
				[16204] = 4,
			},
			["requiredSkill"] = 290,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 15,
			},
			["teaches"] = 23800,
		},
		[23801] = {
			["difficulty"] = {
				290,
				310,
				330,
				350,
			},
			["enchantId"] = 2565,
			["enchantSlot"] = "WRIST",
			["itemId"] = 19446,
			["reagents"] = {
				[7080] = 2,
				[16203] = 4,
				[16204] = 16,
			},
			["requiredSkill"] = 290,
			["stats"] = {
				["ITEM_MOD_POWER_REGEN0_SHORT"] = 4,
			},
			["teaches"] = 23801,
		},
		[23802] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2566,
			["enchantSlot"] = "WRIST",
			["itemId"] = 19447,
			["reagents"] = {
				[12803] = 6,
				[14344] = 2,
				[16203] = 4,
				[16204] = 20,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 24,
			},
			["teaches"] = 23802,
		},
		[23803] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2567,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 19448,
			["reagents"] = {
				[14344] = 10,
				[16203] = 8,
				[16204] = 15,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 20,
			},
			["teaches"] = 23803,
		},
		[23804] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2568,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 19449,
			["reagents"] = {
				[14344] = 15,
				[16203] = 12,
				[16204] = 20,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 22,
			},
			["teaches"] = 23804,
		},
		[25072] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2613,
			["enchantSlot"] = "HANDS",
			["itemId"] = 20726,
			["phase"] = 4,
			["reagents"] = {
				[14344] = 6,
				[18512] = 8,
				[20725] = 4,
			},
			["requiredSkill"] = 300,
			["teaches"] = 25072,
		},
		[25073] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2614,
			["enchantSlot"] = "HANDS",
			["itemId"] = 20727,
			["reagents"] = {
				[12808] = 6,
				[14344] = 10,
				[20725] = 3,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_POWER"] = 20,
			},
			["teaches"] = 25073,
		},
		[25074] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2615,
			["enchantSlot"] = "HANDS",
			["itemId"] = 20728,
			["reagents"] = {
				[7080] = 4,
				[14344] = 10,
				[20725] = 3,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_POWER"] = 20,
			},
			["teaches"] = 25074,
		},
		[25078] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2616,
			["enchantSlot"] = "HANDS",
			["itemId"] = 20729,
			["reagents"] = {
				[7078] = 4,
				[14344] = 10,
				[20725] = 2,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_POWER"] = 20,
			},
			["teaches"] = 25078,
		},
		[25079] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2617,
			["enchantSlot"] = "HANDS",
			["itemId"] = 20730,
			["reagents"] = {
				[12811] = 1,
				[14344] = 8,
				[20725] = 3,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 30,
			},
			["teaches"] = 25079,
		},
		[25080] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2564,
			["enchantSlot"] = "HANDS",
			["itemId"] = 20731,
			["reagents"] = {
				[7082] = 4,
				[14344] = 8,
				[20725] = 3,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 15,
			},
			["teaches"] = 25080,
		},
		[25081] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2619,
			["enchantSlot"] = "BACK",
			["itemId"] = 20732,
			["reagents"] = {
				[7078] = 4,
				[14344] = 8,
				[20725] = 3,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["RESISTANCE2_NAME"] = 15,
			},
			["teaches"] = 25081,
		},
		[25082] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2620,
			["enchantSlot"] = "BACK",
			["itemId"] = 20733,
			["reagents"] = {
				[12803] = 4,
				[14344] = 8,
				[20725] = 2,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["RESISTANCE3_NAME"] = 15,
			},
			["teaches"] = 25082,
		},
		[25083] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 910,
			["enchantSlot"] = "BACK",
			["itemId"] = 20734,
			["reagents"] = {
				[13468] = 2,
				[14344] = 8,
				[20725] = 3,
			},
			["requiredSkill"] = 300,
			["teaches"] = 25083,
		},
		[25084] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2621,
			["enchantSlot"] = "BACK",
			["itemId"] = 20735,
			["reagents"] = {
				[11754] = 2,
				[14344] = 6,
				[20725] = 4,
			},
			["requiredSkill"] = 300,
			["teaches"] = 25084,
		},
		[25086] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 2622,
			["enchantSlot"] = "BACK",
			["itemId"] = 20736,
			["reagents"] = {
				[12809] = 8,
				[14344] = 8,
				[20725] = 3,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["DODGE_PCT"] = 1,
			},
			["teaches"] = 25086,
		},
		[25124] = {
			["craftedItemId"] = 20744,
			["difficulty"] = {
				45,
				55,
				65,
				75,
			},
			["itemId"] = 20758,
			["reagents"] = {
				[3371] = 1,
				[10940] = 2,
				[17034] = 1,
			},
			["requiredSkill"] = 45,
			["teaches"] = 25124,
		},
		[25125] = {
			["craftedItemId"] = 20745,
			["difficulty"] = {
				150,
				160,
				170,
				180,
			},
			["itemId"] = 20752,
			["reagents"] = {
				[3372] = 1,
				[11083] = 3,
				[17034] = 2,
			},
			["requiredSkill"] = 150,
			["teaches"] = 25125,
		},
		[25126] = {
			["craftedItemId"] = 20746,
			["difficulty"] = {
				200,
				210,
				220,
				230,
			},
			["itemId"] = 20753,
			["reagents"] = {
				[3372] = 1,
				[11137] = 3,
				[17035] = 2,
			},
			["requiredSkill"] = 200,
			["teaches"] = 25126,
		},
		[25127] = {
			["craftedItemId"] = 20747,
			["difficulty"] = {
				250,
				260,
				270,
				280,
			},
			["itemId"] = 20754,
			["reagents"] = {
				[8831] = 2,
				[8925] = 1,
				[11176] = 3,
			},
			["requiredSkill"] = 250,
			["teaches"] = 25127,
		},
		[25128] = {
			["craftedItemId"] = 20750,
			["difficulty"] = {
				275,
				285,
				295,
				305,
			},
			["itemId"] = 20755,
			["reagents"] = {
				[4625] = 2,
				[8925] = 1,
				[16204] = 3,
			},
			["requiredSkill"] = 275,
			["teaches"] = 25128,
		},
		[25129] = {
			["craftedItemId"] = 20749,
			["difficulty"] = {
				300,
				310,
				320,
				330,
			},
			["itemId"] = 20756,
			["reagents"] = {
				[4625] = 3,
				[14344] = 2,
				[18256] = 1,
			},
			["requiredSkill"] = 300,
			["teaches"] = 25129,
		},
		[25130] = {
			["craftedItemId"] = 20748,
			["difficulty"] = {
				300,
				310,
				320,
				330,
			},
			["itemId"] = 20757,
			["reagents"] = {
				[8831] = 3,
				[14344] = 2,
				[18256] = 1,
			},
			["requiredSkill"] = 300,
			["teaches"] = 25130,
		},
		[27837] = {
			["difficulty"] = {
				290,
				310,
				330,
				350,
			},
			["enchantId"] = 2646,
			["enchantSlot"] = "WEAPON2H",
			["itemId"] = 22392,
			["reagents"] = {
				[7082] = 4,
				[14344] = 10,
				[16203] = 6,
				[16204] = 14,
			},
			["requiredSkill"] = 290,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 25,
			},
			["teaches"] = 27837,
		},
		[430409] = {
			["craftedItemId"] = 211848,
			["difficulty"] = {
				100,
				105,
				110,
				120,
			},
			["itemId"] = 211849,
			["reagents"] = {
				[3372] = 1,
				[10939] = 1,
				[10940] = 5,
			},
			["requiredSkill"] = 100,
			["teaches"] = 430409,
		},
		[435481] = {
			["difficulty"] = {
				225,
				227,
				230,
				235,
			},
			["enchantId"] = 7210,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 215129,
			["reagents"] = {
				[5637] = 2,
				[11174] = 4,
				[11177] = 2,
			},
			["requiredSkill"] = 225,
			["teaches"] = 435481,
		},
		[435903] = {
			["difficulty"] = {
				225,
				228,
				232,
				240,
			},
			["enchantId"] = 7223,
			["enchantSlot"] = "CHEST",
			["itemId"] = 215138,
			["reagents"] = {
				[11176] = 2,
				[11177] = 1,
			},
			["requiredSkill"] = 225,
			["teaches"] = 435903,
		},
		[439134] = {
			["craftedItemId"] = 217287,
			["difficulty"] = {
				175,
				195,
				215,
				235,
			},
			["reagents"] = {
				[11135] = 1,
				[11137] = 1,
				[11291] = 1,
			},
			["requiredSkill"] = 175,
			["teaches"] = 439134,
		},
		[439156] = {
			["craftedItemId"] = 217308,
			["difficulty"] = {
				225,
				226,
				227,
				230,
			},
			["itemId"] = 215141,
			["reagents"] = {
				[11137] = 5,
			},
			["requiredSkill"] = 225,
			["teaches"] = 439156,
		},
		[446243] = {
			["craftedItemId"] = 221028,
			["difficulty"] = {
				250,
				252,
				255,
				260,
			},
			["reagents"] = {
				[11176] = 5,
			},
			["requiredSkill"] = 250,
			["teaches"] = 446243,
		},
		[448624] = {
			["craftedItemId"] = 220792,
			["difficulty"] = {
				120,
				122,
				125,
				130,
			},
			["itemId"] = 223163,
			["reagents"] = {
				[4470] = 1,
				[10940] = 4,
			},
			["requiredSkill"] = 120,
			["teaches"] = 448624,
		},
		[463866] = {
			["craftedItemId"] = 228978,
			["difficulty"] = {
				290,
				305,
				312,
				320,
			},
			["itemId"] = 228979,
			["reagents"] = {
				[16204] = 1,
			},
			["requiredSkill"] = 290,
			["teaches"] = 463866,
		},
		[463869] = {
			["craftedItemId"] = 228980,
			["difficulty"] = {
				275,
				285,
				295,
				305,
			},
			["itemId"] = 228981,
			["reagents"] = {
				[4625] = 1,
				[8925] = 1,
				[16204] = 2,
			},
			["requiredSkill"] = 275,
			["teaches"] = 463869,
		},
		[463871] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 7603,
			["itemId"] = 228982,
			["reagents"] = {
				[7076] = 1,
				[7078] = 4,
				[7080] = 4,
				[12811] = 1,
				[14344] = 4,
				[16203] = 12,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 55,
				["ITEM_MOD_SPELL_POWER"] = 30,
			},
			["teaches"] = 463871,
		},
		[471400] = {
			["craftedItemId"] = 232611,
			["difficulty"] = {
				300,
				310,
				320,
				330,
			},
			["itemId"] = 232610,
			["reagents"] = {
				[8151] = 3,
				[8152] = 3,
				[14344] = 2,
				[18256] = 1,
			},
			["requiredSkill"] = 300,
			["teaches"] = 471400,
		},
		[1213593] = {
			["craftedItemId"] = 233990,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234266,
			["reagents"] = {
				[2452] = 20,
				[20725] = 6,
				[234004] = 6,
				[234006] = 10,
				[234010] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213593,
		},
		[1213595] = {
			["craftedItemId"] = 233991,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234267,
			["reagents"] = {
				[20725] = 4,
				[234003] = 10,
				[234006] = 10,
				[234010] = 10,
				[234012] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213595,
		},
		[1213598] = {
			["craftedItemId"] = 233992,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234268,
			["reagents"] = {
				[20725] = 4,
				[234003] = 10,
				[234007] = 10,
				[234010] = 5,
				[234011] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213598,
		},
		[1213600] = {
			["craftedItemId"] = 233993,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234269,
			["reagents"] = {
				[2459] = 3,
				[14344] = 4,
				[234003] = 3,
				[234005] = 6,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213600,
		},
		[1213603] = {
			["craftedItemId"] = 233994,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234270,
			["reagents"] = {
				[20725] = 6,
				[234003] = 10,
				[234007] = 10,
				[234010] = 5,
				[234011] = 10,
				[234012] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213603,
		},
		[1213607] = {
			["craftedItemId"] = 233995,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234271,
			["reagents"] = {
				[14047] = 1,
				[16203] = 1,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213607,
		},
		[1213610] = {
			["craftedItemId"] = 233996,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234272,
			["reagents"] = {
				[16204] = 2,
				[234011] = 3,
				[234012] = 3,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213610,
		},
		[1213616] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 7645,
			["enchantSlot"] = "CHEST",
			["itemId"] = 233997,
			["reagents"] = {
				[13458] = 10,
				[16203] = 5,
				[16204] = 8,
				[20725] = 2,
				[234010] = 2,
				[234011] = 2,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 4,
				["ITEM_MOD_INTELLECT_SHORT"] = 4,
				["ITEM_MOD_SPIRIT_SHORT"] = 4,
				["ITEM_MOD_STAMINA_SHORT"] = 4,
				["ITEM_MOD_STRENGTH_SHORT"] = 4,
				["RESISTANCE3_NAME"] = 15,
			},
			["teaches"] = 1213616,
		},
		[1213622] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 7646,
			["enchantSlot"] = "HANDS",
			["itemId"] = 233998,
			["reagents"] = {
				[12735] = 2,
				[13180] = 5,
				[14344] = 5,
				[20725] = 2,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_POWER"] = 20,
			},
			["teaches"] = 1213622,
		},
		[1213626] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 7647,
			["enchantSlot"] = "HANDS",
			["itemId"] = 233999,
			["reagents"] = {
				[12753] = 2,
				[14344] = 5,
				[20725] = 2,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_POWER"] = 20,
			},
			["teaches"] = 1213626,
		},
		[1213628] = {
			["craftedItemId"] = 234000,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234275,
			["reagents"] = {
				[12810] = 4,
				[20725] = 3,
				[234003] = 2,
				[234008] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213628,
		},
		[1213633] = {
			["craftedItemId"] = 234001,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234276,
			["reagents"] = {
				[12810] = 3,
				[20725] = 3,
				[234003] = 2,
				[234012] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213633,
		},
		[1213635] = {
			["craftedItemId"] = 234002,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 234277,
			["reagents"] = {
				[12810] = 3,
				[20725] = 2,
				[234010] = 4,
				[234011] = 4,
				[234012] = 20,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213635,
		},
		[1216005] = {
			["craftedItemId"] = 234477,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 235133,
			["reagents"] = {
				[12810] = 4,
				[20725] = 3,
				[234003] = 2,
				[234008] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1216005,
		},
		[1216007] = {
			["craftedItemId"] = 234475,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 235134,
			["reagents"] = {
				[12810] = 4,
				[20725] = 3,
				[234003] = 2,
				[234008] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1216007,
		},
		[1216010] = {
			["craftedItemId"] = 234476,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 235135,
			["reagents"] = {
				[12810] = 4,
				[20725] = 3,
				[234003] = 2,
				[234008] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1216010,
		},
		[1216014] = {
			["craftedItemId"] = 234480,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 235136,
			["reagents"] = {
				[12810] = 3,
				[20725] = 3,
				[234003] = 2,
				[234012] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1216014,
		},
		[1216016] = {
			["craftedItemId"] = 234478,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 235137,
			["reagents"] = {
				[12810] = 3,
				[20725] = 3,
				[234003] = 2,
				[234012] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1216016,
		},
		[1216018] = {
			["craftedItemId"] = 234479,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 235138,
			["reagents"] = {
				[12810] = 3,
				[20725] = 3,
				[234003] = 2,
				[234012] = 10,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1216018,
		},
		[1216020] = {
			["craftedItemId"] = 234474,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 235139,
			["reagents"] = {
				[12810] = 3,
				[20725] = 2,
				[234010] = 4,
				[234011] = 4,
				[234012] = 20,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1216020,
		},
		[1216022] = {
			["craftedItemId"] = 234469,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 235140,
			["reagents"] = {
				[12810] = 3,
				[20725] = 2,
				[234010] = 4,
				[234011] = 4,
				[234012] = 20,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1216022,
		},
		[1216024] = {
			["craftedItemId"] = 234468,
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["itemId"] = 235141,
			["reagents"] = {
				[12810] = 3,
				[20725] = 2,
				[234010] = 4,
				[234011] = 4,
				[234012] = 20,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1216024,
		},
		[1217189] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 7655,
			["enchantSlot"] = "WRIST",
			["itemId"] = 235526,
			["reagents"] = {
				[7078] = 2,
				[7080] = 2,
				[7082] = 2,
				[14344] = 2,
				[16203] = 4,
				[16204] = 20,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
			},
			["teaches"] = 1217189,
		},
		[1217203] = {
			["difficulty"] = {
				300,
				320,
				340,
				360,
			},
			["enchantId"] = 7656,
			["enchantSlot"] = "WRIST",
			["itemId"] = 235528,
			["reagents"] = {
				[7082] = 2,
				[16203] = 2,
				[16204] = 10,
				[20725] = 2,
			},
			["requiredSkill"] = 300,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 9,
			},
			["teaches"] = 1217203,
		},
		[1219577] = {
			["difficulty"] = {
				320,
				330,
				340,
				360,
			},
			["enchantId"] = 7659,
			["reagents"] = {
				[7082] = 2,
				[16204] = 18,
				[20725] = 2,
			},
			["requiredSkill"] = 320,
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 9,
			},
			["teaches"] = 1219577,
		},
		[1219578] = {
			["difficulty"] = {
				320,
				330,
				340,
				360,
			},
			["enchantId"] = 7660,
			["reagents"] = {
				[7080] = 2,
				[16204] = 18,
				[20725] = 2,
			},
			["requiredSkill"] = 320,
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 12,
			},
			["teaches"] = 1219578,
		},
		[1219579] = {
			["difficulty"] = {
				320,
				330,
				340,
				360,
			},
			["enchantId"] = 7661,
			["reagents"] = {
				[7080] = 1,
				[7082] = 1,
				[14344] = 6,
				[16204] = 18,
			},
			["requiredSkill"] = 320,
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 6,
				["ITEM_MOD_SPIRIT_SHORT"] = 5,
			},
			["teaches"] = 1219579,
		},
		[1219580] = {
			["difficulty"] = {
				320,
				330,
				340,
				360,
			},
			["enchantId"] = 7662,
			["enchantSlot"] = "WEAPON2H",
			["reagents"] = {
				[8831] = 6,
				[12938] = 1,
				[16204] = 24,
				[20725] = 3,
			},
			["requiredSkill"] = 320,
			["teaches"] = 1219580,
		},
		[1219581] = {
			["difficulty"] = {
				320,
				330,
				340,
				360,
			},
			["enchantId"] = 7663,
			["enchantSlot"] = "SHIELD",
			["reagents"] = {
				[7076] = 2,
				[14344] = 6,
				[16204] = 18,
			},
			["requiredSkill"] = 320,
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 12,
			},
			["teaches"] = 1219581,
		},
		[1219586] = {
			["difficulty"] = {
				320,
				330,
				340,
				360,
			},
			["enchantId"] = 7666,
			["enchantSlot"] = "HANDS",
			["reagents"] = {
				[7078] = 2,
				[16203] = 7,
				[16204] = 21,
			},
			["requiredSkill"] = 320,
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 15,
			},
			["teaches"] = 1219586,
		},
		[1219587] = {
			["difficulty"] = {
				320,
				330,
				340,
				360,
			},
			["enchantId"] = 7667,
			["enchantSlot"] = "BACK",
			["reagents"] = {
				[7078] = 1,
				[16203] = 3,
				[16204] = 9,
			},
			["requiredSkill"] = 320,
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 5,
			},
			["teaches"] = 1219587,
		},
		[1220623] = {
			["difficulty"] = {
				320,
				330,
				340,
				360,
			},
			["enchantId"] = 7664,
			["enchantSlot"] = "SHIELD",
			["reagents"] = {
				[12938] = 1,
				[14344] = 5,
				[16204] = 15,
			},
			["requiredSkill"] = 320,
			["stats"] = {
				["CRIT_PCT"] = 1,
			},
			["teaches"] = 1220623,
		},
		[1220624] = {
			["difficulty"] = {
				320,
				330,
				340,
				360,
			},
			["enchantId"] = 7665,
			["enchantSlot"] = "WRIST",
			["reagents"] = {
				[8831] = 2,
				[12808] = 12,
				[16203] = 3,
				[16204] = 9,
			},
			["requiredSkill"] = 320,
			["teaches"] = 1220624,
		},
		[1231128] = {
			["difficulty"] = {
				280,
				305,
				307,
				310,
			},
			["enchantId"] = 7940,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 241191,
			["reagents"] = {
				[12811] = 2,
				[12938] = 1,
				[14344] = 5,
				[20725] = 2,
			},
			["requiredSkill"] = 280,
			["teaches"] = 1231128,
		},
		[1231139] = {
			["difficulty"] = {
				280,
				305,
				307,
				310,
			},
			["enchantId"] = 7941,
			["enchantSlot"] = "WEAPON2H",
			["itemId"] = 241195,
			["reagents"] = {
				[12811] = 4,
				[12938] = 1,
				[14344] = 10,
				[20725] = 4,
			},
			["requiredSkill"] = 280,
			["teaches"] = 1231139,
		},
		[1231164] = {
			["difficulty"] = {
				280,
				305,
				307,
				310,
			},
			["enchantId"] = 7942,
			["enchantSlot"] = "WEAPON1H",
			["itemId"] = 241201,
			["reagents"] = {
				[12811] = 3,
				[12938] = 1,
				[14344] = 6,
				[20725] = 2,
			},
			["requiredSkill"] = 280,
			["teaches"] = 1231164,
		},
		[1232172] = {
			["difficulty"] = {
				280,
				305,
				307,
				310,
			},
			["enchantId"] = 7943,
			["enchantSlot"] = "WEAPON2H",
			["itemId"] = 242361,
			["reagents"] = {
				[12811] = 6,
				[12938] = 1,
				[14344] = 10,
				[20725] = 4,
			},
			["requiredSkill"] = 280,
			["teaches"] = 1232172,
		},
	})

lib:LoadEnchantsCore({
		[15] = {
			["itemId"] = 2304,
			["slots"] = {
				"CHEST",
				"FEET",
				"HANDS",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE0_NAME"] = 8,
			},
		},
		[16] = {
			["itemId"] = 2313,
			["slots"] = {
				"CHEST",
				"FEET",
				"HANDS",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE0_NAME"] = 16,
			},
		},
		[17] = {
			["itemId"] = 4265,
			["slots"] = {
				"CHEST",
				"FEET",
				"HANDS",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE0_NAME"] = 24,
			},
		},
		[18] = {
			["itemId"] = 8173,
			["slots"] = {
				"CHEST",
				"FEET",
				"HANDS",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE0_NAME"] = 32,
			},
		},
		[464] = {
			["itemId"] = 7969,
			["slots"] = {
				"FEET",
			},
		},
		[1483] = {
			["itemId"] = 11622,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_MANA"] = 150,
			},
		},
		[1503] = {
			["itemId"] = 11642,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_HEALTH"] = 100,
			},
		},
		[1504] = {
			["itemId"] = 11643,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE0_NAME"] = 125,
			},
		},
		[1505] = {
			["itemId"] = 11644,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE2_NAME"] = 20,
			},
		},
		[1506] = {
			["itemId"] = 11645,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_STRENGTH_SHORT"] = 8,
			},
		},
		[1507] = {
			["itemId"] = 11646,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 8,
			},
		},
		[1508] = {
			["itemId"] = 11647,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 8,
			},
		},
		[1509] = {
			["itemId"] = 11648,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 8,
			},
		},
		[1510] = {
			["itemId"] = 11649,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_SPIRIT_SHORT"] = 8,
			},
		},
		[1843] = {
			["itemId"] = 15564,
			["slots"] = {
				"CHEST",
				"FEET",
				"HANDS",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE0_NAME"] = 40,
			},
		},
		[2483] = {
			["itemId"] = 18169,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["RESISTANCE2_NAME"] = 5,
			},
		},
		[2484] = {
			["itemId"] = 18170,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["RESISTANCE4_NAME"] = 5,
			},
		},
		[2485] = {
			["itemId"] = 18171,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["RESISTANCE6_NAME"] = 5,
			},
		},
		[2486] = {
			["itemId"] = 18172,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["RESISTANCE3_NAME"] = 5,
			},
		},
		[2487] = {
			["itemId"] = 18173,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["RESISTANCE5_NAME"] = 5,
			},
		},
		[2488] = {
			["itemId"] = 18182,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["RESISTANCE1_NAME"] = 5,
				["RESISTANCE2_NAME"] = 5,
				["RESISTANCE3_NAME"] = 5,
				["RESISTANCE4_NAME"] = 5,
				["RESISTANCE5_NAME"] = 5,
				["RESISTANCE6_NAME"] = 5,
			},
		},
		[2503] = {
			["itemId"] = 18251,
			["slots"] = {
				"CHEST",
				"FEET",
				"HANDS",
				"LEGS",
			},
			["stats"] = {
				["DEFENSE"] = 3,
			},
		},
		[2543] = {
			["itemId"] = 18329,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["RANGED_HASTE_PCT"] = 1,
			},
		},
		[2544] = {
			["itemId"] = 18330,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 8,
				["ITEM_MOD_SPELL_POWER"] = 8,
			},
		},
		[2545] = {
			["itemId"] = 18331,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["DODGE_PCT"] = 1,
			},
		},
		[2583] = {
			["itemId"] = 19782,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["BLOCK_VALUE"] = 15,
				["DEFENSE"] = 7,
				["ITEM_MOD_STAMINA_SHORT"] = 10,
			},
		},
		[2584] = {
			["itemId"] = 19783,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["DEFENSE"] = 7,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 24,
				["ITEM_MOD_STAMINA_SHORT"] = 10,
			},
		},
		[2585] = {
			["itemId"] = 19784,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["DODGE_PCT"] = 1,
				["ITEM_MOD_ATTACK_POWER_SHORT"] = 28,
			},
		},
		[2586] = {
			["itemId"] = 19785,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["HIT_PCT"] = 1,
				["ITEM_MOD_RANGED_ATTACK_POWER_SHORT"] = 24,
				["ITEM_MOD_STAMINA_SHORT"] = 10,
			},
		},
		[2587] = {
			["itemId"] = 19786,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 15,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 13,
				["ITEM_MOD_SPELL_POWER"] = 13,
			},
		},
		[2588] = {
			["itemId"] = 19787,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 18,
				["ITEM_MOD_SPELL_POWER"] = 18,
				["SPELL_HIT_PCT"] = 1,
			},
		},
		[2589] = {
			["itemId"] = 19788,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 18,
				["ITEM_MOD_SPELL_POWER"] = 18,
				["ITEM_MOD_STAMINA_SHORT"] = 10,
			},
		},
		[2590] = {
			["itemId"] = 19789,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_POWER_REGEN0_SHORT"] = 4,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 24,
				["ITEM_MOD_STAMINA_SHORT"] = 10,
			},
		},
		[2591] = {
			["itemId"] = 19790,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 10,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 24,
				["ITEM_MOD_STAMINA_SHORT"] = 10,
			},
		},
		[2604] = {
			["itemId"] = 20078,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 33,
			},
		},
		[2605] = {
			["itemId"] = 20076,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 18,
				["ITEM_MOD_SPELL_POWER"] = 18,
			},
		},
		[2606] = {
			["itemId"] = 20077,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["ITEM_MOD_ATTACK_POWER_SHORT"] = 30,
				["ITEM_MOD_RANGED_ATTACK_POWER_SHORT"] = 30,
			},
		},
		[2681] = {
			["itemId"] = 22635,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE3_NAME"] = 10,
			},
		},
		[2682] = {
			["itemId"] = 22636,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE4_NAME"] = 10,
			},
		},
		[2683] = {
			["itemId"] = 22638,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["RESISTANCE5_NAME"] = 10,
			},
		},
		[2715] = {
			["itemId"] = 23547,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["ITEM_MOD_POWER_REGEN0_SHORT"] = 5,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 31,
			},
		},
		[2716] = {
			["itemId"] = 23549,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["ITEM_MOD_STAMINA_SHORT"] = 16,
				["RESISTANCE0_NAME"] = 100,
			},
		},
		[2717] = {
			["itemId"] = 23548,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["CRIT_PCT"] = 1,
				["ITEM_MOD_ATTACK_POWER_SHORT"] = 26,
				["ITEM_MOD_RANGED_ATTACK_POWER_SHORT"] = 26,
			},
		},
		[2721] = {
			["itemId"] = 23545,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 15,
				["ITEM_MOD_SPELL_POWER"] = 15,
				["SPELL_CRIT_PCT"] = 1,
			},
		},
		[7123] = {
			["itemId"] = 212546,
			["slots"] = {
				"SHOULDER",
			},
		},
		[7124] = {
			["itemId"] = 212568,
			["slots"] = {
				"HEAD",
			},
		},
		[7325] = {
			["itemId"] = 221322,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 9,
				["ITEM_MOD_SPELL_POWER"] = 9,
			},
		},
		[7326] = {
			["itemId"] = 221323,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 18,
			},
		},
		[7328] = {
			["itemId"] = 221321,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["ITEM_MOD_ATTACK_POWER_SHORT"] = 15,
				["ITEM_MOD_RANGED_ATTACK_POWER_SHORT"] = 15,
			},
		},
		[7563] = {
			["itemId"] = 227819,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["RESISTANCE2_NAME"] = 25,
			},
		},
		[7564] = {
			["itemId"] = 227926,
			["slots"] = {
				"BACK",
			},
			["stats"] = {
				["RESISTANCE2_NAME"] = 30,
			},
		},
		[7613] = {
			["itemId"] = 231354,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 10,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 22,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7614] = {
			["itemId"] = 231355,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["HIT_PCT"] = 1,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["SPELL_HIT_PCT"] = 1,
			},
		},
		[7615] = {
			["itemId"] = 231357,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 10,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["ITEM_MOD_STRENGTH_SHORT"] = 10,
			},
		},
		[7616] = {
			["itemId"] = 231358,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["DEFENSE"] = 7,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["ITEM_MOD_STRENGTH_SHORT"] = 10,
			},
		},
		[7617] = {
			["itemId"] = 231359,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["HIT_PCT"] = 1,
				["ITEM_MOD_AGILITY_SHORT"] = 10,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["SPELL_HIT_PCT"] = 1,
			},
		},
		[7618] = {
			["itemId"] = 231361,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["DEFENSE"] = 7,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7619] = {
			["itemId"] = 231362,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["ITEM_MOD_STRENGTH_SHORT"] = 10,
			},
		},
		[7620] = {
			["itemId"] = 231363,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 10,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 22,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7621] = {
			["itemId"] = 231364,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 10,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7622] = {
			["itemId"] = 231366,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 10,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 22,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7623] = {
			["itemId"] = 231367,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 10,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7624] = {
			["itemId"] = 231368,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["DEFENSE"] = 7,
				["ITEM_MOD_AGILITY_SHORT"] = 10,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7625] = {
			["itemId"] = 231370,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["HIT_PCT"] = 1,
				["ITEM_MOD_AGILITY_SHORT"] = 10,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["SPELL_HIT_PCT"] = 1,
			},
		},
		[7626] = {
			["itemId"] = 231371,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["ITEM_MOD_STRENGTH_SHORT"] = 10,
			},
		},
		[7627] = {
			["itemId"] = 231372,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["HIT_PCT"] = 1,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["SPELL_HIT_PCT"] = 1,
			},
		},
		[7628] = {
			["itemId"] = 231373,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 10,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 22,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7629] = {
			["itemId"] = 231375,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["BLOCK_PCT"] = 2,
				["DEFENSE"] = 7,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7630] = {
			["itemId"] = 231376,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["HIT_PCT"] = 1,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["SPELL_HIT_PCT"] = 1,
			},
		},
		[7631] = {
			["itemId"] = 231377,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["DEFENSE"] = 7,
				["HIT_PCT"] = 1,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["SPELL_HIT_PCT"] = 1,
			},
		},
		[7632] = {
			["itemId"] = 231379,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 10,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["ITEM_MOD_STRENGTH_SHORT"] = 10,
			},
		},
		[7633] = {
			["itemId"] = 231381,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["BLOCK_VALUE"] = 15,
				["DEFENSE"] = 7,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7634] = {
			["itemId"] = 231383,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_INTELLECT_SHORT"] = 10,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 12,
				["ITEM_MOD_SPELL_POWER"] = 12,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
			},
		},
		[7635] = {
			["itemId"] = 231384,
			["slots"] = {
				"HEAD",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_AGILITY_SHORT"] = 10,
				["ITEM_MOD_STAMINA_SHORT"] = 20,
				["ITEM_MOD_STRENGTH_SHORT"] = 10,
			},
		},
		[7648] = {
			["itemId"] = 233802,
			["slots"] = {
				"CHEST",
				"FEET",
				"HANDS",
				"LEGS",
			},
			["stats"] = {
				["ITEM_MOD_SPELL_HEALING_DONE"] = 10,
				["ITEM_MOD_SPELL_POWER"] = 10,
			},
		},
		[7649] = {
			["itemId"] = 233803,
			["slots"] = {
				"CHEST",
				"FEET",
				"HANDS",
				"LEGS",
			},
		},
		[7882] = {
			["itemId"] = 236323,
			["slots"] = {
				"SHOULDER",
			},
		},
		[7883] = {
			["itemId"] = 236324,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["CRIT_PCT"] = 1,
				["ITEM_MOD_SPELL_HEALING_DONE"] = 15,
				["ITEM_MOD_SPELL_POWER"] = 15,
			},
		},
		[7884] = {
			["itemId"] = 236326,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["CRIT_PCT"] = 1,
				["ITEM_MOD_ATTACK_POWER_SHORT"] = 26,
				["ITEM_MOD_RANGED_ATTACK_POWER_SHORT"] = 26,
			},
		},
		[7885] = {
			["itemId"] = 236325,
			["slots"] = {
				"SHOULDER",
			},
			["stats"] = {
				["DEFENSE"] = 7,
				["ITEM_MOD_STAMINA_SHORT"] = 16,
			},
		},
	})

end
