local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB core data — WoW Vanilla, Firstaid (locale-independent)
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 16 recipes

local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadCore(129, {
		[3275] = {
			["craftedItemId"] = 1251,
			["difficulty"] = {
				1,
				15,
				30,
				60,
			},
			["reagents"] = {
				[2589] = 1,
			},
			["requiredSkill"] = 1,
			["teaches"] = 3275,
		},
		[3276] = {
			["craftedItemId"] = 2581,
			["difficulty"] = {
				1,
				25,
				50,
				100,
			},
			["reagents"] = {
				[2589] = 2,
			},
			["teaches"] = 3276,
		},
		[3277] = {
			["craftedItemId"] = 3530,
			["difficulty"] = {
				1,
				40,
				80,
				150,
			},
			["reagents"] = {
				[2592] = 1,
			},
			["teaches"] = 3277,
		},
		[3278] = {
			["craftedItemId"] = 3531,
			["difficulty"] = {
				1,
				58,
				115,
				185,
			},
			["reagents"] = {
				[2592] = 2,
			},
			["teaches"] = 3278,
		},
		[7924] = {
			["difficulty"] = {
				125,
				125,
				125,
				125,
			},
			["itemId"] = 16084,
			["reagents"] = {},
			["requiredSkill"] = 125,
			["teaches"] = 7924,
		},
		[7928] = {
			["craftedItemId"] = 6450,
			["difficulty"] = {
				1,
				75,
				150,
				210,
			},
			["reagents"] = {
				[4306] = 1,
			},
			["teaches"] = 7928,
		},
		[7929] = {
			["craftedItemId"] = 6451,
			["difficulty"] = {
				180,
				195,
				210,
				240,
			},
			["itemId"] = 16112,
			["reagents"] = {
				[4306] = 2,
			},
			["requiredSkill"] = 180,
			["teaches"] = 7929,
		},
		[7934] = {
			["craftedItemId"] = 6452,
			["difficulty"] = {
				1,
				40,
				80,
				150,
			},
			["reagents"] = {
				[1475] = 1,
			},
			["teaches"] = 7934,
		},
		[7935] = {
			["craftedItemId"] = 6453,
			["difficulty"] = {
				130,
				147,
				165,
				200,
			},
			["itemId"] = 6454,
			["reagents"] = {
				[1288] = 1,
			},
			["requiredSkill"] = 130,
			["teaches"] = 7935,
		},
		[10840] = {
			["craftedItemId"] = 8544,
			["difficulty"] = {
				210,
				225,
				240,
				270,
			},
			["itemId"] = 16113,
			["reagents"] = {
				[4338] = 1,
			},
			["requiredSkill"] = 210,
			["teaches"] = 10840,
		},
		[10841] = {
			["craftedItemId"] = 8545,
			["difficulty"] = {
				1,
				120,
				240,
				300,
			},
			["reagents"] = {
				[4338] = 2,
			},
			["teaches"] = 10841,
		},
		[10846] = {
			["difficulty"] = {
				200,
				200,
				200,
				200,
			},
			["itemId"] = 16085,
			["reagents"] = {},
			["requiredSkill"] = 200,
			["teaches"] = 10846,
		},
		[18629] = {
			["craftedItemId"] = 14529,
			["difficulty"] = {
				1,
				130,
				260,
				320,
			},
			["reagents"] = {
				[14047] = 1,
			},
			["teaches"] = 18629,
		},
		[18630] = {
			["craftedItemId"] = 14530,
			["difficulty"] = {
				1,
				145,
				290,
				350,
			},
			["reagents"] = {
				[14047] = 2,
			},
			["teaches"] = 18630,
		},
		[23787] = {
			["craftedItemId"] = 19440,
			["difficulty"] = {
				300,
				315,
				330,
				360,
			},
			["itemId"] = 19442,
			["reagents"] = {
				[19441] = 1,
			},
			["requiredSkill"] = 300,
			["teaches"] = 23787,
		},
		[470349] = {
			["craftedItemId"] = 232433,
			["difficulty"] = {
				300,
				315,
				327,
				340,
			},
			["itemId"] = 232434,
			["reagents"] = {
				[14530] = 2,
			},
			["requiredSkill"] = 300,
			["teaches"] = 470349,
		},
	})

end
