local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB core data — WoW Vanilla, Fishing (locale-independent)
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 2 recipes

local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadCore(356, {
		[7732] = {
			["difficulty"] = {
				125,
				125,
				125,
				125,
			},
			["itemId"] = 16083,
			["reagents"] = {},
			["requiredSkill"] = 125,
			["teaches"] = 7732,
		},
		[18248] = {
			["difficulty"] = {
				200,
				200,
				200,
				200,
			},
			["itemId"] = 16082,
			["reagents"] = {},
			["requiredSkill"] = 200,
			["teaches"] = 18248,
		},
	})

end
