local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB never-implemented recipes - WoW Vanilla (locale-independent)
-- Auto-generated by tools/build-hidden-recipes.py. Do not hand-edit.
--
-- Recipes that exist in the client's spell tables but were never obtainable
-- by any means, in any expansion. Curated by AllTheThings (MIT); see the
-- Credits section of README.md. No client signal reveals this.
--
-- 67 never-implemented recipes for this expansion; 25 of them
-- are in the 1564 recipes this version ships. The rest are kept anyway, so
-- adding recipes later cannot silently un-hide one.

local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib then return end

lib:LoadHiddenRecipes({
[2336]=true,
[2369]=true,
[2371]=true,
[2577]=true,
[2578]=true,
[2579]=true,
[2671]=true,
[5395]=true,
[6441]=true,
[6470]=true,
[6471]=true,
[6619]=true,
[6651]=true,
[7434]=true,
[7439]=true,
[7448]=true,
[7451]=true,
[7636]=true,
[7769]=true,
[7853]=true,
[7855]=true,
[7864]=true,
[7865]=true,
[8296]=true,
[8366]=true,
[8368]=true,
[8387]=true,
[8388]=true,
[8778]=true,
[9942]=true,
[10550]=true,
[10844]=true,
[11447]=true,
[12062]=true,
[12063]=true,
[12068]=true,
[12083]=true,
[12087]=true,
[12090]=true,
[12680]=true,
[12681]=true,
[12682]=true,
[12687]=true,
[12689]=true,
[12690]=true,
[12691]=true,
[12719]=true,
[12720]=true,
[12722]=true,
[12900]=true,
[12904]=true,
[16660]=true,
[16960]=true,
[16965]=true,
[16967]=true,
[16980]=true,
[16986]=true,
[16987]=true,
[17579]=true,
[19106]=true,
[22430]=true,
[22434]=true,
[24844]=true,
[26179]=true,
[28327]=true,
[30021]=true,
[30047]=true,
})

end
