local _, ns = ...
ns.LibProfessionDBDataLoaders = ns.LibProfessionDBDataLoaders or {}
ns.LibProfessionDBDataLoaders[#ns.LibProfessionDBDataLoaders + 1] = function()
-- LibProfessionDB core data — WoW Vanilla, Mining (locale-independent)
-- Auto-generated by the TOGProfessionMaster authoritative-data pipeline. Do not hand-edit.
-- 13 recipes

local lib = LibStub and LibStub("LibProfessionDB-1.0", true)
if not lib or not lib:IsGameVersion("Vanilla") then return end

lib:LoadCore(186, {
		[2657] = {
			["craftedItemId"] = 2840,
			["difficulty"] = {
				1,
				13,
				25,
				70,
			},
			["reagents"] = {
				[2770] = 1,
			},
			["requiredSkill"] = 1,
			["teaches"] = 2657,
		},
		[2658] = {
			["craftedItemId"] = 2842,
			["difficulty"] = {
				1,
				50,
				100,
				125,
			},
			["reagents"] = {
				[2775] = 1,
			},
			["teaches"] = 2658,
		},
		[2659] = {
			["craftedItemId"] = 2841,
			["difficulty"] = {
				1,
				33,
				65,
				115,
			},
			["reagents"] = {
				[2840] = 1,
				[3576] = 1,
			},
			["teaches"] = 2659,
		},
		[3304] = {
			["craftedItemId"] = 3576,
			["difficulty"] = {
				1,
				25,
				50,
				75,
			},
			["reagents"] = {
				[2771] = 1,
			},
			["teaches"] = 3304,
		},
		[3307] = {
			["craftedItemId"] = 3575,
			["difficulty"] = {
				125,
				130,
				135,
				140,
			},
			["reagents"] = {
				[2772] = 1,
			},
			["requiredSkill"] = 125,
			["teaches"] = 3307,
		},
		[3308] = {
			["craftedItemId"] = 3577,
			["difficulty"] = {
				155,
				170,
				177,
				185,
			},
			["reagents"] = {
				[2776] = 1,
			},
			["requiredSkill"] = 155,
			["teaches"] = 3308,
		},
		[3569] = {
			["craftedItemId"] = 3859,
			["difficulty"] = {
				165,
				165,
				165,
				165,
			},
			["reagents"] = {
				[3575] = 1,
				[3857] = 1,
			},
			["requiredSkill"] = 165,
			["teaches"] = 3569,
		},
		[10097] = {
			["craftedItemId"] = 3860,
			["difficulty"] = {
				175,
				175,
				175,
				175,
			},
			["reagents"] = {
				[3858] = 1,
			},
			["requiredSkill"] = 175,
			["teaches"] = 10097,
		},
		[10098] = {
			["craftedItemId"] = 6037,
			["difficulty"] = {
				230,
				230,
				230,
				230,
			},
			["reagents"] = {
				[7911] = 1,
			},
			["requiredSkill"] = 230,
			["teaches"] = 10098,
		},
		[14891] = {
			["craftedItemId"] = 11371,
			["difficulty"] = {
				230,
				230,
				230,
				230,
			},
			["reagents"] = {
				[11370] = 8,
			},
			["requiredSkill"] = 230,
			["teaches"] = 14891,
		},
		[16153] = {
			["craftedItemId"] = 12359,
			["difficulty"] = {
				250,
				250,
				250,
				250,
			},
			["reagents"] = {
				[10620] = 1,
			},
			["requiredSkill"] = 250,
			["teaches"] = 16153,
		},
		[22967] = {
			["craftedItemId"] = 17771,
			["difficulty"] = {
				1,
				155,
				310,
				320,
			},
			["reagents"] = {
				[12360] = 10,
				[17010] = 1,
				[18562] = 1,
				[18567] = 3,
			},
			["teaches"] = 22967,
		},
		[1213638] = {
			["craftedItemId"] = 234003,
			["difficulty"] = {
				300,
				315,
				322,
				330,
			},
			["itemId"] = 234278,
			["reagents"] = {
				[12655] = 2,
				[22203] = 2,
			},
			["requiredSkill"] = 300,
			["teaches"] = 1213638,
		},
	})

end
